### ISSUE TITLE
Revisit choke group with CC mapping

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#1021]
Hi,

Last time I check the choke group with the same number, it still has issue (which i think Paul had fixed in some last build), but now seems trouble again.
The issue is, when mapping the region using CC (common use for hihat mapping to CC 4 for play with e-drums kit), which the openness degree mapped to a same key and across different CC level. With the last fix (same group/off_by number don't choke), however when using CC-mapped like this, it should be choke.
I attach a test file for quick check :
[choke_cc_check.zip](https://github.com/sfztools/sfizz/files/7520562/choke_cc_check.zip)

**Comment by paulfd** [comment]
Hi @kinwie ! I'll check it out. Does sforzando handle it properly for me to compare?

**Comment by kinwie** [comment]
Yes it works well in sforzando.
It doesn't works in Cakewalk players (Dropzone, Rapture, etc) since it's their limitation.
Keysw 48 is the normal key mapping. Keysw 50 is the CC mapping
So, mapping like this, users can switch the hihat mode instantly.

For CC mapping keysw 50, play note 62 with CC at high value ( so it is open hat) then move the cc to lower value and play the note agian for closed hat. Open hat should be choked.

**Comment by paulfd** [comment]
Maybe try the PR above? What I put is more than the CC switch, it's going to choke the region if it is disabled by any mean (CC, keyswitch, ...). Maybe that is too much but it seemed to match what is expected more or less: if a region is currently disabled, it should be considered in "another choke group" regardless of the conditions.

**Comment by paulfd** [comment]
I'll change it to only CC though, after thinking about it.

**Comment by kinwie** [comment]
thanks @paulfd for  looking into this. Where to download the new setup btw?

**Comment by paulfd** [comment]
If you go to https://github.com/sfztools/sfizz/actions, you have the list of CI runs. If you click on the last one related to the pull request, it will load up the summary, and there you have the artifacts to download.

The direct link for this one is https://github.com/sfztools/sfizz/actions/runs/1456579150.

**Comment by kinwie** [comment]
Yes, I got it. Tested and the choke works just fine now with the CC. Thanks for this, I feel relieved :)
I just wish this can become the "Native SFZ choke behavior" since it's what Rene's original design and perfected in sfizz!

Anyway, everytime I click something on the UI, e.g. moving the CC 4 knob, it crashed VstHost (32-bit, vst3), also SaviHost. It's a random crash and just because when clicking on the UI. Maybe @jpcima knows something about it?

**Comment by paulfd** [comment]
Maybe it's me, I changed many things in the UI recently. I'll put up another issue for it.

**Comment by paulfd** [comment]
Thanks for the report, as always !

> Yes, I got it. Tested and the choke works just fine now with the CC. Thanks for this, I feel relieved :) I just wish this can become the "Native SFZ choke behavior" since it's what Rene's original design and perfected in sfizz!

Good thing is we have a nice test coverage for all these cases so it should keep getting better.
