### ISSUE TITLE
Crash in VstHost/Savihost

### ISSUE THREAD

**Issue by paulfd** [sfztools/sfizz#1026]
> Anyway, everytime I click something on the UI, e.g. moving the CC 4 knob, it crashed VstHost (32-bit, vst3), also SaviHost. It's a random crash and just because when clicking on the UI. Maybe @jpcima knows something about it?

**Comment by kinwie** [comment]
Thanks @paulfd for opening this issue

**Comment by paulfd** [comment]
After some testing, the error seems to be in `processUnorderedEvents()`. Something seems to be corrupting the queue as soon as you touch a GUI control (not the keyboard notes though).

**Comment by paulfd** [comment]
@jpcima 
```c++
if (vq) {
    // Note: expectation that hosts does not send more than one
    //       queue for one parameter
    Vst::ParamID id = vq->getParameterId();
...
```
well, guess what? 😄

**Comment by paulfd** [comment]
Can we even assume that the points within a queue are ordered?

**Comment by paulfd** [comment]
@kinwie can you try the build in https://github.com/sfztools/sfizz/pull/1035? The artifacts are at https://github.com/sfztools/sfizz/actions/runs/1484845374

**Comment by kinwie** [comment]
I just tested it. It's now no more crashing. It's seems okay in VstHost.
But there is an issue in SaviHost. Moving CC knobs problem, it stays at zero after click and move the knob. Only the Volume (cc7) knob works normally.
Btw, Savihost is the standalone host version.

**Comment by kinwie** [comment]
Ohh wait. 3rd time test in savihost, the problem seems gone. Not sure what it was but now woks fine.
Thanks @paulfd for fixing this!

**Comment by paulfd** [comment]
I've seen that Savihost, like Ardour, doesn't force knobs to linear mode. I cancorrect this.
