### ISSUE TITLE
Exponents Are Ignored

### ISSUE THREAD

**Issue by SirGawain99** [sfztools/sfizz#1029]
Some sfz libraries converted from SoundFonts using Sforzando, contain exponents in their opcode values. These exponents are ignored by sfizz, and only the base is read. One such library, is the NS_Kit7 Free Lite drumkit by Douglas Whates. An ampeg_attack opcode used throughout that library is given the value 6.02385e-009. Sfizz reads this as 6.02385 seconds, and very little sound is produced from a drum beat after six seconds.

**Comment by paulfd** [comment]
I'll check it out, thanks for the report !
