### ISSUE TITLE
Sfizz doesn't respond to audio level changes

### ISSUE THREAD

**Issue by Aouxr** [sfztools/sfizz#1045]
Sfizz does not respond to midi volume changes coming from my DAW.  My operating system is arch linux.  I used the default sfizz instrument.  My DAW is MusE (version 4), but I also tested sfizz in Qtractor with the same results. The problem seemed to start in sfizz version 1.1.0, and persists in 1.1.1.  When I downgrade sfizz to version 0.5.1 the problem disappears.  

Steps to reproduce in MusE:
1. Open MusE.
2. Add new sfizz synth track.
3. Add midi track with midi data.
4. Press play.
5. Adjust the volume slider during playback (or add volume automation to the Midi track in step 3).

Expected behavior:
Volume level should change as the volume slider of the midi track is adjusted.

Actual behavior:
The midi note in sfizz plays at a constant level.

I was able to circumvent this behavior by using carla-rack in MusE and changing the sfizz cc007 to midi channel 2 from within the carla settings. The steps are:
1. Open MusE.
2. Add new carla-rack synth track.
3. Open carla-rack GUI.
4. Click "add plugin" in carla-rack and and select sfizz.
5. Press the wrench button in the sfizz entry in carla-rack.
6. Open the "parameters" tab.
7. Scroll down to "controller 007" and press the "..." button.
8. Hover over the "midi channel" button and change from channel 1 to channel 2.
9. Go back to the main MusE window and add midi track with midi data.
10. Press play.
11. Adjust the volume slider during playback (or add volume automation to the track in step 9).

With this setup, sfizz 1.1.1 follows the volume slider changes in MusE, but I don't like to do it this way because it makes the audio crackly and cuases sfizz reverts to its default instrument when I save the MusE project and restart MusE.

Thank you for all your hard work on this project. I really love the new GUI features you implemented in version 1.1.0

**Comment by paulfd** [comment]
Is this the LV2 or VST3 plugin? Does this happen with both? I'll check in the WE if I find some time.

**Comment by Aouxr** [comment]
This problem seems to only occur with the LV2 plugin. I have not been using the VST3 plugin because MusE does not support VST3 and Qtractor does not find the VST3 plugin (even though it finds the other VST3 plugins in the same directory). I just tried loading the Sfizz VST3 plugin from Carla-Rack within MusE and the volume automation worked fine (without me having to change the midi channel).

**Comment by paulfd** [comment]
Makes sense. It's probably a side-effect of a similar issue to #1042. I'm a bit sad because I think any solution is a bad solution to this particular problem... Anyway, I'll investigate and come back to you.

**Comment by Aouxr** [comment]
Thanks!

**Comment by paulfd** [comment]
Would you mind trying #1054?

**Comment by Aouxr** [comment]
I just installed the lv2-midi-rollback branch, and the midi automation in the lv2 plugin works perfectly now! 
Thank you so much.
