### ISSUE TITLE
Very prone to xruns (at least on older hardware)

### ISSUE THREAD

**Issue by TauPan** [sfztools/sfizz#1055]
I've just started using ardour and experimenting with stuff so please bear with me if I've overlooked something important.

I'm trying to get https://github.com/michaelwillis/virtual-playing-orchestra-ardour-template to run in ardour 6 and I have a very old laptop (mentioning this early in case you think you don't want to support old hardware ... it's a Lenovo Thinkpad W500 with 4G Ram and a double core  Intel(R) Core(TM)2 Duo CPU T9600  @ 2.80GHz ... a new one is ordered).

There was only noise so I started a new ardour project with just the sfizz lv2 plugin to figure out what might be the cause.

When I load e.g. all-strings-SEC-PERF-panned.sfz from http://virtualplaying.com/virtual-playing-orchestra/ (performance) into your lv2 plugin and press a few keys CPU and DSP load quickly gets to 100% and there's only very ugly noise.

If I try the same with the https://github.com/swesterfeld/liquidsfz plugin (which doesn't support all opcodes apparently) or with carla (which doesn't give me any diagnostics about the supported opcodes) everything is fine and DSP load is within safe parameters (60% max when I'm wildly dragging the mouse over the virtual keyboard).

(So it looks like I'll continue my experiments with liquidsfz for now but sfizz looks very promising as well and it has the more recent commits.)

Of course I'm willing to conduct any kind of experiment to give you more actionable information here.

Best regards
Friedel

**Comment by paulfd** [comment]
Which build are you using? Is this true of every/most sfz files you tried or mostly this one? 

> If I try the same with the https://github.com/swesterfeld/liquidsfz plugin (which doesn't support all opcodes apparently) or with carla (which doesn't give me any diagnostics about the supported opcodes)

I'm not discounting improvements we could do to sfizz, but as a matter of fact some of the more "advanced" opcodes can come with a significant computational cost. The best would be to compare to sforzando, but I think even then it'd probably be more taxing.

> (So it looks like I'll continue my experiments with liquidsfz for now but sfizz looks very promising as well and it has the more recent commits.)

Sure use whatever works out for you.

**Comment by TauPan** [comment]
> Which build are you using? Is this true of every/most sfz files you tried or mostly this one?

I've tried building myself from the devel branch and after that I tried with the ubuntu package from obs. The effect was about the same.

I can try with different sfz files later.

> > If I try the same with the https://github.com/swesterfeld/liquidsfz plugin (which doesn't support all opcodes apparently) or with carla (which doesn't give me any diagnostics about the supported opcodes)
> 
> I'm not discounting improvements we could do to sfizz, but as a matter of fact some of the more "advanced" opcodes can come with a significant computational cost. The best would be to compare to sforzando, but I think even then it'd probably be more taxing.

I don't have windows on that laptop so I could only try sforzando via wine and I think you're saying that performance would probably not be better even running natively under windows?

New laptop will arrive some time in February so  until then would it  be interesting if I experiment with some of the performance related PRs in here? (But I didn't check if they would even help with my processor family.) ​

> > (So it looks like I'll continue my experiments with liquidsfz for now but sfizz looks very promising as well and it has the more recent commits.)
> 
> Sure use whatever works out for you.

Of  course!  I know that performance optimization is always a lot  of work and in that case it may absolutely not be worth the effort.

In fact my box is well below the performance requirements given for the ardour template I'm trying to use.

I think even if I would replace sfizz with liquidfz everywhere in that template and use a more efficient delay it would probably still be unusable because of the sheer number of active plugins involved. For me the goal is just learning and experimentation.

In any case thanks for your reply!

**Comment by paulfd** [comment]
> I don't have windows on that laptop so I could only try sforzando via wine and I think you're saying that performance would probably not be better even running natively under windows?

Yes it probably wouldn't be better. It's just sforzando's engine is very good, and it has similar/better opcode coverage. If they're that much faster (and they are usually) then we do have real progress to do. It gives an upper bound in a way. As an example, in a previous release, we integrated the `loop_crossfade` opcode which adds more complex looping logic dead into the real-time callback. I suspect this kind of thing does impact performance in very practical ways.

> Of course! I know that performance optimization is always a lot of work and in that case it may absolutely not be worth the effort.

It is worth it and I'd very much like to do so, it's just hard thankless work most of the time :) Although I have to admit I would target armv7 archs before older x86 platforms; they're just more popular these days. My immediate goal is to have sfizz run on most things (and it does mostly, even in javascript now). Then we can tweak it more.

**Comment by TauPan** [comment]
Uhm, I'm afraid this has turned into a case of "I can't reproduce it any more."

Very sorry about this.

After a reboot of the laptop I ran a couple of experiments and while I could not get sforzando to run at all, I tried with the VST3 and the LV2 version of the sfizz plugin under carla and ardour and while DSP load is high (still higher than with liquidsfz, but marginally) there were no bad xruns.

I don't really have an explanation for this. I did fully replace my self-compiled version of sfizz with the ubuntu package before and I think there were no processes in the background causing cpu and/or dsp load.

I don't see a significant performance difference between liquidsfz and sfizz in ardour any more. Both plugins run more smoothly in carla, but that may be ardour causing more cpu load for other things.

Especially I have no explanation for liquidsfz *and* sfzero (inside carla) running faster than sfizz before the reboot.

**Comment by paulfd** [comment]
(I don't know how computer-literate you are so I am going to assume you know your way, since you started by building from source. If anything is unclear please tell me and I will explain 😄)

One explanation could be that the default build model when building from source is release-with-debug-symbols, which create fatter binaries. Your xruns could have come from the fat binaries and the fact that the older processor, having less cache, has to work more to fetch the instructions to execute. The package has no debug symbols.

Or it could be something else entirely 😄 if it reappears don't hesitate to reopen !
