### ISSUE TITLE
amp_veltrack_onccN issue

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#1065]
Hi sfizz,

I just tried the `amp_veltrack_onccN` implementation that was done in here ;
https://github.com/sfztools/sfizz/issues/483
with this simple test :

```
<control>
set_cc31=127

<region>
sample=crash.wav
key=60
loop_mode=one_shot
amp_veltrack_oncc31=-100
amp_veltrack_curvecc31=2
```

Moving the CC via MIDI controller knob does work.
The issue is, the specified CC number not displayed on sfizz control panel.
That's what needed for user to adjust the value via UI knob to match personal taste.

Same for `fil_veltrack_onccN` and `pitch_veltrack_onccN`, no CC on UI.

**Comment by paulfd** [comment]
Thanks for the catch! #1066 should solve this if you can try.

**Comment by kinwie** [comment]
A quick test of #1066 , it's good so far, thank you Paul!
