### ISSUE TITLE
LV2 display issue

### ISSUE THREAD

**Issue by trebmuh** [sfztools/sfizz#107]
Hi all. Reporting it here after talking a bit about it for it not to be forgotten.

I've been trying sfizz version 0.3.0 from the github release tarball. A strangish stuff is that on my first try, the LV2 looked like:
![sfizz-lv2-ok](https://user-images.githubusercontent.com/8705846/76221067-c4e06980-6218-11ea-9a25-0a7fce5a4ce1.png)
now it looks like:
![sfizz-lv2-pasok](https://user-images.githubusercontent.com/8705846/76221083-cdd13b00-6218-11ea-8625-4fe69ff7504a.png)
Note the **display order** of the different items. It doesn't look to have any impact on the sounds, just it is strange that the display order is changing.

Note: launched with jalv.select.

HTH and thanks for sfizz!

**Comment by jpcima** [comment]
This is the logic behind it:

The 3 parameters 'Polyphony, Oversampling, Preload" belong in the parameter group "Configuration".
They will always show under the heading Configuration regardless of case, and always in that order.

The others 3 don't belong in a group, and they are listed always in identical order "Volume, Freewheeling, File SFZ".

As it seems, there is not a strict order enforced to display the group.
In case 1, Jalv does not display any hint that tell us the (3,3) parameters group are separated, and we are confused to think they are all part of "Configuration", which is not the case.

A solution will be to assign all parameters a group such that they're better organized visually.
Also we should research if LV2 permits to enforce an order on parameter groups.

**Comment by trebmuh** [comment]
Oh yes, you're right. I launch it a few times in a row, there is no way to predict if it's going to be displayed in the first picture order or the second one.

**Comment by jpcima** [comment]
I don't think there exists currently any way to put parameters in groups
(eg. like `SFZ file`, which is not to be confused with control ports).

Jalv doesn't handle this, or it's LV2 specification, I'm not sure of which it is.

Regardless, I would also think that the general issue of layout in presence of groups is something that is best handled at Jalv side. It could be a horizontal line separator placed between the adjacent groups.

**Comment by paulfd** [comment]
Hi!
So in the end this is an upstream problem right? If so, I'll close this for now. I would still prefer another way to set these parameters anyway, since they're not really real-time parameters as much as global configuration points...

**Comment by jpcima** [comment]
>So in the end this is an upstream problem right?

It is. I close this issue which belongs to upstream.
