### ISSUE TITLE
cc140 treats keyswitch as previous note

### ISSUE THREAD

**Issue by Windsurfer152** [sfztools/sfizz#1074]
I've been trying to simulate legato by using keyswitches.

Unreal Instruments Two Whistles has a "tongued" patch (named "Tanging") and 
 a "Fast legato" (Legato_Fast) patch, which creates a slight portamento into the main pitch based on cc140=30.

On a real instrument you might tongue the first note of a phrase to start the airflow and then moderate the airflow as you play subsequent legato notes in order to get them in tune. That's what I think the "Fast legato" tries to emulate.

Fast Legato works really well after the first note of the legato phrase, so the basic implementation is great. But if I hit the Fast Legato keyswitch first (obviously located at the other end of the keyboard from the sounding notes) I get a huge portamento into the first note.

Likewise if I hit the Tang keyswitch, play a note, hit the Fast Legato keyswitch and play another note I get the same huge portamento.

So it seems that cc140 is treating the keyswitch as the note number it uses to calculate the pitch delta.

Is it possible to only include notes that trigger samples so the note numbers of the keyswitches are ignored?

**Comment by paulfd** [comment]
Thanks for the report; I'll check out the behavior of other implementations and correct it if necessary !

**Comment by kinwie** [comment]
I check CC140 with keyswitches in sforzando.
It's the same, it treats keyswitch notes as previous note also.

I think this is quite similar to last year issue, which is ARIA's behavior not excluding keyswitches range as notes range.

**Comment by DSmolken** [comment]
Yes, Sforzando definitely behaves like this, ran into it with Turkish Rebab which keyswitches between legato and non-legato articulations, and the Hadzi-Fia and Hadzi-Hevi vocals which keyswitch between legato syllables. Haven't figured out a workaround of any sort yet, but can confirm this is ARIA behavior.

**Comment by kinwie** [comment]
Just checking again,
In Cakewalk player (DropZone, Dimension etc), also treat keyswitch notes as previous note.
_(example using trigger=legato, cause no porta cc140 in CW)_

**Comment by kinwie** [comment]
@paulfd 
So I guess this need some consideration to decide what best solution for it.
I understand from user POV, excluding keyswitches range from playable note range is a good practical usage.
I believe there is no detailed rule explained in the official SFZ v1 format specs for this keyswitch range behavior.
You are the boss, you decide, LOL

**Comment by paulfd** [comment]
Is there any upside to having a keyswitch register as previous note for cc140?

**Comment by kinwie** [comment]
I don't think so.
If we want the "ghost" glide-in from a previous note, we can always press a blank key to do so.
That's more logic and flexible I think, so the unwanted glide from the keyswitch note can be always avoided.

**Comment by DSmolken** [comment]
I can't think of an upside, either. If I really tried I could maybe think of some edge case where this would be an advantage, but that would be a rare and special usage, and it's definitely a downside for "normal" keyswitching legato instruments.

**Comment by paulfd** [comment]
I know it's almost gravedigging, sorry... To push this idea further, should any of the extended CC be changed by a keyswitch note? e.g. 131, 133, ...

I've tried disabling them all in #1113 if someone wants to give it a shot!

**Comment by MTornPDX** [comment]
I won't get a chance to try it out for a while, but off the top of my head, absolutely a keyswitch note should NOT trigger any extended CCs. So I think that your thinking is correct here.
