### ISSUE TITLE
output_onccN for multi-out flexibility

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#1079]
Since the `output` opcode already implemented and working in sfizz, another request for new opcodes :
`output_onccN` and `output_curveccN`

So we can placed CC control on UI that can be flexible re-routed by users.
This way, the Instrument-makers don't need to make 2 redundant preset files just for output differences.

**1st example** here, the output path can be freely assigned with each CC :
```
<control>
label_cc21=Kick Output
label_cc22=Snare Output
label_cc23=Hat Output
label_cc24=Crash Output

<group>
loop_mode=one_shot

<region>
sample=kick.wav
key=60
output_oncc21=127

<region>
sample=snare.wav
key=62
output_oncc22=127

<region>
sample=hat.wav
key=64
output_oncc23=127

<region>
sample=crash.wav
key=65
output_oncc24=127
```
![output_1](https://user-images.githubusercontent.com/65444898/154235746-cd386cbb-7a44-4cc1-803e-d5fa3538a645.png)

When all CCs are 0, all regions will go to output 0, the Stereo Main Output.
When it changed, _(like in the pic)_ :
- Kick -> Stereo Output No.2
- Snare -> Stereo Output No.3
- Hat -> Stereo Output No.4
- Crash -> Stereo Output No.5

**2nd example**, with the curve set to On/Off style and single CC :
```
<control>
label_cc21=Multi-Output

<group>
loop_mode=one_shot

<region>
sample=kick.wav
key=60
output_oncc21=1
output_curvecc21=9

<region>
sample=snare.wav
key=62
output_oncc21=2
output_curvecc21=9

<region>
sample=hat.wav
key=64
output_oncc21=3
output_curvecc21=9

<region>
sample=crash.wav
key=65
output_oncc21=4
output_curvecc21=9

<curve>
curve_index=9
v000=0
v001=1
v127=1
```
![output_2](https://user-images.githubusercontent.com/65444898/154235863-ce22af42-bacd-403c-a745-d01a4fcbeef7.png)

When CC 21 is 0 (off), all regions will go to output 0, the Stereo Main Output.
When it set to 127 (on), each region will be separated to each output _(same as 1st example)_.

**Comment by kinwie** [comment]
I link this issue for monitoring :
https://github.com/redtide/test/issues/4

**Comment by DSmolken** [comment]
I think this would be very useful for drum kits, where the decision how many outputs to split the mics into is made while working on a track. Should room mic be sent to the same output as overheads, its own output, or just left unused, for example. This opcode would both help instrument makers avoid duplication for multiout, and help users use those outputs in more flexible ways.

**Comment by paulfd** [comment]
@kinwie I don't know if you've seen this but if you load a multi-out SFZ file in the single output VST, it will route every output to the first one.

I'll see about this though :)

**Comment by kinwie** [comment]
Ooohh, It's a brilliant solution, Paul! and it actually solved this need.
Yes, I can confirm it works fine.
Multi-output sfz file all routed to Setreo Main Output in sfizz stereo version.
I guess this issue is solved, but if `output_onccN` is not hard to be added, it should be great also.
For the moment, the use case I can see is for Example No.1 above.
For future consideration, if anyone going to make a multi-out drum plugin based on sfizz, then `output_onccN` might be needed.

I think these special behaviors and features that already implemented in sfizz would be nice get detailed documented in sfzformat.com, as now sfizz slowly becoming the major sfz player. I guess @DSmolken agree with these?

**Comment by DSmolken** [comment]
A choice of stereo out or mulitouts, depending on what the SFZ is loaded into - that looks to me like this is a good solution already. Adding an extra opcode would allow for some additional flexibility with routing multiple mics to one channel, but that would be just a "nice to have" in my view, as it can already be done by using multiout then routing stuff within the DAW.

As far as documenting special features that aren't in ARIA, yeah, we should. Many opcodes already have a "Practical Considerations" section for player-specific implementations, and at least mentioning that output now is implemented is a pretty big deal.

**Comment by kinwie** [comment]
Okay I agree.
We just need to adapt to this behavior to using either stereo or multi-out version of the plugin and it's enough for the next 10 years I guess. We don't need to make 2 redundant sfz presets anymore with this feature.

I'll close this issue tomorrow for it already been solved by current solution noted by Paulfd.

Funny really, for 20 years, the `output` opcode never implemented anywhere, now we have it here.
So, a really big thanks to @paulfd and @jpcima for this.

**Comment by kinwie** [comment]
I'll open a new issue, for increasing output numbers.
Since we follow sfz rule, output paths are counted as stereo pair.
Sfizz currently has 16 outputs (mono), thus just 8 stereo outputs. Will be enough if we can have 16 stereo outs (32 mono).
Then this multi-output quest can finally done...

**Comment by kinwie** [comment]
This is solved so I close it now
