### ISSUE TITLE
VST3 plugins are showing up twice

### ISSUE THREAD

**Issue by MTornPDX** [sfztools/sfizz#1093]
In all DAWs I've tried, the VST3 version of Sfizz shows up as two separate identical plugins.
I've double checked that I don't have two versions installed by mistake.

**Comment by paulfd** [comment]
It should be the stereo and 16 out versions, if you can try. Only REAPER advertise them properly atm I think.

**Comment by MTornPDX** [comment]
Hey, you're right! They do look absolutely identical until I find that I can enable the extra channels on one version.
In Studio One at least, I don't see stereo+16, it shows up as 8 stereo feeds, addressed in the SFZ file with output=0 to output=7. Numbers higher than 7 defaults to output 1.

Is the stereo-only version needed at all? As long as the SFZ file doesn't define any outputs, the multi-out one works just the same, right? In some VSTs you can switch between stereo and multi in their preferences.

No multi output version for AU, correct?

**Comment by paulfd** [comment]
> Hey, you're right! They do look absolutely identical until I find that I can enable the extra channels on one version. In Studio One at least, I don't see stereo+16, it shows up as 8 stereo feeds, addressed in the SFZ file with output=0 to output=7. Numbers higher than 7 defaults to output 1.

Yeah. I don't know if it defaults to 1, or wrap around modulo 8 but it's one of the two.

> Is the stereo-only version needed at all? As long as the SFZ file doesn't define any outputs, the multi-out one works just the same, right? In some VSTs you can switch between stereo and multi in their preferences.

Besides UI clutter with the levels, there is a little added complexity in the multiple output version (if anything it zeros and checks all the empty outputs on each callback). It also kinda clutters the DAW UI depending on the DAW.

> No multi output version for AU, correct?

I'm not sure, the AU is wrapped from the VST so if the wrapper doesn't do multiple outputs I guess now. Now I have a Mac so I can try.

**Comment by paulfd** [comment]
> In some VSTs you can switch between stereo and multi in their preferences.

Hmm in other plugin formats (e.g. LV2) the number of outputs is fixed in the manifest so it order to be compatible I'm not planning on making it a setting.

I added a suffix to the multi-out VST to differentiate. If someone wants to pick up the multi-out AU we can reopen an issue, thanks!
