### ISSUE TITLE
Version numbers are inconsistent

### ISSUE THREAD

**Issue by MTornPDX** [sfztools/sfizz#1096]
I believe this reflects the latest versions, unless I'm not fully up to date:

AU version shows in the plugin listings as 0.39.216 and 1.2.0ff0de9c within the plugin.

VST3 version shows in the plugin listings as 1.2.0 and 1.2.0ff0de9c within the plugin.

Presumably only the "0.39.216" in the AU is incorrect?

**Comment by paulfd** [comment]
Hopefully solved by f2f37d73b040856e91260034a17ef9d221cd8dc5 !
