### ISSUE TITLE
Controls Are Not Saved in Reaper

### ISSUE THREAD

**Issue by SirGawain99** [sfztools/sfizz#1098]
Scenario:
1.) In a Reaper project, load sfizz as a VST3 instrument.
2.) In sfizz, load a SFZ sample library with various MIDI controls such as offset, attack & release.
3.) Adjust the controls as desired and save the result as a preset, export the instrument to a .vstpreset, or save the FX chain to a .RfxChain.
4.) Close and re-open the project in Reaper.

![Adjusted](https://user-images.githubusercontent.com/94105625/178381030-fd70c7bf-8afb-480a-af2d-0204301aac7b.jpg)
[Adjusted Controls]

Result:
The sfizz VST3 instrument remains in the project with the desired sample library loaded. However, all of the control settings are reset to their defaults, including Volume. Importing the previously exported FX chain or preset has no effect on the controls.

![Default](https://user-images.githubusercontent.com/94105625/178381140-02941d37-4aab-46ab-a1eb-eef03f2acdf6.jpg)
[Controls Reset to Defaults]

Reaper seems unable to find the VST's settings, and sfizz might require it's own method of exporting settings to a file. (This might be better placed under Feature Requests) A similar issue is described by others here...
https://www.reddit.com/r/Reaper/comments/phy25e/reaper_not_saving_some_vst_settings/

...as well as here, with replies from Justin himself:
https://twitter.com/SampleScienceSo/status/1437693077444087808

Linux Mint 20.3, Mate
Reaper 6.63
sfizz 1.2.0

**Comment by MTornPDX** [comment]
I think this might be down to a quirk in how SFZ maps its performance knobs. Unlike the knobs in most VSTs, these don't actually edit the sound - the text file of the SFZ remains unchanged. Instead the just send CC values from the front panel to the engine, just as if you had turned up your modulation wheel on your controller keyboard.

I don't know if there's any way to make Reaper remember control change settings as part of a preset, but I suspect it doesn't. Unfortunately I don't think there's a fix possible for this, other than changing how Sfizz (and SFZ in general) handles its performance knob technology.

Of course, you COULD record the CC values of you choice into your sequencer as performance MIDI data.

**Comment by SirGawain99** [comment]
> the text file of the SFZ remains unchanged
That's what I was thinking, too, which is why I said this might be better placed under Feature Requests. If sfizz is smart enough to read the SFZ file and place knobs accordingly, it's presumably smart enough to read user input and store a record of the changes. What I guess I'm asking for, is a means of exporting sfizz settings to a text file for recalling later.

>record the CC values of you choice into your sequencer 
That's not a bad idea! The necessary settings would be stored with the project, where they belong. Thank you!

**Comment by SirGawain99** [comment]
On Thursday, July 21, 2022 at 05:30:56 AM GMT+2, Paul Ferrand ***@***.***> wrote: 

> CC state should be saved and restored.
> By any chance could you try the LV2? Does it also behave like this?

Hay Paul. Thank you for responding. I'm sorry I've only seen this now.

I'll give the LV2 a try this evening and let you know. Curiously, *some* of the CC states are remembered, such as volume, pan & expression. The CC's that are being ignored, are those I've created in the .SFZ, such as Offset, Attack and Release for individual instruments. I've carefully avoided assigning any default values in the .SFZ so as to avoid those being adopted at startup.

Another minor irritation, is that switching on my MIDI keyboard after a library is loaded, causes the volume to be reset to 127 regardless of the default setting in a .SFZ file or subsequent adjustments. I just make sure to power up my Korg SP-170S before starting Reaper.

Gavin

**Comment by paulfd** [comment]
I'll give it a more thorough try as soon as I find some time.

> Another minor irritation, is that switching on my MIDI keyboard after a library is loaded, causes the volume to be reset to 127 regardless of the default setting in a .SFZ file or subsequent adjustments. I just make sure to power up my Korg SP-170S before starting Reaper.

It's probably the keyboard sending a value on CC7, you could check it out (and possibly filter it) using the ReaControlMidi plugin before sfizz.

**Comment by SirGawain99** [comment]
> CC state should be saved and restored. By any chance could you try the LV2? Does it also behave like this?

sfizz VST3i:
Loses CC values between Reaper sessions, but it behaves just fine until Reaper is closed.

sfizz LV2i:
Doesn't even remember CC values between switched FX windows. Checking a different effect's settings and then returning to sfizz, reveals that all controller values are visually returned to their defaults, although the adjusted values continue to be applied to the audio content.

Both VST3 and LV2 interfaces:
Saving the FX chain and adding it later loads the appropriate VST3 or LV2 instrument and sample library, but CC values are not restored.
Saving settings as a FX Preset doesn't help with either the VST3 or LV2 effect; none of the CC values are restored.
Exporting the VST3 preset (.vstpreset) and importing it later also doesn't restore CC values.

Three different SFZ libraries were tried in three different Reaper projects containing the test track only.
sfizz 1.2.0
Reaper 6.64
Linux Mint 20.3

**Comment by SirGawain99** [comment]
Update: CC values are not preserved when duplicating a track in Reaper. The relevant VST3i and SFZ instrument is loaded, but the controllers are all reset to their defaults in the duplicated track.

**Comment by SirGawain99** [comment]
Hey Paul. It looks like you've edited some files. Should I be compiling to test, trying a "current" version, or just waiting patiently for you to close the bug with #1115. No rush intended, just trying to better understand how this GitHub thing works.

**Comment by SirGawain99** [comment]
Jolly happy update: Sfizz "Current" version 1659342168.1eb36c4-0 on Linux Mint 20.3 (Ubuntu 20.04), which shows up as v1.1.1, is successfully saving all CC values with Reaper 6.69 projects as well as exported .vst3 settings. Thank you Paul et al!
