### ISSUE TITLE
[FR] list supported opcodes in Sfizz

### ISSUE THREAD

**Issue by AlexMitchellMus** [sfztools/sfizz#11]
It would be good to list currently implemented opcodes, similar to this page from Linux Sampler: https://www.linuxsampler.org/sfz/

**Comment by redtide** [comment]
like <https://sfzformat.com/software/players/sfizz> or <https://sfz.tools/sfizz/status>?
I'll need to check at some point if they are up to date.

**Comment by AlexMitchellMus** [comment]
Thanks, I didn't notice it.

Would it be possible to make the list more prominent? As opcode compliance is one of the most important things.

Also would it be possible to include in the list, or elsewhere what opcodes Sfizz is planning to support (in future).

I am specifically interested in the script opcode.

**Comment by redtide** [comment]
You can see our work in progress in our [to do road map]. A Linuxsampler script opcode is not planned, at least not ATM.

[to do road map]: https://github.com/sfztools/sfizz/projects/1
