### ISSUE TITLE
Build fails on armv6, armv7: error: unknown type name 'Elf32_auxv_t'

### ISSUE THREAD

**Issue by yurivict** [sfztools/sfizz#1116]
```
In file included from /wrkdirs/usr/ports/audio/sfizz/work/sfizz-0.4.0/src/external/cpuid/src/cpuid/cpuinfo.cpp:20:
/wrkdirs/usr/ports/audio/sfizz/work/sfizz-0.4.0/src/external/cpuid/src/cpuid/detail/init_linux_gcc_arm.hpp:43:5: error: unknown type name 'Elf32_auxv_t'
    Elf32_auxv_t auxv;
    ^
/wrkdirs/usr/ports/audio/sfizz/work/sfizz-0.4.0/src/external/cpuid/src/cpuid/detail/init_linux_gcc_arm.hpp:47:41: error: use of undeclared identifier 'Elf32_auxv_t'
        const auto size_auxv_t = sizeof(Elf32_auxv_t);
                                        ^
2 errors generated.
```

This failure is in src/external/cpuid.

Is it possible to change to use package-installed cpuid?

Version: 0.4.0
clang-14
FreeBSD 13.1

**Comment by redtide** [comment]
> Is it possible to change to use package-installed cpuid?

Apologies for these late replies.
AFAICS there is no `cpuid` package in major distributions of Linux and FreeBSD, so I have no idea how to identify it with CMake. Note that there is another one: <https://github.com/anrieff/libcpuid> (currently v0.6.3), but the one we are using is <https://github.com/steinwurf/cpuid/> (v8.0.0). I'm going to close these issues. Please reopen if still there.
