### ISSUE TITLE
Feature Request - Decouple the GUI to allow for development with other GUI Frameworks

### ISSUE THREAD

**Issue by Audiojunkie** [sfztools/sfizz#1134]
Currently, the existing GUI doesn't support High Resolution screens with Linux. Maybe it would be a good idea to decouple the GUI from SFIZZ so that other developers can create alternative GUIs (hopefully High Resolution supported GUIs) using different GUI Frameworks and Widget libraries.

**Comment by alcomposer** [comment]
Is it not already? Many developers have used libsfizz to add sfizz playback to their projects.

**Comment by Audiojunkie** [comment]
Interesting! I don’t code, and I wasn’t aware of the programs you mentioned. If this is indeed the case, then I think I can close this issue. 🙂

**Comment by Audiojunkie** [comment]
Apparently, libsfizz is the solution. 🙂
