### ISSUE TITLE
how to build sfizz without UI staff for android & ios

### ISSUE THREAD

**Issue by imiskolee** [sfztools/sfizz#1136]
hi,team:

I am not sure the project supports android or ios. I just want a SFZ Player engine without any UI staff, I checked already support C++ bindings. But, I do not know how to build it for android & ios.

**Comment by imiskolee** [comment]
I successful build for android, but found a lots static library,  so I just need link the libsfizz.a for my application. right?

**Comment by redtide** [comment]
HI! Sorry for the delay, yes you need to link the static library to your project. From now on this repository will only contain the library.
