### ISSUE TITLE
public key is not available: NO_PUBKEY 1DCC29D5F18761E8

### ISSUE THREAD

**Issue by anthony-cros** [sfztools/sfizz#1139]
Getting:

`W: GPG error: http://download.opensuse.org/repositories/home:/sfztools:/sfizz/xUbuntu_18.04  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1DCC29D5F18761E8`

Upon `sudo apt update` (following these instructions: https://software.opensuse.org/download.html?project=home%3Asfztools%3Asfizz&package=sfizz)

**Comment by redtide** [comment]
hello, sorry for the late reply! Are you still using 18.04?

**Comment by anthony-cros** [comment]
No worries, and yes, on this old machine I am (would rather not have to upgrade it!)

**Comment by redtide** [comment]
no, I can restore that version, though will need some time because some issues with build configuration

**Comment by redtide** [comment]
Sorry, I spoke too soon, the 18.04 CMake is 3.10 and now we require 3.13 at least. Would be possible for you to update at least to 20.04?

**Comment by redtide** [comment]
It should be there now, but it will be the last release supporting Bionic (CMake 3.10?). It would be nice if you could update at least to Focal. Let me know if the key issue persists or it's OK.

**Comment by anthony-cros** [comment]
Sounds good, and thanks a lot!

**Comment by paulfd** [comment]
@anthony-cros I'll close this for now, reopen if it's still a problem thanks!
