### ISSUE TITLE
Background image aspect ratio and display

### ISSUE THREAD

**Issue by ldrolez** [sfztools/sfizz#1140]
I've played with the 'image' tag, which is working quite well but, I'd like to know
- what is the recommended size/aspect ratio?
- why is there a gray area on the left (see photo)?
- would it be easy to have the same image in the 'knobs screen'?

In this photo I used a 2.5:1 aspect ratio PNG:
![2023-02-03 17_34_58-sfizz_5-sfizz](https://user-images.githubusercontent.com/2277898/216765977-9e0e1e55-3137-4a10-a085-64e1cf17b548.png)

**Comment by ldrolez** [comment]
Ok I see this image visibility is controlled here: https://github.com/sfztools/sfizz/blob/ae42f4a8822bb433f72912158e07d28331d0a447/plugins/editor/src/editor/Editor.cpp#L1901

**Comment by kmturley** [comment]
FYI image tag is not supported in sforzando:
<img width="777" alt="Screen_Shot_2021-12-05_at_9 56 15_PM" src="https://user-images.githubusercontent.com/1710493/218283136-fb25934b-e179-429c-81de-a4a05d4d194b.png">

If you use this tag then you will need separate .sfz files for sforzando vs sfizz :(

**Comment by kmturley** [comment]
Background image dimensions for sfizz are `790x285` as seen in code here:
https://github.com/sfztools/sfizz/blob/develop/plugins/editor/layout/main.fl#L10

For a 2x version you can use `1580x570`, but as mentioned file will error in Sforzando if you use the image tage

**Comment by kmturley** [comment]
If you import a Decent Sampler instrument, the background image is supported:
<img width="801" alt="Screenshot 2023-02-11 at 2 36 08 PM" src="https://user-images.githubusercontent.com/1710493/218283980-e14b3d40-28d8-441a-bca9-21849ca938ca.png">

Sometimes you have to switch tabs for the image to load properly (a known bug)

**Comment by redtide** [comment]
Hello! sorry for the long delay.

> I've played with the 'image' tag, which is working quite well but, I'd like to know
> 
>     * what is the recommended size/aspect ratio?
> 
>     * why is there a gray area on the left (see photo)?
> 
>     * would it be easy to have the same image in the 'knobs screen'?
> 

- The aspect ratio is the original, 1:1 adapted to fit in the image container
- in the kmturley posted link you see a `xywh {90 110 790 285}`; for convenience it was decided to use that 110 pixels offset
- I'll try something ASAP, although I think it would look ugly if the image don't span the full width

**Comment by kmturley** [comment]
My opinion:
- Removing the offset is a good idea, looks better to have a full width image
- Using the same image for Home and Controls looks cluttered

Instruments loaded into sforzando, use two separate images to avoid this issue.
<img width="775" alt="Screenshot 2023-03-30 at 4 59 36 PM" src="https://user-images.githubusercontent.com/1710493/228990562-921eb89c-f3bd-41db-8e8b-d77c128de5cc.png">
Image used: https://github.com/sfzinstruments/karoryfer.bear-sax/blob/master/GUI/bear_info_tab.png
775 x 335

<img width="776" alt="Screenshot 2023-03-30 at 4 59 43 PM" src="https://user-images.githubusercontent.com/1710493/228990580-aad88a1b-61b0-46fd-b728-1ea48329c5f7.png">
Image used: https://github.com/sfzinstruments/karoryfer.bear-sax/blob/master/GUI/bear_control_tab_1.png
773 x 333

I would size sfizz window to fit existing ARIA background images, as images are already created.
Otherwise you are asking every instrument maker to create separate image crops for sforzando vs sfizz

**Comment by alcomposer** [comment]
> Otherwise you are asking every instrument maker to create separate image crops for sforzando vs sfizz

No-one is forcing you or instrument makers to do anything. If you choose to make a sfizz compatible instrument, or choose to make a sforzando compatible instrument, that is your choice.

The layout choices for sfizz are suboptimal, and I would not think that currently this represents the best sfizz plugin has to offer.

Personally, I would like an interface that sample lib makers can easily adapt. However scope creep moves in very fast, and simple controls become full blown _ARIA-XML_ situations.

I would like at some point if we revisited a simpler, more **instrument** focused approach. Where the graphical tools were simply there to give a patch a bit of spice, as opposed to the main event.

**Comment by redtide** [comment]
> Instruments loaded into sforzando, use two separate images to avoid this issue

We don't have the UI system sforzando have, we can only set a single image when [image](https://sfzformat.com/opcodes/image) opcode is set in sfz, the video demo was just to propose a solution to the OP.

**Comment by redtide** [comment]
Let me know what do you think about this solution:
1. no bg image on controls page unless a "controls_background.imgext" (or better name) is found
2. replace the info panel with a semitransparent overlay (like the about dialog) over the home page
3. remove the "about sfizz" button in settings and replace it with the sfizz logo (as it was previously) being orange on mouse hover

**Comment by redtide** [comment]
The full-width image change is applied in develop, the image container size is now 800x300. If the image can't fit with a 1:1 aspect ratio, it will be rescaled (as previously) and now centered.

I'll try to make the other 2 changes (possibly together with #1132) before the next release, planned for the next weekend.

**Comment by redtide** [comment]
> Sometimes you have to switch tabs for the image to load properly (a known bug)

@kmturley is this on both lv2 and vst3 or vst3/au only? It happened to me 2 or 3 times only with VST. I see that vmeters doesn't work there. With LV2 when loading a sfz file it starts from the plugin contents directory instead from the user folder.

Anyway, this is what I got:

https://user-images.githubusercontent.com/1171962/231317175-683a9964-86ce-4a05-aa84-e02bc37643dd.mp4
