### ISSUE TITLE
[Question] Is sfizz still being developed

### ISSUE THREAD

**Issue by sound8** [sfztools/sfizz#1146]
I was just wondering is this project still being actively developed?
Noticed no releases since January 2022 and was just curious before making any posts.

Thank You

**Comment by Audiojunkie** [comment]
I’d be interested in knowing too. I have been unable to use sfizz since I run at HiDPI resolutions. The interface is simply too small. I even went so far as to contact Steinberg and confirm that a solution is currently possible with the existing libraries that are currently being used.  If I knew how to code, I’d do it myself, but programming is akin to a mystical dark art for me. I am left to hoping that someday someone will move the project forward enough that I can finally be able to use the program.

**Comment by redtide** [comment]
Since the beginning of this project (4 years now) there have always been pauses like this due to lack of manpower. AFAIK there is no intention of abandoning the project.

**Comment by reaper-sid** [comment]
I hate to say it, because I used to be a big SFZ supporter, but... The fact is, after DecentSampler came out, with the ability to create beautiful custom UIs, well... I haven't looked at SFZ in over a year. I had hope that sfizz would fix the shortcomings of the original SFZ player, but it seems DecentSampler has taken the wind out of their sails.

**Comment by falkTX** [comment]
so the critical part was custom UIs..?

**Comment by reaper-sid** [comment]
Never underestimate the power of beauty (if you look on PianoBook.com, you can see many inspiring DecentSampler instruments ). A few of us early PianoBook users tried (mostly in vain) to get people to make SFZs of their samples. It was pulling teeth. Then DecentSampler came out and bam, everybody was on board. 

It's nice (for the creators) to be able to create something beautiful or (for the users) to have a beautiful interface to work with. But also, It's nice to be able to tell at a glance what instrument you have loaded up. 

Technically speaking, SFZ is more powerful than DecentSampler, but that interface...

**Comment by falkTX** [comment]
that kinda says it all about the userbase though...

DecentSampler is not opensource, just with that it loses the interest of many people here, me included.

**Comment by reaper-sid** [comment]
Yes, the userbase is musicians, not programmers. SFZ was also not open source either until this project (I'm a user from the old cakewalk days). The DecentSampler spec is as open source as SFZ is. Musicians don't care as long as it works (otherwise how to account for the popularity of Darth Kontakt).

**Comment by Audiojunkie** [comment]
> so the critical part was custom UIs..?

For me, the critical part is being able to use it at all. I use a laptop with a HiDPI screen. These are only becoming more popular as time goes on, not less popular. The GUI is too small to use on Sfizz without being scaled up. I don’t need a “custom UI”, I just need a bigger UI.

**Comment by Audiojunkie** [comment]
> that kinda says it all about the userbase though...
> 
> DecentSampler is not opensource, just with that it loses the interest of many people here, me included.

I’m agreed with this. I don’t use Decent Sampler. I just need Sfizz to be bigger on the screen.

**Comment by reaper-sid** [comment]
If you use Reaper DAW, you can set each VST to HiDPI in the DAW whether or not the VST was coded for it. My understanding is that it works pretty well. I can't say I don't have a HiDPI screen.

**Comment by Audiojunkie** [comment]
> If you use Reaper DAW, you can set each VST to HiDPI in the DAW whether or not the VST was coded for it. My understanding is that it works pretty well. I can't say I don't have a HiDPI screen.

That works great on the Windows version of Reaper. That option doesn’t exist on the Linux version of Reaper. I use Linux.

**Comment by reaper-sid** [comment]
As I mentioned, The DecentSampler specification is open. If you can code, you can make your own open source project to read DecentSampler instruments right now.

**Comment by SpotlightKid** [comment]
> As I mentioned, The DecentSampler specification is open.

But the software is not, nor are most of the libraries offered for it (i.e. they have re-distribution restrictions). For some of us, that makes all the difference.

And why would one want to re-implement a player for it, when sfizz already exists and its authors have already done most of the hard work *and* made it FLOSS?

If you are missing features in sfizz, which DecentSampler has, like e.g. UI controls, if all fails, you can always fork and build upon it.

**Comment by reaper-sid** [comment]
"most of the libraries offered for it" Most of the SFZ libraries are the same way.
I've been using SFZ since SFZ was the name of the player (RGC:Audio SFZ) as well as the format. It wasn't open source, and the Sforzando player is also not open source. Only a small percentage of the libraries from then until now are open without re-distribution restrictions. It's nice that so many people have "reverse engineered" so to speak, the specification to create Open Source versions. However, since most musicians are not programmers Open Source means nothing to them. They wouldn't know what to do with the code if you gave it to them. They were happy to use SFZ before there were Open Source players, and they are happy to use other closed source software. DecentSampler with its open specification and low price (free) gives me what I need (he just added support for scala files and microtuning https://www.youtube.com/watch?v=dTeSv0SKlGc ). I used to have a copy of the Sfizz source code on my computer, but I would rather make music than software.

Anyhow... this discussion was about whether this project was ongoing. I regret having hijacked it. I'll see myself out.

P.S. With all the people showing up here these past few days, it does look like there is still some interest.

**Comment by sound8** [comment]
Well none of this really answers the question unfortunately, I guess I will have to assume this project is most likely not being developed any longer.  Since this post already kind of went off topic already I will ask you guys a question, knowing already it has no answer, but just thought I would share an observation.

My goal was to go completely Linux which for a few reasons did not work out for me at all.  One of the reasons that is "music production" related was an assumption about "players" such this one.
(Could have saved me a ton of time if I had just looked into this first)

SFZ & Soundfonts are really the only two instrument formats available to Linux users.  These two formats have also been around for quite a long time.  I prefer soundfonts but would use either at this point.

Three main features that I would be looking for are....
1.) ADSR Envelope
2.) Legato / Glide
3.) Ability to drag instrument files into GUI to open them

My question is, how is it possible that their is not a single SF2 or SFZ player available in Linux that has these features?
No Linux based developer in the past 20+ years ever desired a player with these relatively basic features?  Just seems strange to me personally, was not expecting this.

Anyone know of any?

-I have no desire to have to purchase a player for something like this in OS Linux based environment and with two OS instrument formats, would seem odd, so hold off on any recommendations for pay products in this situation.
-Please hold off on the suggestions of "just learn how to code and modify this yourself"
-Also have no desire to have to use a Wine based Windows wrapper to achieve this either

All projects like this seem to keep being abandoned.
As mentioned I know there is no answer to this.
I know that most Linux just don't care about these features, but it is kind of strange that there has not been a single coder that ever had the desire for something like this in over 20 years?

**Comment by reaper-sid** [comment]
DecentSampler has a free linux version https://www.decentsamples.com/product/decent-sampler-plugin/
It has ADSR.
It has a legato tutorial.
It has a drag and drop preset editor (drag wav files).
It has drag and drop of instrument file (.dspreset file) to open the full preset.
It can read/convert relatively simple SFZ files.
I use the Windows version I have not tried the Linux version..

**Comment by SpotlightKid** [comment]
@sound8 It's always difficult to answer to such long posts, which bring up so many points, so I'll restrict myself to pointing out some wrong assumptions you have:

> SFZ & Soundfonts are really the only two instrument formats available to Linux users. 

No, they're not. LinuxSampler existed for a *long* time and supported Gigasampler libraries. Also, sample libraries aren't the only form of "instruments". There are many good software synths for Linux.

> Three main features that I would be looking for are....
> 1.) ADSR Envelope

SFZ and sfizz supports those. And you can define MIDI controllers for all stages.

> 2.) Legato / Glide

SFZ and sfizz supports those. BTW, "Legato" in the context of sample libraries usually means something entirely different than Glide or Portamento. 

Anyway, SFZ / sfizz support both Portamento (sort of) and triggering different samples when playing legato.

> 3.) Ability to drag instrument files into GUI to open them

That is entirely dependent on the plugin format and host used. But is having to click on a 
button and choosing a file in a file selector dialog really a show-stopper?

> My question is, how is it possible that their is not a single SF2 or SFZ player available in Linux that has these features?

Besides 3., which IMHO is not really relevant, they do exist.

**Comment by atsushieno** [comment]
Those closed source projects like DecentSampler are no-go for other platforms like [Android](https://github.com/atsushieno/aap-lv2-sfizz) or [Web](https://github.com/sfztools/sfizz-webaudio). SFZ is the most advanced solution there, and sfizz is the most advanced project that supports it.

**Comment by atsushieno** [comment]
The question already received a valid answer https://github.com/sfztools/sfizz/issues/1146#issuecomment-1475159860 . If the questioner does not respect that then I don't see any point to try to give more words.

**Comment by sound8** [comment]
Thank you guys for the responses.
Probably not going to be of much value but will just try to respond to each post as much as I can

-Not a matter of "respecting" the 1146 comment, just was not a definitive answer.
I am still left with the same information I had before the question.
The project has not had a release in over a year, it may just be a pause in development or it may no longer be being developed.

-DescentSampler
Seen it around but, never tried requires signup, overlooked because have not seen any screenshots of a global generic interface that offers ADSR / Legato.
Not sure, seems like they are available only if you create a GUI (Sforzando type of approach)  Uses its own format not really desired personally.

-Long post I made was to try and avoid the "I'll prove you wrong" post but... :)
-Keep in mind the point was stating NOT stating that SFZ / SF2 does not have these features, it is finding a plugin that has these parameters available globally in their actual GUI.
Example, Fluidsynth has tons of features available for SF2 yet no one ever adds them to their plugin GUI, just chorus & reverb.
-Was refering to "instruments" as sample based instrument formats such as SF2 / SFZ
-Was aware of Linux Sampler / Gig(a) did not mention to eliminate longer post / confusion but does not seem to be being developed either and have never seen a screenshot of an GUI that contains ADSR / Legato
-D&D never said anyone had to agree with "my" preferences, if you like navigating through tiny file pickers to open up each instrument that is ok, Sfizz offers d&d so it is a desired feature by some.  Agree, not a deal breaker but nice to have the option.  I have seen plugins with even better options of file selection but don't think developer would want to add them.

Anyways thanks again for all the responses, not really the point of Github, but if anyone has any other suggestions about my post please share.

**Comment by reaper-sid** [comment]
> -DescentSampler Seen it around but, never tried requires signup, overlooked because have not seen any screenshots of a global generic interface that offers ADSR / Legato. Not sure, seems like they are available only if you create a GUI (Sforzando type of approach) Uses its own format not really desired personally.
> 

DecentSampler is not following the Sforzando approach, in that Sforzando charges companies to allow them to have a custom UI.
With DecentSampler, the Custom UI is part of the spec. Still all free. When you make a sample instrument, you make the UI. There is no global generic interface. Also if you find a sample instrument you like and it does not have ADSR, you can just stick the ADSR code into it. Like SFZ, the Instrument is just a text file (XML file) and a bunch of samples.
Here are some screenshots of free DecentSampler instruments with ADSR:
https://www.pianobook.co.uk/packs/the-viking-log-lyre/
https://www.pianobook.co.uk/packs/babblings/
https://www.pianobook.co.uk/packs/roast-bananas-street-vendor/
https://www.pianobook.co.uk/packs/decent-oboe/
https://www.pianobook.co.uk/packs/pneumatic-harmonics/

You get the picture. But honestly, you seem to be looking for reasons NOT to try it.

**Comment by falkTX** [comment]
speaking of pictures, nothing stop us from defining a tag to use in sfz files to set which picture to show on screen when an instrument is loaded.
we mostly just need to define the rules around it

**Comment by reaper-sid** [comment]
> speaking of pictures, nothing stop us from defining a tag to use in sfz files to set which picture to show on screen when an instrument is loaded. we mostly just need to define the rules around it.

Actually there is an image Opcode. Sfizz supports it. https://sfzformat.com/opcodes/image

**Comment by sound8** [comment]
@reaper-sid
Do you work for this company or something?
What is going on here?
First off, I meant similar to Sforzando approach in the sense that you create GUIs for each instrument.
Yes you are right I am looking for reasons to NOT try it, you want to know why?.....
The whole point is I am looking for a plugin that uses SF2 or SFZ formats with the features I mentioned available globally in its interface.

**Comment by reaper-sid** [comment]
> First off, I meant similar to Sforzando approach in the sense that you create GUIs for each instrument.
>
Actually, the Sforzando approach is that basically you Can't create a GUI at all unless you pay them. That is the reason that after more than a decade of using/promoting SFZ I finally gave up on the format. I had hopes for Sfizz, but as you can see, development is sporadic at best.

> The whole point is I am looking for a plugin that uses SF2 or SFZ formats with the features I mentioned available globally in its interface.
>
I wish you the best of luck in your search. 
But actually, I'm curious about something... can you explain the need for "available globally in its interface" I have never seen a sampler that had that (the features offered are usual defined as part of the sample instrument you are using). So I am curious. Also do you make or edit your own sample instruments, or do just use what is on offer from others (not that there's anything wrong with that)?
I guess I talk up DecentSampler so much is because it is exactly the sampler I would have written (except the flaw of not being open source). I can make my own full featured beautiful looking and sounding instruments for my own use. I can edit an instrument from others and add the features I want. It is what I hoped SFZ would become.

**Comment by redtide** [comment]
> Actually there is an image Opcode. Sfizz supports it.

There was an idea to implement something similar to ARIA XML UI in sfizz but it's not that trivial, so at some point, me and JPC, [added](https://github.com/sfztools/sfizz/pull/769) that opcode, which appears in the Simon Cann book (sfz v2?) and then documented on sfzformat website based on our tests with Cakewalk products. though only DropZone supports it and with a very limited image size.

**Comment by kmturley** [comment]
I tried using the control image opcode, which works in `sfizz` but not `sforzando`:
<img width="777" alt="Screen_Shot_2021-12-05_at_9 56 15_PM" src="https://user-images.githubusercontent.com/1710493/227646190-ce924e3c-7212-4a4a-8f9e-d742081dd6dc.png">

Either:
- Players have to ignore opcodes they don't understand
- Need to create separate .sfz files for each player (with only the supported opcodes)
- separate new functionality in a different format from .sfz

As ARIA xml is already a defined format and a separate file, it makes more sense to add support for ARIA UI in sfizz. (minus checking license keys...). I am prototyping an sfz web player. It was simple to parse ARIA xml and create a display using html, css and js. https://github.com/kmturley/sfz-web-player Hooking up the controls to actual audio inputs/outputs will be a little more complex.

**Comment by AlexMitchellMus** [comment]
Sforzando already _does_ skip unknown opcodes AFAIK.

Image opcode was part of original SFZ spec. However SFZ players are able to support any part of the spec they choose.

**Comment by SpotlightKid** [comment]
I think it would be better to continue the discussion about adding features to sfizz in a separate issue.

**Comment by redtide** [comment]
and it should also be a good thing to close it, as I can't say much but I'm sure there are goals planned, not to abandon it, and even if that happened it wouldn't be something pre-arranged.
