### ISSUE TITLE
Set $ definitions by API

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#119]
Provide API that can set $-variables prior to entering the parser.

This can be useful in some scenarios:
- to define some cc numbers by the custom library user of sfizz (eg. `_oncc$MY_KNOB_ID`)
- to set the sample path variable externally. there are some ARIA sfz bundles that want such things
for instance, see https://github.com/sfzinstruments/karoryfer.shinyguitar/blob/026d25a62135aeb1900d0720ae3f87aa80f107f2/Shinyguitar.bank.xml#L5

**Comment by paulfd** [comment]
Overall maybe we should revisit the parser and the bindings between the synth and parser, cf your discussions of 20-13-03 evening on using sfizz programmatically. In essence the synth acts on a set of regions and some "global" information like root directories for samples. There's nothing that limits this to sfz files. However this will require some addition and overhaul in the API. The user-facing API of the library will need to be densified and we should describe how we would like to do this so it's stable enough.

**Comment by paulfd** [comment]
With the new parser code in #130 this is now possible, I'll close this, thanks for the PR !

**Comment by jpcima** [comment]
>With the new parser code in #130 this is now possible, 

Not yet from sfizz API, is it ?

**Comment by paulfd** [comment]
Okay, I thought this support was mostly intended to be internal to e.g. support reading ARIA's banks, and not necessarily accessible from the API. Sorry for the overeager closing!
