### ISSUE TITLE
Crash if a midi note is recieved while the SFZ file is reloaded

### ISSUE THREAD

**Issue by Sylv1o** [sfztools/sfizz#1203]
Hi, I use SFIZZ in Synthedit, so unsure it also happen in SFIZZ VST or Standalone.

Here is the [message](https://groups.io/g/synthedit/topic/sfz_player_bug/102339243?p=,,,100,0,0,0::recentpostdate/sticky,,,100,2,0,102339243,previd%3D1698923105138952783,nextid%3D1692678357979048267&previd=1698923105138952783&nextid=1692678357979048267) I posted in the Synthedit group : 

> I worked a lot on my percussion sampler, things are very promising but...now that my project has became bigger (especially the SFZ files), I noticed a very problematique bug :
>
> If the SFZ player module recieve a midi note while it is reloading the SFZ file, SE crash, same in exported plugin.
>
> Basically in my big project, I need to wait one or two seconds after a change before playing a new note, or SE crashes.
If the SFZ file is very small, It's harder to make it crash but I've been able to do it by playing many notes while adjusting some parameters.
So of course, the bigger the file, the longer the wait...

**Comment by Sylv1o** [comment]
Here's the link to the original post on the Synthedit Yahoo group

[https://groups.io/g/synthedit/topic/sfz_player_bug/102339243?p=,,,100,0,0,0::recentpostdate/sticky,,,100,2,0,102339243,previd%3D1698923105138952783,nextid%3D1692678357979048267&previd=1698923105138952783&nextid=1692678357979048267](url)

**Comment by Sylv1o** [comment]
It's now fixed in Synthedit. 
I was able to reproduce the bug in the SFIZZ VST3.

**Comment by essej** [comment]
Ummm, did they make a fix in the libsfizz code or in how they used it? Sounds like we need a PR from them...

**Comment by redtide** [comment]
heh, I was about to ask it: what do you mean, that it was a bug in SE or still a bug in sfizz but fixed only there?

**Comment by Sylv1o** [comment]
I asked Jeff (Synthedit creator) to send the fix here

**Comment by Sylv1o** [comment]
He has just filter incoming midi notes while files are reloading

**Comment by Sylv1o** [comment]
[Here](https://dev.azure.com/synthedit/_git/CommunityModules?path=/JeffMcClintock/SamplePlayer3/SamplePlayerSfz.cpp&_a=compare) the link to the changes (line 166)

**Comment by paulfd** [comment]
> I was able to reproduce the bug in the SFIZZ VST3.

Just playing midi notes data while reloading made the plugin crash? There should be a process lock so that'd be a bug.

I could see to make the doc clearer but:
```c++
    /**
     * @brief Send a note on event to the synth.
     ...
     * @par Thread-safety constraints
     * - @b RT: the function must be invoked from the Real-time thread
     */
    void noteOn(int delay, int noteNumber, int velocity) noexcept;
```
and
```c++
    /**
     * @brief Empties the current regions and load a new SFZ file into the synth.
     ...
     * @par Thread-safety constraints
     * - @b CT: the function must be invoked from the Control thread
     * - @b OFF: the function cannot be invoked while a thread is calling @b RT functions
     */
    bool loadSfzFile(const std::string& path);
```
I guess a different wording could be that no `@b RT` functions must be called while the `loadSfzFile` function has not returned.

We removed locking within the library on purpose because it's usually much cleaner to do it at the "plugin interface" level where you can possibly leverage abilities offered by hosts.

**Comment by Sylv1o** [comment]
The solution implemented by Jeff in Synthedit seems perfect, I can't see anything wrong with it. One just want the midi to be filtered while the instrument is reloading...

**Comment by paulfd** [comment]
The same mechanism is implemented in the VST plug-in, but you mentioned in a previous comment you managed to make it crash. I was curious to know more about the context in how you made it crash (I.e. which daw, sfz instrument, ...). If you remember :)

**Comment by Sylv1o** [comment]
It seems the mechanism you mention don't work. I've just tested again in Cubase 12 with SFIZZ vst3, I load an instrument, and play some midi notes while the instrument is loading : no problem.
Then I open the SFZ file in a text editor, make a useless change (just add a line), then I save the file and immediatly play some midi notes : Cubase crash.

**Comment by Sylv1o** [comment]
I can make it carsh with any SFZ file, but if the file is very small, it take too little time to load to make Cubase crash. Try with any big SFZ file, it should crash easily.

**Comment by essej** [comment]
Double check the version of the sfizz plugin you have installed, this sounds like a bug that was fixed last year.

**Comment by Sylv1o** [comment]
I'll check but I use sfizz for less than a year...

**Comment by Sylv1o** [comment]
1.2.1

**Comment by essej** [comment]
You need 1.2.2! :)

**Comment by Sylv1o** [comment]
Indeed not the last one, 
I'll check with 1.2.2

**Comment by Sylv1o** [comment]
I'm so sorry, indeed bug is fixed in 1.2.2

I don't even know why I had this old version...

My mistake, the fact that this bug was still there in the Synthedit version had made me wrong...

Appologies again.

**Comment by redtide** [comment]
No worries :) So can close this?

**Comment by Sylv1o** [comment]
I think so yes
