### ISSUE TITLE
bug when off_by is involved and the two midi notes are played exactly at the same time

### ISSUE THREAD

**Issue by Sylv1o** [sfztools/sfizz#1219]
The snippet below won't trigger the first region if note 69 and 81 are played at the same time.
If there's only one sample delay between them (tested at sample rate= 44100), the first region play and is muted in one second by the second region.

In Sforzando, no problem, even when the two notes are played at the same time, the first region is played and muted by the second.

```ini
<region>
key=69
off_by=2
off_mode=normal
tune=-3200
ampeg_release=1
sample=CymbalTest-004.wav

<region>
key=81
group=2
sample=CymbalChokeTest-005.wav
```

Tested with this midi sequence : 

![image](https://github.com/sfztools/sfizz/assets/96621124/dd83245b-14aa-44e5-89af-060eeefd7068)

**Comment by Sylv1o** [comment]
Thanks  !

**Comment by Sylv1o** [comment]
Hi Paul, did you actually test the fix ? I've just tested SFIZZ VST3 version 1.23 and it still don't work...

**Comment by paulfd** [comment]
Hi,

I test something: https://github.com/sfztools/sfizz/blob/3d7bcb49681bf47fbaa34c2bb27bfdf117c63b4e/tests/PolyphonyT.cpp#L617

Your problem might be more complex than what I test then, if so I'll reopen.

**Comment by Sylv1o** [comment]
The following snippet should play the two sample and mute the first one after one second. But only the second sample is played. This is the test that should be done IMHO.

```
<global> loop_mode=one_shot pitch_keytrack=0 

<region>
key=60
off_by=2
off_mode=normal
ampeg_release=1
sample=CymbalTest-004.wav

<region>
key=60
group=2
sample=CymbalChokeTest-005.wav

```
