### ISSUE TITLE
Transpose vs tune

### ISSUE THREAD

**Issue by redtide** [sfztools/sfizz#1220]
### Discussed in https://github.com/sfztools/sfizz/discussions/1159

<div type='discussions-op-text'>

<sup>Originally posted by **afstudios** May  7, 2023</sup>
At the moment it is not possible to use the transpose correctly, as it works as tune actually.
It would be great if the transpose or note shift from V2 could be integrated so the notes could be shifted and tuned in the same time 
Also octave transpose / note shift from V2 does not work.
The opcodes that does not work:

note_offset
octave_offset

Any chance of implementing this?</div>

**Comment by paulfd** [comment]
Could you provide minimal SFZ files and steps to reproduce the behavior you mention and that other more compliant players might do differently? At the moment I see offsets and transpose and tune working as I expect, but maybe I'm mistaken.

**Comment by KKQ-KKQ** [comment]
`note_offset` works with sample files. but not with generators e.g. `*saw`.
This behavior is same as that of sforzando.

**Comment by redtide** [comment]
@afstudios

**Comment by redtide** [comment]
Closing, reopen if any problem.
