### ISSUE TITLE
RAM usage : Samples are continuously loaded in RAM while playing

### ISSUE THREAD

**Issue by Sylv1o** [sfztools/sfizz#1222]
In RAM mode (<control> hint_ram_based=1) the samples are loaded in RAM (normal) but when a key is pressed, the played samples are loaded again in RAM...

This RAM loading while playing consum more CPU than it should causing audio clicks when buffer is low.

In Sforzando : RAM usage is the default mode (and only mode). Samples are not reloaded in RAM while playing. CPU is lower in Sforzando than in Sfizz.

**Comment by Sylv1o** [comment]
Thanks, I'll ask Jeff to implement this fix for the Synthedit version of SFIZZ.

Cheers

**Comment by paulfd** [comment]
We're going to release in a week or so. If he updates he'll get the fix !
