### ISSUE TITLE
Tests fails with the latest Abseil

### ISSUE THREAD

**Issue by KKQ-KKQ** [sfztools/sfizz#1240]
The following tests FAILED with the newer Abseil-cpp:
	457 - [Modulations] LFO v1 CC connections (Subprocess aborted)
	459 - [Modulations] LFO v1 aftertouch connections (Subprocess aborted)
	461 - [Modulations] LFO v1 poly aftertouch connections (Subprocess aborted)
	463 - [Modulations] EG v1 CC connections (Subprocess aborted)

It is no problem with Abseil-cpp 20230802.1.
20240116.0 fails.

on MacOS Ventura 13.6.3
Xcode 15.2

```
#bin/bash
pushd external/abseil-cpp
ABSEILHASH=$(git show --format='%h' --no-patch)
COMMIT=$(git log --oneline --decorate=full | head -1)
popd
#BT=Debug
#BT=Release
BT=RelWithDebInfo
OUTTXT="../results_${BT}_${ABSEILHASH}.txt"
echo "${COMMIT}" > "${OUTTXT}"
rm -r build
cmake -B build -S . -D SFIZZ_ASAN=ON -D CMAKE_BUILD_TYPE=${BT} -D SIZZ_SHARED=ON -D SFIZZ_TESTS=ON -D SFIZZ_GIT_SUBMODULE_CHECK=OFF &&\
cmake --build build --parallel 4 --target sfizz_tests --config ${BT} &&\
ctest --output-on-failure --test-dir build --build-config ${BT} | tee -a "${OUTTXT}"
```

[https://gist.github.com/KKQ-KKQ/3f534864b769a32c675e9a191ecf8ac4](https://gist.github.com/KKQ-KKQ/3f534864b769a32c675e9a191ecf8ac4)

**Comment by KKQ-KKQ** [comment]
20230802.rc2 also works.

**Comment by redtide** [comment]
> 20230802.rc2 also works.

which is older than 20230802.1, that seems to be the only one we can use before the 2024 series.
Let's see what @paulfd think.

**Comment by KKQ-KKQ** [comment]
It might be related to Address sanitizer. The tests succeeds when I set SFIZZ_ASAN to OFF.
Abseil might keep invalid address on hash maps.

**Comment by redtide** [comment]
I had that suspect few hours ago, anyways, let's see. Meanwhile, would you like to join our [Discord](https://discord.gg/3ArE9Mw) or [Matrix](https://matrix.to/#/#sfztools:matrix.org) chat?

**Comment by KKQ-KKQ** [comment]
The tests on ubuntu 22.04 with the following script are failed.
I think the auto tests with new tags fail with the Abseil version.
They also fail when ubuntu's abseil version becomes newer.

```
#/bin/bash
BT=Debug
#BT=RelWithDebInfo
TESTDIR=build_asan
cmake -G Ninja -B ${TESTDIR} -S . -D CMAKE_BUILD_TYPE=${BT} -D SFIZZ_TESTS=ON -D SFIZZ_ASAN=ON -D SFIZZ_USE_SYSTEM_ABSEIL=OFF && \
cmake --build ${TESTDIR} --config ${BT} --parallel 2 --target sfizz_tests && \
ctest --build-config ${BT} --parallel 1 --output-on-failure --stop-on-failure --test-dir ${TESTDIR}
```

**Comment by paulfd** [comment]
Thanks again for the report. It looks like to me that moving the hash map invalidates references, which tends to be validated by [this comment](https://github.com/abseil/abseil-cpp/commit/1a03fb9dd1c533e42b6d7d1ebea85b448a07e793). Since the target vector is grown incrementally during loading, and the hashmap is in the vector, it might get moved if the vector reallocates for more space.

I'll continue investigating.

**Comment by paulfd** [comment]
The changelog entry was:

* Abseil's [hash tables](https://abseil.io/docs/cpp/guides/container) now detect many more programming errors in debug and sanitizer builds.

It's actually our bug, not abseil's. I have a potential fix in https://github.com/sfztools/sfizz/pull/1242, lmk if it helps!
