### ISSUE TITLE
Waveform Generators don't work with tune opcode

### ISSUE THREAD

**Issue by AlexMitchellMus** [sfztools/sfizz#125]
## ISSUE
Generators are intended to be functional with `tune` opcode:

## SFZ Example
```
<region> sample=*saw tune=1200
<region> sample=*saw tune=0
```
## Current Behaviour

Both regions generate the **saw** waveform (or any other generator) at the same pitch.
This issue does not occur with audio sample playback.

**Comment by paulfd** [comment]
Thanks, I'll check it out.

**Comment by jpcima** [comment]
The first reason of this non-working, it's that tune is limited to range ±100 cents (SFZv1)
When this limitation is lifted, the example above can work.

You can take into account the pitch keycenter instead of base freq and the wavetable will be tuned as expected.
```
float frequency = pitchRatio *
     (440.0 * std::pow(2.0, (region->pitchKeycenter - 69.0) / 12.0));
```

**Comment by AlexMitchellMus** [comment]
@jpcima Ah, you are right.

However currently `tune` & `pitch` are aliases for each other, but:

tune = +- 100  cents
pitch= +- 2400 cents (or larger)

Alternatively both could be unbounded? (in Sfizz)

It also doesn't explain why it is working with sample's vs generators?

**Comment by jpcima** [comment]
It's not supposed to be working with samples either since it's handled the exact same.
