### ISSUE TITLE
All voices are always active after sustain is released

### ISSUE THREAD

**Issue by iv-m** [sfztools/sfizz#1257]
Here are the steps to reproduce the issue:
- load some SFZ file, e.g. SalamanderGrandPianoRetuned-V3+20200602.sfz downloaded from https://freepats.zenvoid.org/Piano/acoustic-grand-piano.html
- press down the sustain pedal
- hit some keys so that most of the voices are active
- release the pedal

With sfizz_jack build from v1.2.2 (plus fix for  #1180), the number of active voices quickly goes down to 0 -- in, like, 2 seconds.

With sfizz_jack build from v1.2.3, all the voices become active, and stay active for at least for few minutes.  Same for current `develop` branch (85a275223a).

I can also reproduce it with LV2 plugin in Ardour 8.4, where midi panic correctly resets the states and brings things back to normal.

This is especially noticeable when the max. number of voices is set to some larger value, as CPU usage increases when sustain is released and never goes back to normal.

**Comment by KKQ-KKQ** [comment]
Didn't #1252 fix the issue? The PR has been merged recently.
Did you try the LATEST develop branch?

**Comment by iv-m** [comment]
Well, in fact I did mess up things a bit in my repo. The latest develop branch (342cd99dd9eec2cab8f750db23f32f77492177df), indeed, works for me. Sorry for the noise.

So, this is known issue in 1.2.3 release.
