### ISSUE TITLE
error: no member named 'StrCat' in namespace 'absl'

### ISSUE THREAD

**Issue by yurivict** [sfztools/sfizz#1262]
Build fails:
```
/usr/ports/audio/sfizz/work/sfizz-1.2.3/src/sfizz/Synth.cpp:430:28: error: no member named 'StrCat' in namespace 'absl'
  430 |             image_ = absl::StrCat(defaultPath_, absl::StrReplaceAll(trim(member.value), { { "\\", "/" } }));
      |                      ~~~~~~^
/usr/ports/audio/sfizz/work/sfizz-1.2.3/src/sfizz/Synth.cpp:433:37: error: no member named 'StrCat' in namespace 'absl'
  433 |             image_controls_ = absl::StrCat(defaultPath_, absl::StrReplaceAll(trim(member.value), { { "\\", "/" } }));
      |                               ~~~~~~^
2 errors generated.
```

Version: 1.2.3
abseil-20230125.3
clang-18
FreeBSD 14.0

**Comment by redtide** [comment]
AFAICS `absl::StrCat()` is still part of the `absl::strings` library and the build should succeed; we also test via CI for release builds, so I have no idea what's going on there.

**Comment by yurivict** [comment]
What version of abseil do you test with?

**Comment by redtide** [comment]
personally both the one I have in Arch ATM and the bundled one, I can make a build for testing the one you mentioned but is it possible a missing `#include <absl/strings/str_cat.h>` could be the reason?

**Comment by yurivict** [comment]
Yes, adding the include fixes it.
It needs to be added in all .cpp files that uses this function.

**Comment by redtide** [comment]
OK, do you mind to send a PR? Or I'll fix it later this night

**Comment by yurivict** [comment]
Please fix it.

**Comment by redtide** [comment]
OK, but I see only Synth.cpp missing it.

**Comment by redtide** [comment]
Looks like my checkout was older than current develop, where it seems it's [already fixed](https://github.com/sfztools/sfizz/blob/develop/src/sfizz/Synth.cpp#L37).
So I guess if it's about to create a release from the 1.2.3 tarball, you should add a patch.

**Comment by yurivict** [comment]
No, there is also src/sfizz/effects/Lofi.cpp

**Comment by redtide** [comment]
> No, there is also src/sfizz/effects/Lofi.cpp

I don't see any StrCat in that file. Have you an updated develop checkout?

**Comment by yurivict** [comment]
The current master branch doesn't have this problem.
