### ISSUE TITLE
[question] Is LV2 support present?

### ISSUE THREAD

**Issue by yurivict** [sfztools/sfizz#1263]
The README file says that sfizz can be used as an LV2 plugin.
There used to be the cmake variable ```SFIZZ_LV2``` but it isn't present now.
CHANGELOG.md doesn't mention LV2 removal.
LV2 plugin isn't installed by 'make install'.

Is LV2 support present in sfizz?

**Comment by redtide** [comment]
It's explained [here](https://github.com/sfztools/sfizz?tab=readme-ov-file#repository-reorganization)

**Comment by yurivict** [comment]
Ok, thank you.
