### ISSUE TITLE
The DEBs for Ubuntu 24 LTS are missing from the OBS

### ISSUE THREAD

**Issue by rolodoom** [sfztools/sfizz#1279]
The Sfizz Ubuntu DEBSs on the OpenSuse Build Service need to be compiled for Ubuntu 24 LTS latest version.

https://software.opensuse.org/download.html?project=home%3Asfztools%3Asfizz&package=sfizz

Thanks.

**Comment by paulfd** [comment]
I added the repository, they should appear now.
