### ISSUE TITLE
Segfault on Raspberry Pi 5, no debug symbols

### ISSUE THREAD

**Issue by GeoffreyPlitt** [sfztools/sfizz#1282]
I'm getting a segfault when running sfizz_jack on my Pi 5 (Raspian 12 Lite 64-bit). It errs even when just doing `--helpfull`, and there are no debug symbols, so I can't get a stacktrace.

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 6.6.31+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux
pi@raspberrypi:~ $ sfizz_jack --helpfull
Segmentation fault

I know the device's sound card and drivers are working fine because both aplay /usr/share/sounds/alsa/Front_Center.wav and mpv --ao=jack /usr/share/sounds/alsa/Front_Center.wav result in playing a sound I can hear.

I installed sfizz with the standard steps, copied from the Raspian section of the official install page:
echo 'deb http://download.opensuse.org/repositories/home:/sfztools:/sfizz/Raspbian_12/ /' | sudo tee /etc/apt/sources.list.d/home:sfztools:sfizz.list
curl -fsSL https://download.opensuse.org/repositories/home:sfztools:sfizz/Raspbian_12/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_sfztools_sfizz.gpg > /dev/null
sudo apt-get update
sudo apt-get install -y sfizz.

I wanted to get a backtrace gdb says No debugging symbols found in sfizz_jack, so I can't debug the segfault. How do I get debugging symbols?

**Comment by paulfd** [comment]
I really never tried but some debug symbols seem to be on the OBS repo? https://download.opensuse.org/repositories/home:/sfztools:/sfizz/Raspbian_12/armhf/

**Comment by GeoffreyPlitt** [comment]
Gotcha! I ended up compiling source and got around this. Closing.
