### ISSUE TITLE
ampeg_release phase entry inconsistent

### ISSUE THREAD

**Issue by AlexMitchellMus** [sfztools/sfizz#129]
When playing in Ardour with the Virtual Keyboard release is not entered, until after the note has been held down for the ampeg_attack time value.

```
<region>
sample=*saw
ampeg_attack=1
ampeg_release=1
```

Recorded MIDI passages can also exhibit this behaviour- but not on every note- only on a few random notes:
![adsr](https://user-images.githubusercontent.com/12004932/76820728-df8b9180-685b-11ea-95c4-1f4691c5cd76.png)

**Comment by paulfd** [comment]
Is this develop?

**Comment by AlexMitchellMus** [comment]
Yes 474f221f

**Comment by paulfd** [comment]
- Is it random or not? If it appears with this midi file can you share it? 
- Can you try master?

**Comment by AlexMitchellMus** [comment]
[MIDI 2-1.zip](https://github.com/sfztools/sfizz/files/4342085/MIDI.2-1.zip)

It isn't random when playing live. It always fails.

Strangely when I render out the audio- it **does** fail at exactly the same note! :thinking:

**Comment by paulfd** [comment]
It's better. Random stuff are more annoying

**Comment by AlexMitchellMus** [comment]
Checked with current Master, (had to use *sine) but exactly the same:

![Screenshot from 2020-03-17 18-19-36](https://user-images.githubusercontent.com/12004932/76833875-0c4fa100-687c-11ea-9d9f-721f9fb684be.png)

**Comment by paulfd** [comment]
Ok thanks I'll check it out

**Comment by jpcima** [comment]
It's the `getBlock` version of ADSR that's failing.
The sample-by-sample has correct result.

**Comment by jpcima** [comment]
Below a comparison of 3 ADSR - in this order: Cakewalk, sfizz, ARIA

You can observe sfizz to have bad decay.
Cakewalk releases faster that the 2 others.

![Capture_du_2020-03-18_17-52-44](https://user-images.githubusercontent.com/17614485/76986490-03290780-6942-11ea-9df5-d5dfdf668a39.png)

**Comment by jpcima** [comment]
I guess that decay value (seconds) represents the time it would take an exponential segment from top point to 0.

In the Cakewalk trace, the decay looks like a truncated exponential segment that stopped running as it reached the sustain point.

**Comment by AlexMitchellMus** [comment]
I can confirm that #136 fixes this issue completely from initial testing.

Thank you @jpcima you are a superstar. 
Not too bad either @paulfd ;-)

**Comment by paulfd** [comment]
@alcomposer can you check if this is still the case with the last commits/rebasing? Thanks.

Btw I'm not competing, cause I'll loose :)

**Comment by paulfd** [comment]
#136 is merged ! Thanks for the report as always 🙂
