### ISSUE TITLE
Build Doxygen API docs only on tagged releases

### ISSUE THREAD

**Issue by redtide** [sfztools/sfizz#13]
Currently the API documentation is built at each commit in develop branch which is not correct, the correct behavior should be to build the API at each release and eventually separate the documentation per versions.
Need to evaluate eventually also if to remove the build date from pages footer template.

**Comment by paulfd** [comment]
Yeah maybe the rate is a bit high for documentation refreshes :)

**Comment by redtide** [comment]
indeed, I used that way for testing but now I need to change it, so I added this issue as reminder for myself :-P
