### ISSUE TITLE
Pan is non-working with stereo sources

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#133]
When using a mono source, either mono sound file or generator, `pan` works as expected.
When it's a stereo sound, `pan` does absolutely nothing.

[mono.wav.gz](https://github.com/sfztools/sfizz/files/4351208/mono.wav.gz)
[stereo.wav.gz](https://github.com/sfztools/sfizz/files/4351209/stereo.wav.gz)

Example
```
<region>
sample=stereo.wav
pitch_keycenter=69
pan=50
```

**Comment by jpcima** [comment]
There is a fix at b551716.
It's not exact in comparisons, probably because other software probably use different pan laws. (see xfin/xfout curve formulas)

**Comment by paulfd** [comment]
This should be fixed, thanks for the report and the correction ! 🙂
