### ISSUE TITLE
Make hardcoded dependencies soft.

### ISSUE THREAD

**Issue by spongeboburu** [sfztools/sfizz#134]
In the list of dependencies the following libraries are not mentioned:
-lFLAC, -logg, -lvorbis and -lvorbisenc.

If they are mandatory they should be added to the docs. However, it would probably be better to have those codecs as options in cmake.

**Comment by jpcima** [comment]
Hello,

>In the list of dependencies the following libraries are not mentioned:

Yes, and it's correct; these formats are accessed through libsndfile, but sfizz does not make any direct use of this list of libraries.

The case when you need to link these libraries explicitly, it's to build with static linking.
If this is necessary, it's suggested to enable option `-DSFIZZ_STATIC_LIBSNDFILE=ON` in cmake.

**Comment by spongeboburu** [comment]
Ah, from the libsndfile docs "From version 1.0.18, libsndfile also reads and writes FLAC and Ogg/Vorbis".

But if that is included in libsndfile already, why try to link against FLAC, ogg, vorbis and vorbisenc?

**Comment by paulfd** [comment]
I think that libsndfile dtnamically links the flac and ogg vorbis libraries, they are not baked in. Unless you ask for `pkg-config --static` there should only be libsndfile

**Comment by paulfd** [comment]
Hi! Did  you have time to check this out more? On my side I have this after `make install`

```
~/source/sfizz/build develop*
❯ pkg-config --libs sfizz
-L/usr/local/lib -lsfizz

~/source/sfizz/build develop*
❯ pkg-config --libs --static sfizz
-L/usr/local/lib -lsfizz -lsndfile -lFLAC -logg -lvorbis -lvorbisenc
```

**Comment by paulfd** [comment]
I'll let you reopen this if this is still an issue. Thanks for reporting!
