### ISSUE TITLE
VST picture not displayed on debian buster

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#135]
The picture does not show, with VST3 in Reaper host.
(reported by @sub26nico on #librazik IRC)

It's the package `sfizz_0.3.1-0librazik1_amd64.deb`.
https://download.tuxfamily.org/librazik/pasapas/pool/main/s/sfizz/

A screenshot to illustrate the problem
![1584829944](https://user-images.githubusercontent.com/17614485/77237551-958f0c80-6bc9-11ea-863e-f43f15055e64.png)

**Comment by jpcima** [comment]
This bug is reproduced in a Buster VM when using the binary package above (1), however NOT when building sfizz from the source (2).

If I extract all strace logs of Reaper that mention `sfizz.vst3`
- in (1) the background file `logo.png` is never accessed, despite that it's present in the package and  correct
- in (2) the background file `logo.png` is logged, and shows in UI

---

In VSTGUI, the file is supposed to be looked up according to the bundle directory.
https://github.com/steinbergmedia/vstgui/blob/f326bb4853f4cc30283cdb5377a7e996c7df1df0/vstgui/lib/platform/linux/x11platform.cpp#L122-L125

Here the location of how the path is deduced, by `dlinfo` API and going 3 folders up from there
https://github.com/steinbergmedia/vstgui/blob/f326bb4853f4cc30283cdb5377a7e996c7df1df0/vstgui/lib/platform/linux/x11platform.cpp#L143-L168

**Comment by jpcima** [comment]
It's VSTGUI.. this is a recap of the issue

Here is a static initializer to compute the resource path `UTF8String Frame::resourcePath`
https://github.com/steinbergmedia/vstgui/blob/f326bb4853f4cc30283cdb5377a7e996c7df1df0/vstgui/lib/platform/linux/x11frame.cpp#L797

Obtaining this resource path depends on setting the global variable `soHandle`, and it must be before this initializer is computed.

`soHandle` is set only on the first instantiation of the editor, so the `resourcePath` above is sure to be incorrect
https://github.com/steinbergmedia/vst3_public_sdk/blob/c04e9bd690f50893742e2a082abab47af2c3efc8/source/vst/vstguieditor.cpp#L86

But that's not the actual problem, there's more.

This static initializer will cause creation of the singleton instance of `X11::Platform`, which will incorrectly set in stone the cairo bitmap search path, using the empty path prefix.
https://github.com/steinbergmedia/vstgui/blob/f326bb4853f4cc30283cdb5377a7e996c7df1df0/vstgui/lib/platform/linux/x11platform.cpp#L122-L126

If I should guess why this works on a platform and not another, probably it's the `UTF8String Frame::resourcePath` is some unused variable that linker may or may not strip, and it falls into the described problem in case it doesn't.

**Comment by hexdump0815** [comment]
i just wanted to let you know that i see the exact same problem on ubuntu 18.04 x86_64 with reaper as well ...

**Comment by jpcima** [comment]
This patch should resolve VSTGUI's static initializer issues.
[vstgui.patch.gz](https://github.com/sfztools/sfizz/files/4398581/vstgui.patch.gz)

In addition to the problem described above, another thing is that Cairo bitmaps won't load right if there is an attempt before the call of `X11::Platform::getInstance()`.
This gets rid of `setGetResourcePathFunc`.

**Comment by hexdump0815** [comment]
i can confirm that the above patch fixes the logo problem - tested with the vst3 on armv7l and aarch64 ubuntu 18.04 with reaper ...

**Comment by paulfd** [comment]
So in the end we will host a version of the VST headers on a fork? Another option would be to use CMake's facilities to patch VST before building, since we already download it on configure.... I think FetchContent or ExternalProject have such abilities. Things like Conan or vcpkg do too.

**Comment by jpcima** [comment]
This is the plan on VST. Here is the original repo: https://github.com/steinbergmedia/vst3sdk
You can see it's made of a variety of submodules.

Including only the subset lets us skip some stuff we don't need (eg. the docs one which is super huge)

It's recommended that we make these [shallow submodules](https://git-scm.com/docs/git-submodule) so it doesn't pull the whole history by default, keeping the clone more lightweight.

Also we have to make personal forks of these to apply following patches:
- linux VSTGUI
- windows MinGW

**Comment by paulfd** [comment]
Yes I remember the repo (dear Lord, the memories...). My question was more: do we need to have personal forks rather than applying patches after [this line](https://github.com/sfztools/sfizz/blob/8861e0e8dc30412e64a696f44f07b3b3ac87f4da/vst/CMakeLists.txt#L25)?

**Comment by jpcima** [comment]
There are some motivations to make the clone complete with VST SDK.

It stems from Debian packaging mostly. @trebmuh has requested that the source package is complete, so he doesn't have to repack it.

Debian accepts only one archive of sources, and must forbid download during its build.

It's also the case for me of OBS builds, I can build RPM and Arch with separate source archive, but can't do Deb because I need all to be in one.

While unifying everything, we may as well include the patches.

**Comment by jpcima** [comment]
Problem is solved in `develop`
