### ISSUE TITLE
VSCO SViolin-KS.sfz has a non-standard usage of the <control> header

### ISSUE THREAD

**Issue by paulfd** [sfztools/sfizz#14]
Probably better to fix it upstream. Using multiple relative `default_path` opcodes does not seem so well formed: should we take the relative path with respect to the current sample path or the sfz file parent path? What about includes?

**Comment by michaelwillis** [comment]
@sgossner Just a heads up, are you aware of this being a problem with other SFZ plugins?

**Comment by sgossner** [comment]
default_path is a major space saving tool for instruments featuring deeply nested samples. It is part of the SFZ 2.0 spec, which VSCO 2 CE's files follow; both ARIA/Sforzando and Linuxsampler support default_path.

As used in VSCO 2 CE, it is merely a string which is appended to the start of each sample location as given in the individual regions which inherit from the respective control header. New control headers, as specified in the SFZ spec, replace previous control headers allowing a new default path to be specified mid-file. If for some reason the plugin in question is not allowing this, then its implementation is not following the SFZ spec (you can use non-KS patches as a workaround, or use a simple replace operation in your text editor of choice to re-incorporate the paths at the cost of file size). If default_path is not working at all, then it probably just isn't supported (yet?).

All VSCO 2 CE SFZ's are tested and verified to work correctly in ARIA/Sforzando and theoretically work in LinuxSampler. I have no plans to make revisions to the master VSCO 2 CE files just to add compatibility with this or that non-standard sampler/SFZ implementation, but if someone wants to make their own fork that is of course allowed.

Note: Fundamentally, controls, globals, groups, and masters must be able to override the previous effects of any equal or parent header, similar to XML or HTML. Therefore, a standard implementation of control or any other header must allow for (1) multiple of them to exist, and (2) each subsequent one to "overwrite" the previous information for the items "nested" inside of it. When you imagine SFZ to follow a hierarchy like XML or HTML, with regions nested in groups nested in masters nested in globals, this makes sense. This is intended in the original spec as described by Rene and is how it is implemented in ARIA/Sforzando, and used in most SFZ instruments including VSCO 2 CE's SFZ's.

**Comment by paulfd** [comment]
Thanks, I will integrate it this way as I do agree that this use makes sense. Please consider proposing an update https://sfzformat.com/headers/, the control header and default path oppose with all the information you wrote so that it's clear for everyone. I have no other sfz reference.

I disagree with the xml comparison but it's another matter.

The default path should not be taken with respect to the current default_path, but the sfz file parent path. If a file is #included, should I take the initial root file or the included file parent path?

**Comment by sgossner** [comment]
I'll leave a note on the SFZ Discord group to consider revising the headers page to better match how the ARIA engine performs. The sfzformat website is still very WIP with certain information. Luckily some folks from Plogue are involved in the Discord group so it is easy to get accurate information on implementation there!

You may find these earlier resources interesting-
The original SFZ Format instructions by Rene (mirrored): https://sfzformat.com/legacy/
Peter L. Jones' take on SFZ (very early, but still relevant): http://drealm.info/sfz/plj-sfz.xhtml

I don't make use of #includes in any of my instruments... this is the file being discussed, correct?
https://github.com/sgossner/VSCO-2-CE/blob/SFZ/SViolin-KS.sfz

The only ways to find out would be to try making a patch with an include and two different paths and see what the ARIA engine does, or to ask in the SFZ discord about it.

**Comment by paulfd** [comment]
I've read both of these before, but they don't seem to mention `default_path` since it's sfz v2 probably. I've implemented this in 4916b94fc3a585afd4b7490c4e120f9e1d5dea03 assuming that all paths are w.r.t. the root sfz file, as are #includes. This can be modified later if there is a major discrepancy, until then I'll close this.
