### ISSUE TITLE
armv7l support and vst3 support for aarch64 and armv7l

### ISSUE THREAD

**Issue by hexdump0815** [sfztools/sfizz#147]
i just wanted to let you know that i successfully built sfizz on armv7l (ubuntu 18.04) and i also enabled the vst3 build for both armv7l and aarch64 and it works well (tested on both platforms with reaper) ... here are the notes and the patch from my build try: https://github.com/hexdump0815/sfizz-arm-build ... under releases one can find an example build

best wishes and keep up this cool project - hexdump

**Comment by jpcima** [comment]
Nice thanks for sharing it.

Feel free to add post the VST ARM patch as PR. Only intel archs were listed when I made it, we'll take others as well.
Normally you wouldn't need a patch for these VST architectures, it was intented that you could pass them as `-DVST3_PACKAGE_ARCHITECTURE=..`

On the VSTGUI one, it's certainly time we fork steinberg to fix all we need.
We discussed about having them back as submodules. This will also helps the package maintainers.

>best wishes and keep up this cool project - hexdump

more great features will be coming :)

**Comment by hexdump0815** [comment]
just in case anyone wants to play with it, i have updated my arm build to version 0.3.2: https://github.com/hexdump0815/sfizz-arm-build/releases/tag/0.3.2

**Comment by paulfd** [comment]
Hey! Thanks again for sharing this. I think @jpcima integrated it in our vstgui fork so it's in the main build now :slightly_smiling_face: I'm closing this one.
