### ISSUE TITLE
Sound cutting when playing fast note sequence

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#148]
To reproduce
- open Sfizz in carla, with `sample=*sine` instrument
- go to the patchbay tab
- click sfizz's jack client
- click a note on the virtual keyboard, keep it help, and rapidly move it left and right across keyboard

At some points after doing this, some more or less strong glitch noises will be emitted.
It sounds like a discontinuity, but I can't record it as sound to exhibit the bug.

If I try, the click sounds are silent in RecordMyDesktop recordings.
This leads to think it must be a NaN/inf occurring somewhere inside sfizz.

Moreover, if you add a `strings` effect to sound, this will cut the sound entirely without recovery.
It's another hint about a NaN/Inf problem; given `strings` recirculates its output signal through feedback.

**Comment by jpcima** [comment]
after a bit of debugging
- It's indeed a problem about NaNs
- the source of the NaNs is the current ampEG that's in develop (not the PR one)

**Comment by paulfd** [comment]
I think I'll merge the PR and we'll discard the unused API later 😄

**Comment by jpcima** [comment]
The problem seems gone with new EG thanks.
