### ISSUE TITLE
a 0.3.2 asset is missing?

### ISSUE THREAD

**Issue by trebmuh** [sfztools/sfizz#160]
@redtide : can you add a "sfizz-0.3.2-src.tar.gz (such as https://github.com/sfztools/sfizz/releases/download/0.3.1/sfizz-0.3.1-src.tar.gz).
Or maybe it isn't needed anymore and we can use https://github.com/sfztools/sfizz/archive/0.3.2.tar.gz?

**Comment by trebmuh** [comment]
Needed for:
- https://github.com/sfztools/sfizz/tree/master/external
- https://github.com/sfztools/sfizz/tree/master/vst/external/VST_SDK/VST3_SDK

**Comment by redtide** [comment]
there is some issue again with the Travis-CI, it should be an automated archive build, that was done because GitHub doesn't include submodules sources in its archive. Will add later manually.

**Comment by trebmuh** [comment]
done,  thanks people!
