### ISSUE TITLE
[FR] direction=reverse opcode

### ISSUE THREAD

**Issue by AlexMitchellMus** [sfztools/sfizz#179]
This feature request is for Sfizz to support:

`direction=reverse` opcode.

Specifically Sfizz should be able to work with the below SFZ example from René Ceballos:
```
<group> sample=wave_name_here.wav xf_cccurve=gain
<region> xfin_locc1=0 xfin_hicc1=127 direction=reverse
<region> xfout_locc1=0 xfout_hicc1=127
```

**Comment by jpcima** [comment]
Then it's needed to add [reverse_loccN](https://sfzformat.com/opcodes/reverse_loccN) to make this feature support complete.

**Comment by jpcima** [comment]
The PR #185 does not handle offset correctly when the direction is reversed. (checked against CW)
A diagram below of how it should be.

![Diagram](https://user-images.githubusercontent.com/17614485/79479878-afc3db00-800d-11ea-872b-f24748c03dd9.png)

**Comment by jpcima** [comment]
Addendum/Correction:

The above depicts current Sfizz (orange color) vs Dropzone (green)

- ARIA does it also like Sfizz current
- Dimension, RXP do it like Sfizz current too!

Cakewalk products don't agree to each other, so it can be the case that this implementation is good.
It can be also argued that it's more useful.
