### ISSUE TITLE
MIDNAM duplicate note number sw_label live editing

### ISSUE THREAD

**Issue by AlexMitchellMus** [sfztools/sfizz#191]
Ardour displays in the log `Duplicate note number 36 (KS_tri) ignored` when live editing `sw_label` in a SFZ file while the same SFZ file is loaded in Sfizz.

Steps to reproduce:

1) create a new SFZ file as below
2) load SFZ file into Sfizz
3) change the name of `sw_label` in a text editor and save
```
<global> sw_lokey=36 sw_hikey=37 sw_default=36
<region> sw_label=KS_tri sw_last=36 lokey=38 sample=*tri
<region> sw_label=KS_sine sw_last=37 lokey=38 sample=*sine
```
Not only will the log display an error, but the MIDNAM data will not be updated for the key-switch name. Other MIDNAM names are able to be live edited and changed, except key-switches.

In order to allow the key-switch name to update- the Sfizz plugin need's to be loaded.

**Comment by jpcima** [comment]
You're right that it needs to clear the keyswitch labels.
I added it at 364a2af.
