### ISSUE TITLE
Ardour template does not load SFZ files

### ISSUE THREAD

**Issue by jens-r** [sfztools/sfizz#194]
I'm trying to use the "Virtual Playing Orchestra Template" for Ardour (https://github.com/michaelwillis/virtual-playing-orchestra-ardour-template). If I use the template, I have to manually select the SFZ-file for all the instruments. See this bug: https://github.com/michaelwillis/virtual-playing-orchestra-ardour-template/issues/5

An Ardour session created from the template has an empty sfzfile path (in the state.ttl files):

    ...
    <http://sfztools.github.io/sfizz:sfzfile> <> ;
    ...

I have tried to solve the problem by creating a new, working, template. But I can't see that there is any difference in the template files.

I have tested with:
sfizz 0.2.0 - 0.3.2
Ardour 5.12 - 6-git
(CentOS 8 and Ubuntu 18.04)

Anyone here might know what is causing this bug?

**Comment by jpcima** [comment]
Hello,
this problem is because the SFZ files are in different paths from a computer to another, and sfizz cannot currently deal with this.
As result, sessions files will not be currently shareable.

eg. if a Ardour session is saved with `/home/alice/myfile.sfz`, it can't reload on another computer which has it in `/home/bob/`.

We have to investigate LV2 spec for possible solutions.

**Comment by jpcima** [comment]
It seems to be the job of the LV2 `mapPath` extension.
https://lv2plug.in/ns/ext/state/state.html#mapPath

There is some code in zeroconvo that shows the usage.
https://github.com/x42/zconvo.lv2/blob/72d701ffb2a3272dc5f7db01ae9e07a5781c6e12/src/lv2.cc#L530

**Comment by jens-r** [comment]
I have verified that the paths to the SFZ files are the same on my computer (following the instructions from https://github.com/michaelwillis/virtual-playing-orchestra-ardour-template ). I have also verified against a new working template that uses the exact same paths.

Here I show how I tested in Ubuntu 18.04:
https://github.com/michaelwillis/virtual-playing-orchestra-ardour-template/issues/5#issuecomment-615374952

**Comment by jpcima** [comment]
It's reproduced on my side. It's possibly a problem of the template.

On creating the project, many errors like this one are seen.
```
error: failed to open file /Users/michaelwillis/Library/Preferences/Ardour5/templates/Virtual Playing Orchestra/8045/state5/state.ttl (Aucun fichier ou dossier de ce type)
```

and the path `/Users/michaelwillis/[...]` is hardcoded into the template.
That is probably the origin of the issue, and then it has to do with the template and not sfizz.

**Comment by mattias-ohlsson** [comment]
It has to do with the template:
https://discourse.ardour.org/t/templates-sometimes-include-absolute-paths-with-my-home-dir/89283

:) :+1:

**Comment by redtide** [comment]
I think the origin of the problem might be a missing LV2 feature (liblilv, not in Ardour) to save independent standard paths. I suppose it would work if copying the template in a machine with the exact same path only, otherwise if it could be saved like some `$HOSTCFGDIR/template/...` it would work.
In brief not a host issue, nor plugin one.

**Comment by agittins** [comment]
I believe this is a bug in Ardour and how it chooses to store pathnames, and not a bug in sfizz or lv2. I've raised a bug at https://tracker.ardour.org/view.php?id=8057, I think that and the one against the template at https://github.com/michaelwillis/virtual-playing-orchestra-ardour-template/issues/5 are the two correct places for the bug report, this one could probably be closed.

**Comment by paulfd** [comment]
OK ! @jens-r can you confirm? Apparently the Ardour template bug got resolved too.

**Comment by jens-r** [comment]
Yes, thank you everyone! I can use the template without any problems.
