### ISSUE TITLE
Block comments in SFZ file fail to load

### ISSUE THREAD

**Issue by AlexMitchellMus** [sfztools/sfizz#195]
## Issue
Block comments starting with `/*` and ending with `*/` cause Sfizz to not load the SFZ file, and print to Ardour log:
2020-04-20T17:36:34 [ERROR]: [sfizz] Error with EXAMPLE_FILE; no file should be loaded

Removing block comments fixes issue. Comments starting with `//` do not exhibit this issue.

## Versions:
Latest Sfizz Git
Latest Ardour Git

## Example File:
```
/*
*/
<region> sample=*sine
```

**Comment by jpcima** [comment]
It's fixed starting with commit c2767b3
