### ISSUE TITLE
Note-on at velocity 0

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#208]
The jack client should handle note-on velocity 0 as note-off.
https://github.com/sfztools/sfizz/blob/b528f54db162d5a00eace39d2512caf8988c784d/clients/jack_client.cpp#L71-L74

There are 2 potential resolutions for these problems.
- to handle note-on 0 at sfizz library level
- to handle it in the plugins

Notes:
- Perhaps, it's best to leave it to plugins. As VST3 is concerned, incoming velocity is a float and I'm not sure of what to do of it in case of 0.
- By LV2's specification, noteon 0 is strictly forbidden, nevertheless it's not bad to protect against bad hosts as defensive measure.

**Comment by paulfd** [comment]
Agreed, this is a front-end matter. But it does happen in the wild, I've seen it either in midi files or Reaper or something. Reaper does not do it now, I just tried, so must be somewhere else...

Commit : 5ee3e92848b580df2322bcb3287e8c630d9d4caf
