### ISSUE TITLE
Symbols missing from shared object.

### ISSUE THREAD

**Issue by spongeboburu** [sfztools/sfizz#21]
Hello.  Thanks for a fun project, well done!

I'm trying out the develop branch, after building successfully I check `libsfizz.so` and it does not contain any of the symbols found in `libsfizz.a`.

I'm not sure if C++ differs from C when it comes to linking, but I think the symbols of an archive (static library) are only included when linking if they are actually used by whatever you are linking. I'm not sure if this is the problem, but maybe.

I think you can use `-Wl,--whole-archive static_libs.a -Wl,--no-whole-archive` to include everything. There's also a cmake recipe for creating archives and shared objects from the same set of objects:

```
set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON) # Handy when building on windows

add_library(library_objects OBJECT ${source_files})
set_target_properties(library_objects PROPERTIES POSITION_INDEPENDENT_CODE 1) # Linux

add_library(library_static STATIC $<TARGET_OBJECTS:library_objects>)
target_link_libraries(library_static PUBLIC we_need_this_too.a)
if(BUILD_SHARED)  
    add_library(library_shared SHARED  $<TARGET_OBJECTS:library_objects>)
    target_link_libraries(library_shared PUBLIC we_need_this_too.a)
endif()
```
Linking with the other static libraries (absl) should then work for the symbols used by any of the objects, but I'm not sure. May be totally wrong here.

**Comment by paulfd** [comment]
No you are right apparently there are indeed no symbols in the shared libraries (and too many symbols in the LV2 plugin...). I will try to sort this out !

**Comment by paulfd** [comment]
d3cb36dcc8971d1329577d823f579f1bd2433fd9 should implement the proper exports, also for the lv2 (more or less). I'll wait for your confirmation! Note however that this only concerns the C API (i.e. the one in https://github.com/sfztools/sfizz/blob/develop/src/sfizz.h). If you want to link in native C++ static linking is the only way for now.

**Comment by spongeboburu** [comment]
Hi Sorry for the late response!

The shared object now has a lot of symbols. I tried new, load and free functions, they work. So consider this resolved. If find that anything else is missing I'll report it here.
