### ISSUE TITLE
Feature request: loops from FLAC tags

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#229]
Currently it's only WAV and a handful others which can handle loops directly in the sound file.
Flac does not have this ability.

A suggestion is to use tags to store this information.
There isn't an established specification, but there are some relatively established conventions used by a few video game engines.

https://wohlsoft.ru/pgewiki/How_To:_Looping_music_files
https://doomwiki.org/wiki/Audio_loop

Desired also: a tool for converting wav to flac, and preserving the loop using one of these specifications.

[loop.tar.gz](https://github.com/sfztools/sfizz/files/4629659/loop.tar.gz)

**Comment by kinwie** [comment]
Tested the included flac file. The loop seems not function yet
