### ISSUE TITLE
Consider giving CC7 and/or CC11 default behavior

### ISSUE THREAD

**Issue by michaelwillis** [sfztools/sfizz#23]
I'm not sure whether this is strictly compatible with the SFZ spec, but it would be nice if Channel Volume (CC7) and/or Expression (CC11) had default behavior of controlling volume. Of course if the SFZ file specifies their behavior, it should override the default.

**Comment by paulfd** [comment]
> Paul Fd
> @Michael Willis I saw them, the dynamic crossfade is probably a small commit away :sweat_smile:
> For the default CC why not, I am concerned about the fact that I also have a volume on the lv2 part
> Would these be the same volume or separated? That may be a bit weird for users? What do you think?
> I am but a puny developer for this usability part so honestly, I would believe and implement it the way you and/or @alexmitchellmus think it's best for users
> Same for panning btw

**Comment by paulfd** [comment]
> Michael Willis
>     @Paul Fd About your earlier question, my opinion is that there should be two separate types of volume control. I want to set one "global" gain level once that controls how the track's overall volume compares to other tracks. I don't want automation to change that one. I want a different one with automation that changes throughout the session to do crescendos and decrescendos.
> 
> Traditionally, CC7 is supposed to be the former, and CC11 is supposed to be the latter.
> But ultimately I don't really care what it is, so long as I have both.
> As I'm experimenting with sfizz, I've been using the dB gain available in the plugin parameters as the "global" level without automation.
> One problem with making CC7 correspond to the dB gain parameter is that it doesn't have very fine granularity, only 128 different possible values.

**Comment by paulfd** [comment]
> Paul Fd
> @Michael Willis But don't hosts usually also provide a track fader for the more stable volume? I was kinda counting on this to be the global volume and expected the lv2 one to be more the crescendo one that you would automate as needed

**Comment by paulfd** [comment]
(Let's continue this conversation here for tracking)

**Comment by paulfd** [comment]
I also see that CC10 is global panning in Sforzando

**Comment by paulfd** [comment]
I think now these have the expected effect, so I'm closing this !
