### ISSUE TITLE
Group-level opcodes considered "unknown"

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#231]
The opcodes handled at group-level, such as `polyphony`, are put in the unknown opcode list, despite that they have been handled at `handleGroupOpcodes`.

~~The opcode "polyphony" appears at <master> level in the Naked Drums set.
Sfizz has a problem with it because it seems only handled at the <group> level.~~

**Comment by paulfd** [comment]
This should be handled by #275 .
