### ISSUE TITLE
Trigger on CC incorrect

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#239]
The following example will trigger on CC in ARIA.
It does not on sfizz, unless `key=-1` is written explicitly.
Surely it's another case of ARIA where `-1` and `<not set>` have identical semantic.

```
<region>
sample=*sine
start_locc16=100
start_hicc16=127
```

**Comment by paulfd** [comment]
I remembered seeing it mentioned explicitely somewhere. It was on [Peter Jones' page](http://www.drealm.info/sfz/plj-sfz.xhtml).

> To prevent the player even trying to match the components of a Note On event for a layer, set the note number upper limit to -1. If you want the layer triggered by a MIDI CC event, you *must* do this. 

I don't mind matching ARIA though. I'll test what happens with e.g.
```
<region>
sample=*sine
start_locc16=100
start_hicc16=127
key=64
```
and
```
<region>
sample=*sine
key=64
start_locc16=100
start_hicc16=127
```

**Comment by paulfd** [comment]
@jpcima you corrected this already no?

**Comment by jpcima** [comment]
I didn't do anything regarding this problem.

**Comment by paulfd** [comment]
My examples mess up with sforzando, I've contacted David about it.

In the meanwhile I'll try to match the behavior by just deactivating CC triggering when a `key`-type opcode is encountered, and deactivating key-triggering when a CC trigger is encountered.

People mixing and matching those in regions are not likely. The most obvious case would be that there are some key (or CC) opcode in a group or master, and you want to have in your region a CC (or key) trigger. Using the latest opcode in this case thus makes sense to me.

**Comment by paulfd** [comment]
Actually, your example:
```
<region>
sample=*sine
start_locc1=127
start_hicc1=127
```
does not disable key triggers in Sforzando. I'll need to update #315.
