### ISSUE TITLE
Parameter automation of VST

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#240]
Some things to remember/fix regarding the parameter automation.

- [x] When a SFZ file initialized a CC, this should automate the corresponding parameter in the plugin.
- [x] It was reported by @kinwie that CC parameters don't do anything when they are manipulated with Hermann Seib's VSTHost generic UI.
  Likely related to the Bitwig console log warning about the CC parameters.
  In other VST3 example plugins, the CC parameters are hidden, unlike ours are.

**Comment by paulfd** [comment]
Should be fixed now right?

**Comment by jpcima** [comment]
Yes it should be all good. Some testing in a larger range of hosts would be appreciated.
On host side, there remains this problem that Juce's hosting classes don't notify the controller of changed CC when it happens by MIDI. So don't be surprised if Carla lacks this support. Reaper works well.

**Comment by paulfd** [comment]
I'll close this then ! Thanks !
