### ISSUE TITLE
Crash with Ardour

### ISSUE THREAD

**Issue by gonsolo** [sfztools/sfizz#248]
I'm trying to a bassoon from Virtual Playing Orchestra via an sfz file using self-compiled sfizz (commit 8a43a9fa873c190afdb0ae7ed05f38c8dd181a27).
It works great until I try looping. After setting a loop region and pressing L Ardour crashes reliably at the end of the loop.

1. Download VPO from http://virtualplaying.com/virtual-playing-orchestra/
2. Clone sfizz from https://github.com/sfztools/sfizz/
3. Compile sfizz & move the resulting sfizz.lv2 to ~
4. Open Ardour, scan for plugins, at a midi track add some notes, add sfizz in the mixer, use bassoon from vpo.
5. Playing works fine, looping crashes.

I don't know whether this is a bug in Ardour or sfizz.

I opened a bug in Ardour too: https://tracker.ardour.org/view.php?id=8127

**Comment by gonsolo** [comment]
The culprit was an assert at src/sfizz/SIMDHelpers.h +386:

ASSERT(gain.size() == input.size());

But when arriving at the end of the loop in Ardour, the gain can be as small as 16 while the input and output stay at 1024.

I think either that assert has to be removed (the min is taken anyway a few lines later) or the default cmake configuration should specify no-asserts.

Thanks.

**Comment by gonsolo** [comment]
Setting the default cmake configuration to Release is enough, too.

**Comment by jpcima** [comment]
Hello. It's most likely a benign problem that occurs only under debug mode which enables the asserts, as you have noted.

This raises an issue already observed, that there should be an option to enable Release+Asserts.
Also, since it's not the the first time that such a problem of this kind is reported, it may be wise to set the default build type to something more appropriate. (eg `RelWithDebInfo`)

sfizz should not be built unoptimized in the vast majority of cases.

- [x] identify the assert failure and fix
- [x] set a default build type (see https://blog.kitware.com/cmake-and-the-default-build-type/)
- [x] add the option to enable assertions in release modes

**Comment by gonsolo** [comment]
Since I am developer I can help myself. As a user I would go away after a crash.
The best thing for me would be an Ubuntu/Debian package with the right compile options.

Don't get me wrong; I tested several plugins for my little orchestration project and yours is the only one that worked. :)

**Comment by jpcima** [comment]
>The best thing for me would be an Ubuntu/Debian package with the right compile options.

There exist some automated package builds for all distributions.
https://build.opensuse.org/package/show/home:sfztools:sfizz:develop/sfizz

Although this was broken in recent commits, I push a few changes to fix it.

**Comment by gonsolo** [comment]
> There exist some automated package builds for all distributions.
> https://build.opensuse.org/package/show/home:sfztools:sfizz:develop/sfizz
<https://build.opensuse.org/package/show/home:sfztools:sfizz:develop/sfizz>
> Although this was broken in recent commits, I push a few changes to fix
it.

That's cool, thanks. I tested it and it seems to work.

On the other hand, I would never have found it without you. I tried "apt
search" and if it doesn't show up I usually give up. I think it would be
very beneficial for your visibility to upload those packages to Debian
and/or Ubuntu.

Thanks
-- 
g

**Comment by jpcima** [comment]
Latest commits are expected to resolve the issue under debug mode.

>On the other hand, I would never have found it without you. I tried "apt
search" and if it doesn't show up I usually give up

On the places where to find these downloads at the moment, it's on the sfz.tools website downloads section, and the wiki of this repo. These links will be for the stable release channel.

That which I linked to you is the development channel which has the continuous updates from git commits.

Regarding these packages, they're not adhering to debian package standards, hence not immediately fit for official redistribution. There exists the distribution LibraZiK which distributes a more adequately packaged sfizz (stable) in their repos. 
[sfizz in repo](https://download.tuxfamily.org/librazik/pasapas/pool/main/s/sfizz/)
[home](https://librazik.tuxfamily.org/base-site-LZK/english.php)

**Comment by gonsolo** [comment]
>
>
> On the places where to find these downloads at the moment, it's on the
> sfz.tools website downloads section, and the wiki of this repo. These links
> will be for the stable release channel.
>

Ok, I see. Cool.


> That which I linked to you is the development channel which has the
> continuous updates from git commits.
>
> Regarding these packages, they're not adhering to debian package
> standards, hence not immediately fit for official redistribution. There
> exists the distribution LibraZiK which distributes a more adequately
> packaged sfizz (stable) in their repos.
> sfizz in repo
> <https://download.tuxfamily.org/librazik/pasapas/pool/main/s/sfizz/>
> home <https://librazik.tuxfamily.org/base-site-LZK/english.php>
>

Also cool.

However: This sort of fragmentation is not helpful. In my ideal world those
packages would be in Debian (and Ubuntu), Ubuntu defaulted to a low-latency
kernel, Ardour is a deb package in Debian with dependencies on sfizz and
VPO, also in Debian. That way I wouldn't have to spend hours searching the
internet, compiling stuff, and fixing crashes. There is a reason people
stay on Windows or macOS.
<rant over>

But thanks for writing sfizz. It's amazing. :)

-- 
g
