### ISSUE TITLE
SFZ opcode (exclusive) groups

### ISSUE THREAD

**Issue by grammoboy2** [sfztools/sfizz#256]
Seems to be important for cymbals
https://sfzformat.com/tutorials/cymbal_muting

**Comment by kinwie** [comment]
I've already opened an opcode suggestion for the need of cymbal/hihat muting, here :
https://github.com/sfztools/opcode-suggestions/issues/3

**Comment by paulfd** [comment]
I think we handle most of the facility described on the cymbal muting page. If not, can you provide a minimal working example of what does not work with the expected behavior?

**Comment by grammoboy2** [comment]
On 7/1/20 5:49 PM, Paul Ferrand wrote:
>
> I think we handle most of the facility described on the cymbal muting 
> page. If not, can you provide a minimal working example of what does 
> not work with the expected behavior?
>
Thanks, I'll test it in the coming days if I find some time.
>

**Comment by paulfd** [comment]
Maybe wait for the next release for a more complete polyphony handling though!

**Comment by paulfd** [comment]
Misclicked sorry :slightly_smiling_face:

**Comment by grammoboy2** [comment]
> Maybe wait for the next release for a more complete polyphony handling though!

Sure, please let me know when the polyphony handling is ready! Thx.

**Comment by kinwie** [comment]
I just remember about this post. The exclusive groups and choking behavior already completely done by @paulfd couple builds ago, which cover both Cakewalk and ARIA behaviors perfectly. All other necessary needed opcodes for this also have been implemented well, i.e. `off_time` `note_polyphony` and CC usage for same group number

I think this can be closed now?

**Comment by grammoboy2** [comment]
You guys are doing amazing work it seems! Thanks and keep up the good work. Will try it out later.

**Comment by kinwie** [comment]
@grammoboy2 have you tried the choke grup feature in sfizz latest build? I supposed this issue can be closed now?

**Comment by grammoboy2** [comment]
Not yet, but it can be closed indeed I think. Thanks again!
