### ISSUE TITLE
Some Sonatina instruments non working

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#260]
Reported by @sub26nico. This was sfizz stable 0.3.2

>with Sonatina Symphony Orchestra soundfonts, some SFZ patches are working, some are not. Regarding brass, for one given instrument, the 'sustain' articulations would work but not 'staccato' ones

>Brass-Horns sustain works, not Brass-Horns staccato

The bank which used to be available at this website: http://sso.mattiaswestlund.net/index.html
He provided a copy of SFZ files. Most likely its the same as https://github.com/peastman/sso

[Sonatina Symphonic Orchestra-patches.tar.gz](https://github.com/sfztools/sfizz/files/4679190/Sonatina.Symphonic.Orchestra-patches.tar.gz)

**Comment by trebmuh** [comment]
[Archive of it if needed](https://web.archive.org/web/20180222133126/http://mattiaswestlund.net/samples/sonatina-symphonic-orchestra-1.0.zip)

**Comment by jpcima** [comment]
@redtide has reported the instrument as working on develop, defective on 0.3.2 stable.
While not exactly identified, it's possible this problem was already fixed in development.

**Comment by paulfd** [comment]
I'll close this for now then !
