### ISSUE TITLE
terminate called after throwing an instance of 'std::logic_error'

### ISSUE THREAD

**Issue by magnetophon** [sfztools/sfizz#27]
When I run ``sfizz_jack`` I get:

```
Flags
- Oversampling: 1x
- Preloaded Size: 8192
Positional arguments:
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
[1]    3300 abort (core dumped)  sfizz_jack
```
This is on the develop branch, commit 994fe1738d8a6a0560626621c002201f5c7acd3c

**Comment by paulfd** [comment]
Yeah it's because the client expects a positional argument with an sfz file to load. I've updated the client to exit with a message if there's not enough arguments.

**Comment by magnetophon** [comment]
great, thanks!
