### ISSUE TITLE
macos sierra 10.12.6 build/link error around align_val_t

### ISSUE THREAD

**Issue by hexdump0815** [sfztools/sfizz#270]
i just tried to build sfizz myself on macos sierra 10.12.6 (compiler found is AppleClang 9.0.0.9000039) and get the following build/linker errors:
```
[ 49%] Linking CXX shared module ../sfizz.lv2/sfizz.so
undef: __ZnwmSt11align_val_t
undef: __ZdlPvSt11align_val_t
Undefined symbols for architecture x86_64:
  "operator new(unsigned long, std::align_val_t)", referenced from:
      _sfizz_create_synth in libsfizz.a(sfizz_wrapper.cpp.o)
  "operator delete(void*, std::align_val_t)", referenced from:
      _sfizz_create_synth in libsfizz.a(sfizz_wrapper.cpp.o)
      _sfizz_free in libsfizz.a(sfizz_wrapper.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
any odea how to get this resolved? any compiler options to maybe not add extra alignement stuff?

a lot of thanks in advance and best wishes - hexdump

**Comment by jpcima** [comment]
If I believe the reference document, aligned operator new is available only on c++ version 17 and up.
https://en.cppreference.com/w/cpp/memory/new/operator_new

Perhaps `-DCMAKE_CXX_STANDARD=17` helps to resolve this?

**Comment by hexdump0815** [comment]
i did already use that option - i basically used the cmdline from https://github.com/sfztools/sfizz/blob/develop/.travis/script_osx.sh ... looks like -DCMAKE_CXX_STANDARD=14 helps :)

**Comment by jpcima** [comment]
Most likely it's the effect of a system c++ runtime too old to support this feature.

I don't recall where exactly this alignment consideration comes from, but I recall it is seen in some warning logs.

**Comment by hexdump0815** [comment]
at least the resulting binaries work and this way i'm able to compile sfizz on my system too ...

**Comment by jpcima** [comment]
I downgraded the Travis build to 14, hopefully this lets next release builds to work on older macOS.
