### ISSUE TITLE
Crash when smoothcc present and polyphony changed

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#284]
- `loadSfzFile` allocates smoother arrays
- `setNumVoices` -> `resetVoices` happens
- voices are recreated with empty smoother arrays
- crash on next key-on

**Comment by jpcima** [comment]
Possibly, maxFilters/maxEQs are affected the same.
These occur at the end of sfz loading.

```
    for (auto& voice : voices) {
        voice->setMaxFiltersPerVoice(maxFilters);
        voice->setMaxEQsPerVoice(maxEQs);
        voice->prepareSmoothers(maxModifiers);
    }
```

**Comment by paulfd** [comment]
Right, good catch.
