### ISSUE TITLE
The jRhodes3d does not sound right

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#289]
Compare it with ARIA, the difference should be quite evident.
https://github.com/jlearman/jRhodes3d

jRhodes3d bafd91d3dabd0784cfa11686801c1bc8cb1cef55
sfizz 1f7f105584a87a99e8974af7b19d0c78f4aa7f65

**Comment by kinwie** [comment]
Could this possibly because the use of width_oncc and the curve for it?

**Comment by jpcima** [comment]
We don't have support of the `Ab1` kind of pitch notation.
I'm going to add it.

**Comment by jpcima** [comment]
It's fixed. Now it's only the range limits problem, but that's for another issue.
