### ISSUE TITLE
The *noise generator should be white, not gaussian

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#290]
It's a measurement of ARIA generator `*noise`. Cakewalk does not have it.
![Capture du 2020-06-22 17-13-15](https://user-images.githubusercontent.com/17614485/85304982-b1e26400-b4ac-11ea-8499-ca05d0a951e1.png)

We could keep the gauss one as extension, eg. "*gnoise".

**Comment by paulfd** [comment]
OK so noise is actually uniform noise. What's the frequency response of this btw?

**Comment by jpcima** [comment]
The amplitude response of white noise is supposed to be roughly a flat line.

As I was discussing with @redtide a bit earlier, the white noise also gives purpose to the `pink` filter type in order to create the `1/f` response.

**Comment by paulfd** [comment]
Could be another naming variation. For me white noise has a flat average *frequency* response over the band of interest. In almost every case I work with, the white noise is Gaussian and its histogram over time is therefore necessarily Gaussian too. Generating i.i.d. random Gaussian samples fills these properties for a sampled process.

As long as the uniform version is what people expect it's fine though :slightly_smiling_face:

**Comment by jpcima** [comment]
White noise is just the nothing-special random generator. This will describe it better
https://ccrma.stanford.edu/~jos/sasp/White_Noise.html
