### ISSUE TITLE
Instrument missing in export, unless UI opened

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#295]
According to @unfa, some SFZ instruments in a session are missing.
Regardless of the wait delay for instruments to play, the instrument does not play.
It can be experienced sometimes by exporting the project. (Ardour I suppose)
It's worked around by manually opening the UI and ensuring to reload the SFZ file there.

**Comment by paulfd** [comment]
@unfa I can't really reproduce this, is this an Ardour session you could share maybe?

**Comment by jpcima** [comment]
I could not reproduce this either.
All I can think of is the old problem of worker messages back and forth.
Then, it was possible that lv2 messages are not reaching destination because of buffer overrun, but this is supposed fixed since a long time and included in the stable release.

**Comment by jpcima** [comment]
I have observed a possibly related phenomenon recently. This was in carla.
I opened a sfizz plugin, loaded a SFZ file, saved. On reload, the SFZ path was different.

- Path opened:  /home/jpc/desktop/reverb.sfz
- Path on reload:  /home/jpc/documents/projects/sfizz/desktop/reverb.sfz

The path `/home/jpc/documents/projects/sfizz` exists on my disk.
The path `/home/jpc/documents/projects/sfizz/desktop` does not.

The exact log
```
[sfizz] File changed to: /home/jpc/.lv2/sfizz.lv2//Resources/DefaultInstrument.sfz
[sfizz] Number of masters: 0
[sfizz] Number of groups: 0
[sfizz] Number of regions: 1
[sfizz] Restoring the file /home/jpc/.lv2/sfizz.lv2//Resources/DefaultInstrument.sfz
[sfizz] Restoring the scale /home/jpc/.lv2/sfizz.lv2//Resources/DefaultScale.scl
[sfizz] Restoring the number of voices to 64
[sfizz] Restoring the preload size to 8192
[sfizz] Restoring the oversampling to 1
Parse error in "reverb.sfz" at line 1: Cannot open file for reading: /home/jpc/documents/projects/sfizz/desktop/reverb.sfz
[sfizz] File changed to: /home/jpc/documents/projects/sfizz/desktop/reverb.sfz
[sfizz] Number of masters: 0
[sfizz] Number of groups: 0
[sfizz] Number of regions: 0
[sfizz] Error while restoring the file /home/jpc/documents/projects/sfizz/desktop/reverb.sfz
[sfizz] Error while restoring the scale /home/jpc/documents/projects/sfizz/.lv2/sfizz.lv2//Resources/DefaultScale.scl
[sfizz] Restoring the number of voices to 64
[sfizz] Restoring the preload size to 8192
[sfizz] Restoring the oversampling to 1
```

**Comment by jpcima** [comment]
Posting another carxp, just created minutes ago, and its sfz, reproducing the problem all the time when opened.
[dry.zip](https://github.com/sfztools/sfizz/files/5000939/dry.zip)

Files are supposed to be in ~/desktop/

**Comment by jpcima** [comment]
When the carla session is fixed after resaving, the saved parameter gets a different value
```
--- dry-OLD.carxp	2020-07-30 13:31:52.568787115 +0200
+++ dry.carxp	2020-07-30 13:31:07.451126138 +0200
@@ -79,7 +79,7 @@
    <CustomData>
     <Type>http://lv2plug.in/ns/ext/atom#Path</Type>
     <Key>http://sfztools.github.io/sfizz:sfzfile</Key>
-    <Value>desktop/dry.sfz</Value>
+    <Value>../../../desktop/dry.sfz</Value>
    </CustomData>
 
    <CustomData>
```

**Comment by jpcima** [comment]
After researching, this is how the difference happens
- when carla is run from the CLI, and the CWD is `~/documents/projects/sfizz`,
  then path gets abstracted as `../../../desktop/dry.sfz`
- when carla is run from the desktop, the CWD is supposedly `~/`,
  then path gets abstracted as `desktop/dry.sfz`

that is, it gets abstracted relative to the CWD.

Further, some additional observations permit to confirm
- a carxp which is saved under CLI will reload only from CLI, not desktop
- inversely, a carxp created from desktop will not reload on CLI, only desktop

conclusion: both saving and reloading are affected by the CWD

**Comment by jpcima** [comment]
Note: an update of Carla `2.2.0.RC1.r37.g6669b2686` resolved this problem entirely
