### ISSUE TITLE
Deal with ampersand in sample names.

### ISSUE THREAD

**Issue by mickski56** [sfztools/sfizz#3]
A sfz file contains the following region line (edited for brevity)
<region> sample=..\G&S CW-Drum Kit-1\SnareFX\SNR-OFF-V08-CustomWorks-6x13.wav
sfizz_jack fails to load given sample because of "&" in the sample name.
Applying 
[parser.diff.txt](https://github.com/paulfd/sfizz/files/3621354/parser.diff.txt)
to sfizz/sfizz/Parser.h solves the issue. Not widly tested as yet but doesn't seem to have unintended consequences.

Hope this helps.

**Comment by paulfd** [comment]
Thanks, good catch :) I applied the patch and added a quick test with this filename. No regressions that I see, I don't think there are anywhere else where ampersands would be used.
