### ISSUE TITLE
The filters

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#30]
I attach an implementation of filters which matches ARIA near perfectly. (when implemented there)

It uses some very generic resonant filters, it showed to be quite easy to reproduce them.

Current:
[sfz-filters](https://github.com/jpcima/sfz-filters-experimental)
~[sfzfilters.dsp.gz](https://github.com/sfztools/sfizz/files/4125719/sfzfilters.dsp.gz)~

Reference:
https://sfzformat.com/opcodes/fil_type
https://sfzformat.com/opcodes/fil2_type

- 2 pole filters, cascaded for 4 pole and 6 pole
https://shepazu.github.io/Audio-EQ-Cookbook/audio-eq-cookbook.html

Status:
- [x] lpf_1p
- [x] hpf_1p (buggy in current Plogue ARIA, reported and fixed)
- [x] lpf_2p
- [x] hpf_2p
- [x] bpf_2p
- [x] bpf_1p
- [x] brf_1p (equivalent of brf_2p in Plogue ARIA)
- [x] brf_2p
- [x] lpf_4p
- [x] hpf_4p
- [x] lpf_6p
- [x] hpf_6p

New ARIA extensions:
- [x] lsh
- [x] hsh
- [x] peq

Not implemented by ARIA:
- [x] apf_1p
- [x] lpf_2p_sv
- [x] hpf_2p_sv
- [x] bpf_2p_sv
- [x] brf_2p_sv
- [ ] pkf_2p
- [ ] comb
- [x] pink

Implemented by us, not in specification:
- [x] bpf_4p
- [x] bpf_6p

**Comment by redtide** [comment]
`brf_2p` is listed in SFZ1 [fil_type](https://sfzformat.com/opcodes/fil_type), I kept them separated.

**Comment by jpcima** [comment]
@redtide edited.
Also, added the All-pass and Notch.

**Comment by jpcima** [comment]
Here, I implemented the Hal Chamberlin state-variable filter.
This one fits requirements to implement the `*_sv` opcodes, but needs way more precaution.
[chamberlin.dsp.gz](https://github.com/sfztools/sfizz/files/4127020/chamberlin.dsp.gz)

Reference: https://www.earlevel.com/main/2003/03/02/the-digital-state-variable-filter/

As noted from the article:
>The main drawback of the digital state variable is that it becomes unstable at higher frequencies. It depends on the Q setting, but basically the upper bound of stability is about where f reaches 1, which is at one-sixth of the sample rate (8 kHz at 48 kHz). The only way around this is to oversample. A simple way to double the filter’s sample rate (and thereby double the filter’s frequency range) is to run the filter twice with the same input sample, and discard one output sample.

It means if we want to permit range up to 22 kHz, oversample by 3 and call the filter with 1/3 effective cutoff.
(Assuming 44.1 kHz as FsMin)

**Comment by jpcima** [comment]
More general notes:

The cutoff is modulable, it means to recompute the filter coeffs, potentially at the audio rate.
- as it is, the operation will be expensive, considering it makes 1 or 2 mathcalls each audio frame (sin, cos, or "sincos" if known to compiler)
- a way to reduce computation, it's to update filter coeffs less frequently. for example, only update every Nth frame (typical N=16).
- in effect, this creates a staircase effect; while probably not perceptible, it needs to check if strong modulation affects the filter stability
- when LFO exists, it should be tested at extreme conditions that the filter stability holds well. one can generate the faust code with internal double precision to improve numerical robustness. (flag `-double`)

**Comment by jpcima** [comment]
I made a multimode-filter wrapper class. It is a very simple API.
https://github.com/jpcima/sfz-filters-experimental

It's probable that sfizz can use it like it is, however, it will be better if I make also a dedicated stereo wrapper, because then it can optimize filter computations further.

It permits modulation of Cutoff and Q. It works like this:
- Filter coeffs will recompute at some particular time intervals, such that it's less computation than updating it every frame. Computing the filter involves trigonometric functions.
- The coeffs are also going to be smoothed (an advice of David), such that it will be more robust in case of strong modulation. Also note than in this configuration, vectorizing is not possible.
- The smoothing is not really calibrated at this point, it was set to a default thing, which means a LFO may possibly lag. I left a TODO comment at `smoothCoefs`.

**Comment by jpcima** [comment]
Implemented most of filters in the [sfz-filters-experimental](https://github.com/jpcima/sfz-filters-experimental) repo above.
I think code as ready to be copied into sfizz at this point.

- added an optimized specialization for stereo
- added state-variable filters, based on Eric Tarr's Sallen-Key digital model
- had to upgrade the precision to double, as some models were instable (eg. the 6-poles)

From observation, state-variable variants don't have a lot of difference with ordinary biquads.

In the repo, you can find also a JACK Qt client if you'd like to test these filters.

**Comment by jpcima** [comment]
Added the Peaking EQ and shelves.

**Comment by paulfd** [comment]
Hi @jpcima and thank for all this work. I may not have time until this WE but I will prepare integration then and we can discuss more on a pull request if that's OK with you?

**Comment by paulfd** [comment]
Let's move this into the release, thanks alot!
