### ISSUE TITLE
Implement `ampeg_dynamic`

### ISSUE THREAD

**Issue by paulfd** [sfztools/sfizz#301]
- [x] Store the boolean in the region
- [x] Add a CC dispatch method to the ADSR envelope to update the parameters
- [x] On received CC in the voice, if the region has `ampegDynamic` set, update the ampeg

References:
- #300 
- https://sfzformat.com/opcodes/ampeg_dynamic.html

**Comment by jpcima** [comment]
Can we do the coeffs updates between blocks of size 16? the same as with modulated filters.

**Comment by paulfd** [comment]
Sure we could, it will be smoothed by the envelope anyway.
