### ISSUE TITLE
sfizz.lv2 needs to respect CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by atsushieno** [sfztools/sfizz#307]
I was trying to build and install development version of sfizz into non-standard location, apart from the some stable-ish version at `/usr/local`. But `sfizz.lv2` cannot be installed because it seems always trying to install it to `/usr/local`.

```
/sources/sfizz/build$ make install
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /sources/sfizz/dist/lib/libsfizz.a
-- Up-to-date: /sources/sfizz/dist/include/sfizz.h
-- Up-to-date: /sources/sfizz/dist/include/sfizz.hpp
-- Up-to-date: /sources/sfizz/dist/lib/pkgconfig/sfizz.pc
-- Installing: /sources/sfizz/dist/lib/libsfizz.so.0
-- Up-to-date: /sources/sfizz/dist/lib/libsfizz.so
-- Installing: /sources/sfizz/dist/bin/sfizz_jack
-- Installing: /sources/sfizz/dist/bin/sfizz_render
-- Up-to-date: /usr/local/lib/lv2/sfizz.lv2
CMake Error at lv2/cmake_install.cmake:49 (file):
  file INSTALL cannot set permissions on "/usr/local/lib/lv2/sfizz.lv2":
  Operation not permitted.
Call Stack (most recent call first):
  cmake_install.cmake:44 (include)
```

**Comment by jpcima** [comment]
Hi, you would have to also override the cmake variable `LV2PLUGIN_INSTALL_DIR` after the first run.
It's cached and defined at `cmake/LV2Config.cmake`, and it will be defined according to the initial value of the prefix.

(same applies to VST and `VSTPLUGIN_INSTALL_DIR`)

**Comment by atsushieno** [comment]
Ahh, I guess I only had a look at the topdir and `src`, not `lv2`. Thanks, it just worked. I'm not sure if there is any reason to have them independent of CMAKE_INSTALL_PREFIX (i.e. by design) and not sure if I had better close this issue or not. I leave it to you folks.

**Comment by paulfd** [comment]
```cmake

if (MSVC)
    set (LV2PLUGIN_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/lv2" CACHE STRING
    "Install destination for LV2 bundle [default: ${CMAKE_INSTALL_PREFIX}/lv2}]")
else()
    set (LV2PLUGIN_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/lib/lv2" CACHE STRING
    "Install destination for LV2 bundle [default: ${CMAKE_INSTALL_PREFIX}/lib/lv2}]")
endif()
```
We could `FORCE` these, or make them normal cmake variables rather than cached values? I don't remember if we had a good reason to cache these.

**Comment by paulfd** [comment]
Ok so there are still reasons to cache these, name that you could want them decoupled from the cmake install prefix.

The current best solution to this problem is thus a clean configure (with only the CMAKE_INSTALL_PREFIX that will propagate throughout the cache) or explicitely mention the LV2_PLUGIN_INSTALL_DIR on reconfigure. I don't think it is mandatory to add complexity to the build scripts at this point.

Thanks for reporting! :slightly_smiling_face:
