### ISSUE TITLE
Add C-api alternatives for common buffer layouts.

### ISSUE THREAD

**Issue by spongeboburu** [sfztools/sfizz#31]
Hi!

I'm currently trying to get sfizz running under Unity and I'm planning to use in Python for another project in the future. To help with rendering to buffers from other languages I added a couple of helpers in `sfizz_wrapper.c` to avoid implementing the float smashing in the bindings language.

The code isn't very good, but this is my temporary code for now:

```
void sfizz_render_block_noninterleaved(sfizz_synth_t* synth, float* channels, int num_channels, int num_frames)
{
    auto self = reinterpret_cast<sfz::Synth*>(synth);
    // Only stereo output is supported for now
    ASSERT(num_channels == 2);
    UNUSED(num_channels);
    self->renderBlock({{channels, channels + num_frames}, static_cast<size_t>(num_frames)});
}

void sfizz_render_block_interleaved(sfizz_synth_t* synth, float* channels, int num_channels, int num_frames)
{
    float tmpbuffers[2][32768]; // Is this somehow solvable with preallocated buffers?
    auto self = reinterpret_cast<sfz::Synth*>(synth);
    // Only stereo output is supported for now
    ASSERT(num_channels == 2);
    UNUSED(num_channels);
    if (num_frames > 32768)
        num_frames = 32768;
    self->renderBlock({{tmpbuffers[0], tmpbuffers[1]}, static_cast<size_t>(num_frames)});
    for (int i = 0; i < num_frames; i++)
        for (int j = 0; j < num_channels; j++)
            channels[i * num_channels + j] = tmpbuffers[j][i];
}
```

**Comment by spongeboburu** [comment]
I have also added ranges as public symbols so they can be accessed easily from bindings language:

```
typedef struct _sfizz_range_t {
    float min;
    float max;
} sfizz_range_t;

/**
 * @brief      A range for volume.
 */
extern SFIZZ_EXPORTED_API const sfizz_range_t SFIZZ_RANGE_VOLUME;

/**
 * @brief      Clamps a float value to a range.
 *
 * @param      range  The range.
 * @param      value  The float value.
 *
 * @return     A float clamped between the min and max value of the range.
 */
SFIZZ_EXPORTED_API float sfizz_range_clamp(const sfizz_range_t *range, float value);
```
EDIT: this doesn't work since C# doesn't seem to have a way to access non-function symbols. I'll have to figure something else out.

**Comment by paulfd** [comment]
Hi @spongeboburu 
As a matter of fact such interleaving is a quite common operation, which is e.g. implemented in [this function in sfizz](https://github.com/sfztools/sfizz/blob/a9d358d77400134bf0b4dd624d32930aaa78250e/src/sfizz/SIMDHelpers.h#L104). The SIMD helpers could be integrated in the wrapper, which potentially accelerate the second function.

I would argue however that such functions are much more general than the `sfizz` library in anything that controls interleaved buffers and thus I am not sure it is such a good idea to create additional API calls within `sfizz` to handle these cases. You mention a bindings language and this may be a better place for this type of code to live, as a "translation" layer. A loop like you made should be vectorized by compilers most of the time, but if you want to squeeze out stuff for sure on SSE platforms you can use [this function body](https://github.com/sfztools/sfizz/blob/a9d358d77400134bf0b4dd624d32930aaa78250e/src/sfizz/SIMDSSE.cpp#L93) with any adaption you'd need.

On a side note the stack allocation of buffers is 256 kB, which is sizable although afaik the default stack on most OS should be around 1 MB.

**Comment by spongeboburu** [comment]
Yes, you are probably right. Instead of forking I could make sfizz a submodule, build my additional code and link statically with sfizz to expose all the symbols.
