### ISSUE TITLE
Handle information about the time and position possibly sent from a host

### ISSUE THREAD

**Issue by paulfd** [sfztools/sfizz#314]
This ability will be required e.g. for [sync_beats](https://sfzformat.com/opcodes/sync_beats) or [delay_beats](https://sfzformat.com/opcodes/delay_beats.html). From the frontend PoV it has to link to [LV2 Time](http://lv2plug.in/ns/ext/time), JACK master clock or [VST3 PPQ position](https://steinbergmedia.github.io/vst3_doc/vstinterfaces/structSteinberg_1_1Vst_1_1Event.html#a5da7304404b66954c04f2c61242b4336).

See also #311

**Comment by jpcima** [comment]
In LV2 it can have some complication, I suggest referring to DPF.
https://github.com/DISTRHO/DPF/blob/fb3cd6372592f37b064f770adfccc02dead5f1ae/distrho/src/DistrhoPluginLV2.cpp#L335

What's the behavior when host stops the playback?
is one supposed to pass a 0 to the tempo API of sfizz?

**Comment by paulfd** [comment]
I... guess?

Although I would expect the host to just stop calling the render function in this case?

**Comment by paulfd** [comment]
I need a way to move this button....

**Comment by jpcima** [comment]
For the `delay` effect it needs to receive BBT info.
It has syncing functions which trigger an advance of the delay every N beats.
There are also `*_beats` opcodes in regular SFZv2.

**Comment by paulfd** [comment]
I'm closing this since the API accommodates it now. It's more a matter of implementing opcodes that use it, and we can track this separately.
