### ISSUE TITLE
Voice cout as LV2 control output

### ISSUE THREAD

**Issue by falkTX** [sfztools/sfizz#318]
I find having access to this information extremely useful, as it allows me to know how heavy I am pushing the sampler. If the value reaches the voice limit, then I would know I likely have to increase it.

**Comment by paulfd** [comment]
I'll check it out ! The introspection is there as a debug tool for development, also with memory information.

**Comment by alcomposer** [comment]
From a user POV, having such information displayed in a top panel element would be very useful.

While it may be thought of as information overload, it is very helpful for the end user, especially for live performance, where a balance between resources and polyphony would need to be managed by the performer.

Kontakt displays both voice count, cache usage, and current max polyphony in the generic header (which is visible regardless of custom GUI)
