### ISSUE TITLE
0.4.0 source tarball missing

### ISSUE THREAD

**Issue by dvzrv** [sfztools/sfizz#332]
Hi! I package sfizz for Arch Linux.
In the past I could rely on the combined source tarballs as release assets (which include the submodules).
The standard github auto-generated release tarballs based on the tags do not have the git submodule sources included (which are required for sfizz and for sfizz vst3).

**Comment by jpcima** [comment]
Fixed now. It's a problem of a bad deployment which was already creating trouble in the previous release.
Now it should be as usual.

**Comment by dvzrv** [comment]
Cool, thanks!
