### ISSUE TITLE
Adding end=-1 or ampeg_sustain=0 to *silence region make the voice not counted

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#365]
Adding `end=-1` or `ampeg_sustain=0` to a wav or flac file cause the region not played and the voice also not counted (0).

This should be also behave the same for `*silence` region. At this moment, the voice still counted. So for some usage combination with `on_lo/hiccN`, the voices of the `*silence` region will get stuck and never released.

Maybe also for other `*sample`, like the `*sine` `*saw` etc...

**Comment by kinwie** [comment]
This behavior also valid in DropZone, the *silence region with `end=-1` or `ampeg_sustain=0` will have zero voice count.
```
<region>
sample=crash.wav
key=48
loop_mode=one_shot
group=1
off_by=2

<region>
sample=*silence
key=50
end=-1
group=2
```
or
```
<region>
sample=crash.wav
key=48
loop_mode=one_shot
group=1
off_by=2

<region>
sample=*silence
key=50
ampeg_sustain=0
group=2
```
Pressing key 50, the voice is not counted, 0, but it still play and will mute key 48

![Untitled](https://user-images.githubusercontent.com/65444898/90554670-6b656900-e1c0-11ea-8ab3-deec54d3bf5d.jpg)

**Comment by paulfd** [comment]
Is it only `sustain=0`, not `attack=0` and `decay=0` and `hold=0`?

**Comment by kinwie** [comment]
Yes, rechecked this, it is `ampeg_sustain=0` only. Other `ampeg_xxx` won't cause this specific behavior

**Comment by paulfd** [comment]
Actually the voice is not really disabled. For example if you use
```
<region> sample=*sine ampeg_sustain=0 ampeg_attack=0.1 ampeg_decay=0.1
```
you hear a small boop and the voice indeed dies. What I did in #380 was that regions with `ampeg_sustain` set to 0 are free-running, much like `loop_mode=one_shot`. This way, the region is instantly killed off after the early envelope stages are done.

**Comment by kinwie** [comment]
Yes correct. For any wave with `ampeg_sustain=0` still produce very small boop sound, yet the polyphony voice will be uncounted. And for *silence, there won't be any boop, right? As it is contain no signal at all

**Comment by paulfd** [comment]
Yes. This should be the behavior with #380.
