### ISSUE TITLE
Request to reduce main volume to -3 or -4 or -6 dB

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#367]
Some sfz instruments with normalized samples clipped the DAW track when just load and play with current default volume at 0 dB

**Comment by jpcima** [comment]
>reduce main volume to -3 or -4 or -6 dB

No, the volumes should just match to ARIA at 0dB.
I noticed sometimes that there were a few differences, although without researching any further.
Do you have particular examples we can look at?

**Comment by kinwie** [comment]
I mean not internally, but at the volume parameter. In Aria, by just loading an inst. will make the volume set to -4 dB

**Comment by kinwie** [comment]
To match Aria's default volume output a bit more precise (which default at -4 dB, CC7 value 96), i have to set sfizz volume at approx. -1.5 dB

*I think Aria has internal volume reduced by -3 dB, but not sure the exact number. Or maybe that's the pan law value...hmm

**Comment by kinwie** [comment]
This unmatched volume between sfizz, sforzando and rgc sfz also affected by the different amp_veltrack curve

**Comment by paulfd** [comment]
@kinwie now that @jpcima fixed the amp_velcurve, is the base volume still bad? I've indeed seen sforzando set the UI volume to -4 or -6 by default, but I don't know if it's a UI trick or a real thing.

**Comment by jpcima** [comment]
According to some observations, I believe following steps will fix the problem.
- leave the global volume parameter set to 0 dB
- CC7 connected to amplitude, and default controller value set to 100
  this is the equivalent of -4.15.. dB according to General MIDI documentation (`L(dB)=40 log10(V/127)`)
  (note: also connect pan CC10 while at it)
- increase oscillator amplitudes, `*sine` and friends, by +4.15.. dB
  (these were adjusted to ARIA manually, but it needs to boost them to compensate for CC7)
