### ISSUE TITLE
Release Trigger adjustment

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#372]
Current sfizz release trigger have some disadvantages.
These are what I think may need to be adjusted :

1. Sfz specs default behavior: By setting trigger to `release` or `release_key` will automatically set the region into one-shot mode.
_*Current state in sfizz : It is not and we need to put ampeg_hold= or ampeg_release= with high value to make the release region play, which is no needed if it automatically put into loop_mode=one_shot._

2. Playing notes with sustain pedal down (especially repeated notes) then release the pedal, need `note_polyphony=1` to limit each released notes to 1 voice per key.
_*Current state in sfizz :_
- note_polyphony not yet recognized by the release regions, so for example, with sustain pedal down, playing fast 10 notes of the same key, then release the pedal, all 10 released notes will play. It should be limited follow the note_polyphony value.
- off_time not yet working properly. Sfizz default to off_mode=normal and depends on the ampeg_release value for the attack region's fade-out time, so we can't set different fade-out time independently. This can be an issue for the high undampened piano keys which have long release time, but to have a shorter off_time (In Aria, this is set to off_mode=time by default).

3. Adding `note_polyphony=1` will also cause both the attack and release regions of the same key, muting each other (bi-directional). This is the default behavior with no `group=` set (both attack and release regions are in the same `group=`)
_*Current state in sfizz : release region can't get muted by the attack region because the use of long ampeg_release value for it to play_

Point #3 could be just gone if #2 fixed

**Comment by kinwie** [comment]
This simply will just works in both DropZone and sforzando :
```
<group> note_polyphony=1
<region> sample=sine.wav
<region> sample=saw.wav trigger=release
```
Both will mute each other (per key) in both pedal up and pedal down

**Comment by paulfd** [comment]
I have yet to consolidate the polyphony logic to note-off and cc-triggered values, so points 2 and 3 are expected in a way ;-)

For the first point it's a valid remark. We do take into account the amplitude envelop for release voices, so you can actually do
```
<region> trigger=release_key sample=*sine ampeg_attack=0.02 ampeg_release=0.1
```
In sforzando afair this generates an inifinite sine wave.

**Comment by kinwie** [comment]
Yes, as the `note_polyphony` was just fixed last week, I'm also guessing that not yet put into release trigger.

Yes, `ampeg_attack` `ampeg_hold` `ampeg_decay` `ampeg_sustain` should works  for release trigger. Only `ampeg_release` is ignored.

**Comment by kinwie** [comment]
But If you want to extend the current sfz behavior, so the release region can also have AHDS for shaping the sample, it will be an extra feature in sfizz. And it's in the same direction as normal `loop_mode=one_shot` behavior, where we can apply `ampeg_attack` ampeg_hold` `ampeg_decay` and `ampeg_sustain` for it.

**Comment by paulfd** [comment]
For 1., do you have a reference? If yes, is it somewhere on sfzformat?

**Comment by paulfd** [comment]
>     1. __
> 
>     2. Playing notes with sustain pedal down (especially repeated notes) then release the pedal, need `note_polyphony=1` to limit each released notes to 1 voice per key.
>        _*Current state in sfizz :_

Yes, this was changed because it seemed to me that sforzando actually stacked the release samples. Can you check the volume of the sine wave on release when using and playing multiple notes?
```
<region> sample=*saw
<region> trigger=release sample=*sine 
```

> 
> 
>     * note_polyphony not yet recognized by the release regions, so for example, with sustain pedal down, playing fast 10 notes of the same key, then release the pedal, all 10 released notes will play. It should be limited follow the note_polyphony value.
> 
>     * off_time not yet working properly. Sfizz default to off_mode=normal and depends on the ampeg_release value for the attack region's fade-out time, so we can't set different fade-out time independently. This can be an issue for the high undampened piano keys which have long release time, but to have a shorter off_time (In Aria, this is set to off_mode=time by default).

`off_mode` actually defaults to `fast`, which should be the same as the default `off_time` in ARIA. If you set `off_time` explicitely it will also switch the region to `off_mode=time`. I changed this in the last PR but maybe it doesn't work properly?

> 
> 
>     1. Adding `note_polyphony=1` will also cause both the attack and release regions of the same key, muting each other (bi-directional). This is the default behavior with no `group=` set (both attack and release regions are in the same `group=`)
>        _*Current state in sfizz : release region can't get muted by the attack region because the use of long ampeg_release value for it to play_

Your example here would be 
```
<group> note_polyphony=1
<region> key=60 sample=*saw
<region> key=60 trigger=release sample=*sine
```
?

Also, which may explain the behavior you experience, sfizz does not steal released voices, nor do they count in the note polyphony.

**Comment by kinwie** [comment]
`For 1., do you have a reference? If yes, is it somewhere on sfzformat?`
Yes, it is documented in here :
https://sfzformat.com/opcodes/loop_mode

**Comment by paulfd** [comment]
Ok this one (1.) is fixed in #379 

For the rest we can tweak it, I'll wait for your feedback on the number of release voices triggering, but I guess a core issue is just that there is no polyphony checks on note-off and cc events yet.

**Comment by kinwie** [comment]
`Yes, this was changed because it seemed to me that sforzando actually stacked the release samples. Can you check the volume of the sine wave on release when using and playing multiple notes?`
The volume of sine wave will get louder because it keep stacked. Same behavior in both sforzando and DropZone

`off_mode actually defaults to fast, which should be the same as the default off_time in ARIA. If you set off_time explicitely it will also switch the region to off_mode=time. I changed this in the last PR but maybe it doesn't work properly?`
*edited : `off_time` works

**Comment by kinwie** [comment]
edited : off_time doesn't works for both the attack and release region. It default to off_mode=normal. Just adding ampeg_release to attack region, will modify the fade-out time

**Comment by kinwie** [comment]
Another test prove that `off_time` works by default.
Sorry, too many tests drained my brain :))

**Comment by kinwie** [comment]
`For the rest we can tweak it, I'll wait for your feedback on the number of release voices triggering, but I guess a core issue is just that there is no polyphony checks on note-off and cc events yet.`

All players behave the same including sfizz. with pedal down, all release triggered voices will be hold and then released when pedal up, as long as its correspond attack note is still active (behavior of rt_dead=off). So, `note_polyphony` will solved this issue
