### ISSUE TITLE
Noise print or denormal occur when ampeg_release not reached

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#373]
When the ampeg_release stage not yet reached and the region ends, sfizz produce some kind of noise print of denormal after it.

**Comment by paulfd** [comment]
There should be no denormals, so it might be noise or garbage. Do you have a test case?

**Comment by kinwie** [comment]
Yes, tempo 120 bpm
```
<region>
sample=*sine
ampeg_attack=1
ampeg_hold=1
ampeg_decay=1
ampeg_sustain=0
ampeg_release=1
```

Draw one bar midi note, so it reach the release stage, no noise :
![Untitled](https://user-images.githubusercontent.com/65444898/90631022-3c94d480-e24c-11ea-85b0-1145c1d0ad1c.jpg)

Draw two bars note, it's not reach the release stage, there is noise after it (it should ends in the 2nd bar, 3rd beat, like first image) :
![Untitled2](https://user-images.githubusercontent.com/65444898/90631306-b5942c00-e24c-11ea-8b38-598e6836843b.jpg)

This seems only occur when the ampeg_sustain value is 0

**Comment by paulfd** [comment]
Was this one improved this summer?

**Comment by jpcima** [comment]
It's because we cut the envelope release at -60 dB.
You can lessen it by aiming at -80 dB.
If we rewrite the ADSR entirely in curves, there is no more need to take care of this asymptotic behavior.
(but then unnatural behavior on level/time dynamic updates. it's the ARIA behavior)

**Comment by paulfd** [comment]
I think it could make sense to have the ampeg as a FlexEG too, if only to have a single codepath to check and optimize for all this.

**Comment by paulfd** [comment]
@kinwie does this still happen? I have trouble seeing it on Reaper

**Comment by kinwie** [comment]
@paulfd Using same example case as above, the release is cut shorter (sfizz - DropZone - sforzando)
![Untitled](https://user-images.githubusercontent.com/65444898/112020608-0feac780-8b63-11eb-80c2-1272eb1292ec.png)

**Comment by jpcima** [comment]
A simple solution is to add a final phase that finishes the envelope in linear.
