### ISSUE TITLE
Support sw_lolast & sw_hilast

### ISSUE THREAD

**Issue by AlexMitchellMus** [sfztools/sfizz#389]
For sfizz to support the ARIA opcodes:

* `sw_lolast`
* `sw_hilast`

Documented: https://sfzformat.com/opcodes/sw_hilast.html

**Comment by paulfd** [comment]
Ok let's try to solve this for the next release, along with #423

**Comment by paulfd** [comment]
Note that if `sw_lolast/hilast` is present in a region, `sw_last` is ignored in sforzando.
