### ISSUE TITLE
Clicks when no ampeg_release

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#392]
While testing some sfz v1 organ presets which has no ampeg setting at all, I encountered clicks sound.
This seems cause by sfizz initial ampeg_release value.
Adding `ampeg_release=0.0001` solved the click noises.
This clicks sound doesn't appear in other players. So I suggest to add a very short value for initial ampeg-release

Simple example can prove this case :
```
<region>
sample=*sine
```
This will sound smoother in sforzando and DropZone

**Comment by AlexMitchellMus** [comment]
This is a good simple suggestion.

If a user wanted the clicks, then add `ampeg_attack=0` etc.

**Comment by kinwie** [comment]
@alcomposer Maybe you mean `ampeg_release=0`?

**Comment by paulfd** [comment]
Do you have any idea of the value used e.g. by sforzando? 0.0001?

**Comment by kinwie** [comment]
> 
> 
> Do you have any idea of the value used e.g. by sforzando? 0.0001?

I made a comparison of 4 with images below (in order: sfizz, DropZone, RGC, sforzando) and image cut at the note-off point :

- With just `<region> sample=sine60.wav`
![Untitled](https://user-images.githubusercontent.com/65444898/93984033-82920a80-fdad-11ea-95a2-140354f21ff8.jpg)

- Adding `<region> sample=sine60.wav ampeg_release=0.001` seems to match enough three of them :
![Untitled2](https://user-images.githubusercontent.com/65444898/93984169-ac4b3180-fdad-11ea-9a65-0132264b8b58.jpg)

**Comment by paulfd** [comment]
Thanks alot @kinwie :) I'll get to it.
