### ISSUE TITLE
Click/transient disappear because of initial attack

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#394]
sfizz seems to have a small initial ampeg-attack value by default. This will cause the sound less punchier comparing to rgc sfz and sforzando. I include a test file to demonstrate this issue for quicker check
[attack_transient_check.zip](https://github.com/sfztools/sfizz/files/5135313/attack_transient_check.zip)

**Comment by paulfd** [comment]
Is this still a problem? Note that on a single smallish transient like this the sample rate and interpolation method plays a massive role, so if you want the full transient to appear the rates need to be properly matched.

I added a second transient at the beginning and compared the outputs with sforzando, and it looks okay !

![Screenshot from 2020-09-23 14-21-32](https://user-images.githubusercontent.com/15227713/94014217-8755bf00-fdab-11ea-99e4-a58197000741.png)

**Comment by kinwie** [comment]
Well yeah. I just test like you said, I move the transient one sample behind and the click sounded.
But I think it's not quite pretty solution as lot of samples are edited/trimmed with high transient from very beginning.
It's quite impossible to instruct users to re-edit the samples to get the full attack sounds.
I've also checked this behavior in Kontakt and it's start purely from zero also.
But well, if that means also adjusting the sample rate/interpolation, I don't know what to say :D

**Comment by paulfd** [comment]
I mean I have exactly the same, I just put a second transient to check if this was some resampling trick or something.
![Screenshot from 2020-09-23 15-47-29](https://user-images.githubusercontent.com/15227713/94021327-2e3e5900-fdb4-11ea-83f6-01374683ef59.png)

**Comment by kinwie** [comment]
I have no idea :D`
But maybe this also cause the issue #395 ?
Seems like the offset is set +1 value in sfizz?
Btw, DropZone also behave like this :))

**Comment by paulfd** [comment]
OK the offset might impact. Another thing is that in order to have some buffer for interpolation algorithms, we fill some pre- and post-buffer with zeros assuming this is how samples start and end, which is not the case here. This could also explain partly why such a transient is dampened by interpolation algorithms.

I'll push this for later, #395 seems like the most pressing issue on this front and you're right it might also solve this one.
