### ISSUE TITLE
Keyboard display in GUI

### ISSUE THREAD

**Issue by alcomposer** [sfztools/sfizz#402]
There needs to be a keyboard display in sfizz GUI.

This is important to be able to:
* Clearly see current range of regions
* Keys set to keyswitch
* Currently played MIDI notes
* Rudimentary Virtual Keyboard (mouse over key, and press key to trigger output)

Here is a mock-up of what the keyboard _could_ look like, I have placed the keyswitch indicators above the keys, as a keyswitch can be inside a region. I have used colour to indicate current region, but we may want to think about greying out notes outside of regions?
![keyboard_with_keyswitch](https://user-images.githubusercontent.com/12004932/92301886-8862b000-efa6-11ea-9481-d4a67d83eaf9.png)
Middle C4 has a dot positioned under. This keyboard is designed to aid users in understanding what the SFZ Script is capable of- not for playability with the mouse. In which case a Virtual Keyboard that allows Musical Typing would be better equiped to handle.
Having the keyboard full range 0-127 allows consistency between SFZ Scripts, and simplifies the GUI display - as there is no need to include up/down octave UI elements.

**Comment by alcomposer** [comment]
A simpler design, not using colour (as it will be almost impossible to show multiple regions at same time, as regions can overlap)

NOTES:
* Top dots denote keyswitches, with current active switch taller
* Dots inside key represents notes that are played, either via MIDI or mouse
* Bottom line indicates current keyswitch range
* Mouse interaction would lock to key area on LMB, velocity of note set to 64, moving mouse on Y axis changes velocity of new notes. (Movement exceeds the vertical size of the key area)

![keyboard_mockup_3](https://user-images.githubusercontent.com/12004932/92327545-96ddc400-f099-11ea-8131-e6815461f4b3.png)

**Comment by paulfd** [comment]
I like II C :D I think color-coding only the keyswitches could make sense?

**Comment by alcomposer** [comment]
SFZ can have 128 keyswitches, so its quite a bit to colour code.

**Comment by jpcima** [comment]
Is it bad that colors would repeat?

**Comment by alcomposer** [comment]
@jpcima no, not at all. But we may want to allow a few settings:

* Mono (dark colour)
* Custom palette

**Comment by alcomposer** [comment]
Mixing B + C with colour, and changed the keyswitches to sticks.

![keyboard_sfizz_6](https://user-images.githubusercontent.com/12004932/92332508-8fc8ad00-f0bd-11ea-94b5-9b0631d73de5.png)

**Comment by paulfd** [comment]
The rainbow is a bit distracting while not really carrying relevant information I think. Coloring the key switches directly on the keyboard also has an advantage in terms of compactness.

**Comment by alcomposer** [comment]
![keyboard_sfizz_7](https://user-images.githubusercontent.com/12004932/92346383-c1686500-f10b-11ea-9db0-4859cfc51593.png)

**Comment by alcomposer** [comment]
## G inverted
This design inverts the use of range->keyswitch display. Hence dark notes (previous keyswitch) can be used to display key range.
![keyboard_concept_9](https://user-images.githubusercontent.com/12004932/92435825-68b7cb80-f1e2-11ea-835e-2d8e49a2f807.png)

**Comment by alcomposer** [comment]
## G inverted keyswitch examples:
Keyswitch inside range (active switch is playable inside range- other switch is grey, as it changes the region played)
![keyboard_sfizz_9_mixed_keyswitch](https://user-images.githubusercontent.com/12004932/92550975-133ff500-f29c-11ea-91dc-72df218f7e9c.png)
White notes of octave showing keyswitches:
![keyboard_sfizz_9_white_note_keyswitch](https://user-images.githubusercontent.com/12004932/92550977-14712200-f29c-11ea-902b-2f18bc5614a3.png)

**Comment by alcomposer** [comment]
## F Traditional Keyboard, with keyswitch bar on top.
![traditional_keyboard_hybrid](https://user-images.githubusercontent.com/12004932/92556716-c6fbb180-f2a9-11ea-8240-e00fe009326a.png)

**Comment by kinwie** [comment]
If using bar, the keyswitch displayed like a range. While keyswith can only on white keys or only on black keys or adjacten keys. It's a litte bit im-flexible imo

**Comment by alcomposer** [comment]
![traditional_keyboard_hybrid_3](https://user-images.githubusercontent.com/12004932/92559025-ef39df00-f2ae-11ea-857c-3a75608a7328.png)

**Comment by paulfd** [comment]
> If using bar, the keyswitch displayed like a range. While keyswith can only on white keys or only on black keys or adjacten keys. It's a litte bit im-flexible imo

This depends if we're only considering the individual `sw_last`, `sw_up`, ... or the actual keyswitch range `sw_lokey` and `sw_hikey`

**Comment by alcomposer** [comment]
Top of keybed with 'felt'
![traditional_keyboard_hybrid_6](https://user-images.githubusercontent.com/12004932/92571888-d6d3bf80-f2c2-11ea-8730-b617adb31852.png)

**Comment by alcomposer** [comment]
## L
![Multi_KS_Tri_Keyboard_v2](https://user-images.githubusercontent.com/12004932/92718167-9c405480-f3a0-11ea-9646-eddc8e2cb7cb.png)

Multi-Keyswitch keyboard, Down triangle signifies active keyswitch. (multiple active keyswitches to illustrate readability)

**Comment by alcomposer** [comment]
## N
* Unused keys are grey
* `sw_last` has a paddle, which also shows active switch state
* `sw_last` keys are also coloured with switch colour
* `sw_down` keys are coloured- but have no top paddle (they are momentary)

![keyswitch_colour_in_key_light_kslast ksdown_v2](https://user-images.githubusercontent.com/12004932/92882278-eb44c300-f44e-11ea-9775-70317e94a1b5.png)

**Comment by alcomposer** [comment]
Current GUI design iteration:
![UI_Keyboard_gradient_default_v9](https://user-images.githubusercontent.com/12004932/93305369-908bdc80-f83d-11ea-82b5-316f10e5cc45.png)

**Comment by alcomposer** [comment]
Continued in #418
