### ISSUE TITLE
CC Rotary Control Design

### ISSUE THREAD

**Issue by alcomposer** [sfztools/sfizz#403]
sfizz needs a way of displaying rotary knobs, this is a simple knob design, that shows both a label, ccN, and value.
![pan_knob](https://user-images.githubusercontent.com/12004932/92301935-fad39000-efa6-11ea-90eb-673d8b81c6be.png)
It can be modified to be a `pan` (bi-polar), or `volume` rotary knob.

**Comment by kinwie** [comment]
I may suggest, for easier read, the CC number displays without the leading zeros, so just e.g. CC 7 or CC 35.
For the value's curve, yes it will be great to have Linear (0 to 100%) and Bipolar (-100% to 0 to +100%). If possible, I also suggest to add another one, Inverted Linear (-100% to 0). It can be useful for e.g. offset_onnccN control

**Comment by kinwie** [comment]
The next question is,
At which level this control type need to be defined?
Is it at player-level (exclusive to sfizz UI)?
Or with opcodes inside the sfz file.

If from the sfz file, maybe new opcodes for it need to be added, like :
```
<control>
label_cc7=Pan
set_realcc7=0.5
display_cc7=bipolar
```

**Comment by kinwie** [comment]
@alcomposer 
From the example image, since it going to have the rotary value bar displayed as well, I think we don't need the % sign. So just 0 to 100,
or -100 to +100, etc..

**Comment by kinwie** [comment]
If more precision can be added, maybe having decimal point value will be nice and useful, like 50.2 or 50.28
