### ISSUE TITLE
Ubuntu 20.04 Focal Fossa Build Dependencies

### ISSUE THREAD

**Issue by josephbburg** [sfztools/sfizz#406]
In order to successfully configure the cmake files for sfizz, I had to install more dependencies than https://sfz.tools/sfizz/development/build/linux lists. 
In all, I needed `libxcb-utils-dev` `libxcb-cursor-dev` `libxcb-keysyms1-dev` `lib-xkb-dev` `libxkbcommon-x11-dev` to succesfully configure the Cmake file (step 4, `cmake ..`).
After that, it succesfully built with `make` and `sudo make install`. Worked perfectly in Ardour 6.3.

This guthub issue is simply: please update the documentation :)

**Comment by jpcima** [comment]
Hi, I'll add it to the list thanks.
Note that future versions will also add `libglib2.0-dev` as a requirement.
