### ISSUE TITLE
The file open GUI does not open in Ardour 6.2

### ISSUE THREAD

**Issue by paulfd** [sfztools/sfizz#416]
- OS: Ubuntu Linux 20.04
- sfizz version: develop branch with LV2 UI

Upon opening the UI and clicking to open a file, nothing happens.

Zenity apparently can not launch and produces the following message:
```
/usr/bin/zenity: symbol lookup error: /lib/x86_64-linux-gnu/libsecret-1.so.0: undefined symbol: g_input_stream_read_all_finish
```

It seems linked/similar to https://github.com/surge-synthesizer/surge/issues/2455

**Comment by falkTX** [comment]
Seems like ardour needs to provide zenity.

Alternatively, at least for lv2, you can use the request-file feature to get a native file browser from the host.
See https://github.com/lv2/lv2/commit/c11adc705f7028eeff2e8fcd6cbf6b9d5ee97206

You can also see what the host does with this in https://github.com/drobilla/jalv/commit/74c4c4d9badcd6ffc452baf8bea5530f44e95b4d

**Comment by x42** [comment]
If you have to rely on external apps and fork external apps, use a wrapper and unset `LD_LIBRARY_PATH`
like https://www.kvraudio.com/forum/viewtopic.php?f=31&t=424953&start=975

But then please use vfork  like
https://github.com/sadko4u/lsp-plugins/issues/54
https://github.com/surge-synthesizer/surge/issues/657

Then again zenity may not even be installed, so @falkTX suggestion to use LV2's
http://lv2plug.in/ns/extensions/ui#requestValue

**Comment by x42** [comment]
To elaborate `zenity` is a gtk3 application, while Ardour is a gtk2 app and binaries from ardour.org come with gtk2 that's in `LD_LIBRARY_PATH`.

A quick/dirty solution:  add `/usr/local/bin/zenity`

```bash
#!/bin/sh
unset LD_LIBRARY_PATH;
exec /usr/bin/zenity "$@"
```

**Comment by paulfd** [comment]
Hi, thanks for the solution, that's what I got from the surge discussion so this was more for tracking the problem. The key underlying issue is that we're dependent on vstgui's call for the file search. The LV2 extension could be hacked into which would solve this from the LV2 point of view, but this would not prevent the error on the VST plugin loaded in Ardour. We already forked vstgui so we can patch it (again?) :slightly_smiling_face: 

Thanks for the pointers!

**Comment by jpcima** [comment]
I'll hack this into vstgui.. anyway, steinberg's present implementation is bad.
Strings go into a popen command without escaping, which provides all kinds of amazing shell command injection abilities.
So it's a perfect occasion to rewrite this without the security problems.
Is it fine to go with `posix_spawn` instead of `vfork`? I must already have this code somewhere around.

**Comment by x42** [comment]
> Is it fine to go with posix_spawn instead of vfork?

Probably. `posix_spawn` is implemented as glibc function, while `vfork` is a syscall.

**Comment by x42** [comment]
PS. Carla does not allow plugins to call `fork` or `posix_spawn` or other non rt-safe means to launch child apps.

This is prevented by overriding global symbols:
https://github.com/falkTX/Carla/blob/321d2670c38d733bfe6ad085fb16359d377d913e/source/interposer/interposer-safe.cpp#L37-L66

**Comment by jpcima** [comment]
>PS. Carla does not allow plugins to call fork or posix_spawn or other non rt-safe means to launch child apps.

This is curious, our UI currently has `posix_spawn`, and it runs in Carla without issue.
(anyway I'm rewriting this to `vfork` soon, and submitting this to the vstgui upstream)

**Comment by falkTX** [comment]
> PS. Carla does not allow plugins to call `fork` or `posix_spawn` or other non rt-safe means to launch child apps.

these overrides are opt-in, not enabled by default (yet)

**Comment by jpcima** [comment]
done, for reference the vfork PR has been posted at
https://github.com/steinbergmedia/vstgui/pull/159
