### ISSUE TITLE
Not yet working sfz v1 opcodes

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#432]
These opcodes not yet working in sfizz :

- [x] `count`
- [x] `delay_ccN` or `delay_onccN`
- [x] `sw_previous`
- [x] `sw_vel`

**Comment by paulfd** [comment]
`count` does not work?

**Comment by kinwie** [comment]
No it' s not working

**Comment by kinwie** [comment]
Checked, the `sw_previous` now already works :+1:

**Comment by kinwie** [comment]
A bit strange that `sw_vel` never implemented either in rgc sfz nor Cakewalk players.
ARIA implemented it by taking only previous velocity value and apply it as amp_veltrack value (modifying only the volume) to the regions that have `sw_vel` defined, and this could raise an undesired volume changes when the regions are multi-velocities samples, which, a low and soft velocity sample can be triggered with much louder volume (and the opposite, high and hard velocity sample triggered  with much lower volume).

E.g. :
```
<group>
loop_mode=one_shot
key=60
sw_vel=previous

<region> sample=snare_p.wav hivel=31
<region> sample=snare_mp.wav lovel=32 hivel=63
<region> sample=snare_f.wav lovel=64 hivel=95
<region> sample=snare_ff.wav lovel=96
```
_In ARIA, possibly, snare_p could be played at loud volume or snare_ff could be played at low volume, which is then can sounded undesired_

**Comment by kinwie** [comment]
Okay, I finally figure out how `sw_vel` works in rgc sfz.
`sw_vel=previous` only works when `sw_previous` opcode is present.
While it's working in Cakewalk DropZone, it has a little bug in DZ (I suspect it is).

So, `sw_vel=previous` in rgc sfz works like I expected.
It will trigger the region using previous velocity value (not only modifying the volume).
So from above example, when a previous note is at vel 25 and current note at vel 100, the "snare_p" will play, and at vel 25 volume.

The conclusion i think is,
`sw_vel` always need `sw_previous` in rgc sfz, but not in ARIA
And Aria implementation is only modifying the volume by previous velocity value

**Comment by tseaver** [comment]
The V1 opcodes [`lochan` and `hichan`](https://sfzformat.com/opcodes/hichan) are [unimplemented / ignored](https://github.com/sfztools/sfizz/blob/cbcc875aef05ca161a962e0e529c38ae149ffc45/src/sfizz/Region.cpp#L1420).  I would find them useful in setting up articulation-per-channel mappings for e.g. orchestral samples (e.g., a sustain patch on channel 1, a stacatto patch on channel 2, a pizzicato patch on channel 3, etc.).

**Comment by paulfd** [comment]
They're purposefully ignored right now actually, which was an early design decision. @jpcima proposed to lift it; we have to check whether the potential gain warrants the additional complexity this might introduce.

The workaround for this is to do midi routing outside of the sfizz library/plugin, so that you'd have one sfizz instance per patch.

**Comment by jpcima** [comment]
I'm interested to find at first the way how cakewalk handles this, which should be telling of what complexity such a system needs.
I have noted unfortunately, that CC parameters lose the channel information in VST3, which is our primary platform for plugins.

**Comment by kinwie** [comment]
@paulfd 
Checked, the last change for `sw_vel` works just perfect! Both fil_veltrack and pitch_veltrack also applied. Superb!!

**Comment by kinwie** [comment]
Checked, both `delay_ccN` and `delay_onccN` works just fine :+1:

**Comment by kinwie** [comment]
Tested, `count` is working as expected, thank you @paulfd
