### ISSUE TITLE
Incorrect vst3 architecture folder on armhf systems (armv7l → armv7hl)

### ISSUE THREAD

**Issue by x42** [sfztools/sfizz#442]
First the good news. I managed to build the VST3 in a Raspberry Pi load it in Ardour 6.3.92 and make some noise.

Since this is an ARM processor and OS with hard-float support (armhf in debian), I had to rename the plugin's arch:

```
cd ~/.vst3/sfizz.vst3/Contents/
mv armv7l-linux/ armv7hl-linux/ 
```

https://steinbergmedia.github.io/vst3_doc/vstinterfaces/vst3loc.html#linuxformat
specifies `based on the RPM Terminology + "-linux"``

RPM terminology for `armhf` is `armv7hl`  (not arm7l)

**Comment by jpcima** [comment]
Hi, the detection of the ARM architecture for VST was a contribution and somewhat basic.
We've not yet thought about a solution which covers all cases, however this name is allowed to be overriden in CMake.
for instance `-DVST3_PACKAGE_ARCHITECTURE=armv7hl`

**Comment by jpcima** [comment]
For reference, how Steinberg VST extracts Linux architecture.
https://github.com/steinbergmedia/vst3_cmake/blob/e454821efdb76ba410e65db01128050623c1bd7b/modules/AddSMTGLibrary.cmake#L166
