### ISSUE TITLE
polyphony not working with Maestro\ Concert\ Grand.sfz 

### ISSUE THREAD

**Issue by grammoboy2** [sfztools/sfizz#466]
polyphony not working with Maestro\ Concert\ Grand.sfz 

Build the latest git version develop branch

sfizz_jack
using mamba/ jack-keyboard virtual keyboards

**Comment by kinwie** [comment]
Hi, thanks for the report.
Indeed it doesn't play well in sfizz at the moment. This case is not polyphony issue, but the use of 2 `<global>` in Maestro Grand Piano.sfz. There are some other small cases too as sfizz keep added things to support all opcodes at its best. We will working on it

**Comment by kinwie** [comment]
Futher look in the Maestro sfz file, it seems the 2nd `<global>` that use `polyphony` opcode override the `note_polyphony` that used in the 1st `<global>`.
The workaround at the moment is, open Data/effect.txt. Change the opcode `polyphony=1` to `note_polyphony=1`

**Comment by kinwie** [comment]
@grammoboy2 Btw, is the Maestro Concert Grand.sfz you mean, is the one in here?
https://github.com/sfzinstruments/MatsHelgesson.MaestroConcertGrandPiano

**Comment by grammoboy2** [comment]
On 10/1/20 8:02 PM, kinwie wrote:
>
> @grammoboy2 <https://github.com/grammoboy2> Btw, is the Maestro 
> Concert Grand.sfz you mean, is the one in here?
> https://github.com/sfzinstruments/MatsHelgesson.MaestroConcertGrandPiano
>
Yes. It's not that I need it atm, but I stumbled upon it when fiddling 
around.
>
