### ISSUE TITLE
Extended CC

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#481]
https://sfzformat.com/extensions/midi_ccs

- [ ] 128: pitch bend, [-1:+1] per cycle
- [x] 129: channel aftertouch, ?
- [ ] 130: polyphonic aftertouch, ?
- [ ] 131: note on velocity, per voice [0:1]
- [ ] 132: note off velocity, ?
- [ ] 133: keyboard note number, per voice [0:1] normalized
- [ ] 134: keyboard note gate, per voice [0:1]
- [ ] 135: unipolar random, per cycle? [0:1]
- [ ] 136: bipolar random, per cycle? [-1:+1]
- [ ] 137: alternate, per cycle? [0:1]

**Comment by paulfd** [comment]
Channel aftertouch is in #630.

**Comment by kinwie** [comment]
I think 129 is per cycle and 130 is per voice?

**Comment by paulfd** [comment]
Ok I'm lost. What do we mean by per voice or per cycle here? Barring any normalization question, these should just be like CC sources no?

**Comment by AlexMitchellMus** [comment]
Hm, yeah, I think these extended CCs are in a sense a hack. Polyphonic aftertouch would have to be per-voice. As it's each key.

Otherwise there would be no difference between Channel or Poly.

**Comment by kinwie** [comment]
Tested CC 129 and seems it has an issue :
```
<region>
sample=snare.wav
loop_mode=one_shot
key=60
pitch_oncc129=1200
```

Sending Channel aftertouch (mono aftertouch) from my host didn't modulate the pitch :
![Untitled](https://user-images.githubusercontent.com/65444898/110680967-d8e3f000-820b-11eb-8207-1603ee8f0391.png)

But moving the CC 129 knob from UI does change the pitch.
Though, not sure if it's the kushview Element problem that it can't receive channel aftertouch message or not.
_(I use it to host VST3)_

**Comment by kinwie** [comment]
For sfz v1, CC 129 is `chanaft`
So, `locc129` and `hicc129` are alias to `lochanaft` and `hichanaft`
Using those also cause the CC 129 knob appeared at the UI in sforzando
