### ISSUE TITLE
veltrack_oncc additional opcodes

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#483]
To be able to control the "Veltrack" opcodes with CC is a flexible option, for example, for adjusting velocity response via GUI based on each piano player's hands strength/habit, and more other cases.
Currently ARIA support amp_veltrack_onccN
I also suggest to add the other two as well :
fil_veltrack_onccN and pitch_veltrack_onccN

- [ ] `amp_veltrack_onccN`
- [ ] `fil_veltrack_onccN`
- [ ] `pitch_veltrack_onccN`

**Comment by paulfd** [comment]
As a note there are actually curves attached to this it seems (i.e. `amp_veltrack_curveccN`) so I guess we could add all these at once.
