### ISSUE TITLE
MacOS build instructions

### ISSUE THREAD

**Issue by michaelwillis** [sfztools/sfizz#5]
Please include instructions about how to compile this on MacOS.

**Comment by redtide** [comment]
Hi Michael,
the macOS build is currently a work in progress due a recent issue, but you can find how we do it with Travis in the [script.sh](https://github.com/sfztools/sfizz/blob/master/.travis/script.sh) file:
```sh
cd sfizz
mkdir build && cd build
cmake -D SFIZZ_CLIENTS=ON -G Xcode ..
xcodebuild -project sfizz.xcodeproj -alltargets -configuration Debug build
```
Set SFIZZ_CLIENTS=OFF if you need to build the library only.
We don't own a mac, so this is unfortunately anything we can do ATM (other than remove temporarily the `macOS` bit in the Travis badge :disappointed:).

**Comment by michaelwillis** [comment]
Thanks, I was able to build it after commenting out `#include <intrin.h>` in `sfizz/atomicops.h`. Before that, it complained that it couldn't find `intrin.h`, but it built without it. I'm wondering if the `#if` preprocessor conditional before that isn't correct.

**Comment by paulfd** [comment]
This header should be more for Windows, it's weird that it gets included.

Hopefully I should get a Mac too try this out soon!

**Comment by redtide** [comment]
@paulfd The only include that gave me a build error before the other recent build issue was `arm_neon.h` in the [CMake build file](https://github.com/sfztools/sfizz/blob/master/sfizz/CMakeLists.txt#L15), you see both are included from there, maybe a matter of different toolchain configuration.

**Comment by paulfd** [comment]
Yes I was trying to cover different platforms and their intrinsics using Cmake checks for the proper files.

That said, I don't have access to a computer atm but atomicops.h is a file from moodycamels queue, not my intrinsics iirc.

**Comment by redtide** [comment]
Sorry for the delay, done in 02cb53e.
@michaelwillis please let us know if any problems related, closing this for now.

**Comment by michaelwillis** [comment]
@redtide I just confirmed that the MacOS build works! I was able to load the LV2 in Ardour and make some noise with it. Thanks a lot for this work, for a long time I've been hoping for enough cross-platform plugins to enable me to swap projects back and forth between my macbook and my linux music machine. I think an SFZ player that worked on both was the last one I needed.

**Comment by redtide** [comment]
Thank you, I miss the chance to test it with a complete environment, but you should thank Paul for the player code :-)

**Comment by michaelwillis** [comment]
Uhh, oops... Thanks @paulfd for all the work on this!

**Comment by hexdump0815** [comment]
just in case someone else comes across this while trying to build sfizz on macos: the current way to build it is different - see: https://github.com/sfztools/sfizz/blob/develop/.travis/script_osx.sh ... and maybe https://github.com/sfztools/sfizz/issues/270 in case you run into problems with that too ...

best wishes - hexdump

**Comment by redtide** [comment]
@hexdump0815 just updated [the page] accordingly to recent changes, thanks for the reports!

[the page]: https://sfz.tools/sfizz/development/build/macos

**Comment by hexdump0815** [comment]
cool - thanks for the info

best wishes - hexdump
