### ISSUE TITLE
Request: no configure-time detection

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#50]
I wish to eliminate the detection of features such as `HAVE_INTRIN_H`.

Usually, in gcc at least, there already exist some predefined macros which permit to detect CPU features without resorting to such checks.

If configure-time checks are gone, sfizz is more easily included from systems which do not use cmake.
For instance, DPF uses only GNU make, and I would like to provide some make module that plugin makers include to embed it easier into the plugin.

Also, in the part below, it's not advisable to override a user's flags with a fixed architecture.
It disables the ability of creating portable ARM packages.
(moreover I don't think -march=native and -mtune or -mfpu together to make sense)
```
    add_compile_options (-DHAVE_ARM_NEON_H)
    add_compile_options (-mfpu=neon)
    add_compile_options (-march=native)
    add_compile_options (-mtune=cortex-a53)
```

**Comment by paulfd** [comment]
Fine for me :+1:
