### ISSUE TITLE
Switch up the interpolation quality

### ISSUE THREAD

**Issue by paulfd** [sfztools/sfizz#504]
We should target to have Hermite or B-Spline by default. An issue at the moment is that for ARM builds there is no NEON codepath, and the interpolation was quite slow there.

**Comment by kinwie** [comment]
Yeah, I suspect this maybe can also solve that "transient' issue #394?

**Comment by paulfd** [comment]
#394 is mostly due to another "problem", which is that we assume that the start and end of samples are always 0, and we fill the "corner" values of the interpolation algorithms with 0. Regardless of the interpolation, this will require a change, probably filling the overflow buffers with the actual start and end value of the samples.

**Comment by kinwie** [comment]
@paulfd I see.. though I feel okay with linear's sound, but if we can have Hermite, of course it will be better, but of course also in regard of CPU usage :)

**Comment by ghost** [comment]
Linear sound is fine if you are using chromatic sampling but for whole-tone sampling and beyond, Hermite makes a huge difference to sound quality, IMHO.
