### ISSUE TITLE
Sfizz 0.5.0 crashing Reaper

### ISSUE THREAD

**Issue by lichoradka** [sfztools/sfizz#513]
I'm trying to use sfizz 0.5.0 with the program Reaper (Ver. 6.14/64) on a Mac, and whenever I try to use the plugin or even scan for it Reaper crashes.
Thanks in advance for any help!

**Comment by jpcima** [comment]
Hi @lichoradka , we're in the middle of fixing some important bugs that came up in this version, and hope to push a hotfix version 0.5.1 shortly.
If I can confirm your bug, I'll include the fix in the release.
Which version of macOS is it?

**Comment by lichoradka** [comment]
10.10.1 !
Thank you so much.

**Comment by jpcima** [comment]
Indeed the team has identified some issues running on Reaper macOS.
I believe we have it fixed in the dev branch, at least it works under virtualization.

I'm attaching a fresh build, do you mind to check it?
[sfizz-Issue-513.tar.gz](https://github.com/sfztools/sfizz/files/5412575/sfizz-Issue-513.tar.gz)

**Comment by lichoradka** [comment]
Thanks for the prompt response!
It certainly doesn't crash anymore, but reaper can't seem to find/recognize
the plugin at all now. I believe I have all the paths mapped correctly and
I've cleared the cache for the VST locator, etc. But nothing is popping up
even though the file is in the proper place.
It could be user error, but this is the same way I usually load plugins in
the program, and the other plugins I use are showing up fine.

**Comment by jpcima** [comment]
My bad, it appears I failed a step. This other must be ok.
[sfizz-Issue-513-bis.tar.gz](https://github.com/sfztools/sfizz/files/5413270/sfizz-Issue-513-bis.tar.gz)

**Comment by lichoradka** [comment]
this one works! Awesome. Thank you very much.
