### ISSUE TITLE
AU Plugin Knob has wrong mouse behaviour

### ISSUE THREAD

**Issue by alcomposer** [sfztools/sfizz#516]
Testing sfizz 0.5.0 in Logic Pro (AU Only) the behaviour of the knobs with mouse is rotary, not vertical.

See attached screencast.
![SFIZZ_KNOB_AU_LOGICPRO](https://user-images.githubusercontent.com/12004932/96669095-0b4b9880-13a4-11eb-91b0-488c35211258.gif)

**Comment by jpcima** [comment]
Link to an upstream issue regarding auwrapper
https://github.com/steinbergmedia/vst3_public_sdk/issues/18
