### ISSUE TITLE
Concurrency issue: crash on changing instrument

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#519]
The problem is as follows:
- change instrument
- the DSP invokes `FilePool::triggerGarbageCollection` on the old files
- some of these files are still streaming, their memory block is freed and they write invalid memory
- crash with [report.txt.gz](https://github.com/sfztools/sfizz/files/5420012/report.txt.gz)

very easily reproduced with a timer that changes loaded instrument every tick
[stress.patch.gz](https://github.com/sfztools/sfizz/files/5420016/stress.patch.gz)

It's difficult to find a quick fix to this one, it's more than tempting to revert the loader to pre-0.5.0.

**Comment by paulfd** [comment]
I'll have time tonight to look into this. I think the "nice" behavior in this case would actually be to keep the file and the voice streaming on instrument change to avoid sound cutoffs, but it probably will not be a simple machinery to implement.
