### ISSUE TITLE
note_polyphony=1 didn't mute on release trigger

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#529]
While adding `polyphony=1` did make the "attack" and "release" triggered regions muted/choke each other (bi-directional), there is an issue it won't choke when using `note_polyphony=1` instead.
A simple example :

```
//crash on attack
<group> key=60 note_polyphony=1
<region> sample=crash.wav loop_mode=one_shot
<region> sample=snare.wav trigger=release

//crash on release
<group> key=62 note_polyphony=1
<region> sample=snare.wav loop_mode=one_shot
<region> sample=crash.wav trigger=release
```

**Comment by paulfd** [comment]
`note_polyphony` uses a separate code_path, I guess I'll get on it ;)

**Comment by kinwie** [comment]
@paulfd Nice, thanks

**Comment by paulfd** [comment]
Right now attack regions and release regions are checked separately for `note_polyphony`. We should have release regions potentially mask out attack regions then?

**Comment by kinwie** [comment]
@paulfd Yes and vice versa
