### ISSUE TITLE
width/position inverted in stereo case?

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#54]
In the stereo output, it appears as if width and position are mixed.

- width: a cross-channel mixing value, default 100% = no mixing
- position: the panning value, default 50% = middle

Below is mono position, vs. stereo width: a similar computation.

It suggests position and width processed to have been mistaken for each other, in the case of stereo.

https://github.com/sfztools/sfizz/blob/7f1d8259610e95e550228fbb869f00f57d7b144c/src/sfizz/Voice.cpp#L296-L305

https://github.com/sfztools/sfizz/blob/7f1d8259610e95e550228fbb869f00f57d7b144c/src/sfizz/Voice.cpp#L340-L348

**Comment by paulfd** [comment]
I managed to find a short explanation of the mid/side thing and assumed the balance between the different "channels" would follow similar pan laws. As I can't find the original paper, I'll draw something back without looking at the code and we can check whether it makes sense :slightly_smiling_face: 

Here's my quick take which I think mirrors what I was thinking at the time, now we can agree(?) on something like this and check the code.

[mid-side.pdf](https://github.com/sfztools/sfizz/files/4177676/mid-side.pdf)

**Comment by jpcima** [comment]
specification of `width` says:

`A width value of 0 makes a stereo sample play as if it were mono (adding both channels and compensating for the resulting volume change).`

If the paper is followed, we are using `a=1` and `b=0` for the center case, which means only the left sample is mixed, not an addition/compensation of both channels.

EDIT forgive misunderstanding if I read through this too fast, I will reexamine later

**Comment by paulfd** [comment]
When `a = 1` both output channels are equal to the sum of left and right.

**Comment by jpcima** [comment]
On a quick reexamination, yes, it makes sense.
It's also not what's implemented above as the stereo formula.

**Comment by paulfd** [comment]
Handled in #56
