### ISSUE TITLE
Generator wavetables

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#55]
This is the wavetable generator with IFFT for saw, square, triangle.
It's based on BSD-licensed kissfft.
https://gist.github.com/jpcima/9e43f08ed3a39e0363115c1ed449740e

In sfizz, it will need to implement adequate resampling so these waves can be generated with good quality.

**Comment by jpcima** [comment]
EDIT changed size*2+1, a benign mistake I copied everywhere, to size/2+1
also made the triangle wave start upwards instead of downwards

About this I don't know, didn't check against real oscillator, but I remember the LFO triangle was starting going up.

**EDIT** checked against ARIA, all waves starting upwards, fixed the square also

**Comment by jpcima** [comment]
It's implemented in the PR #61 
For a short summary of how this thing works:

- there exists a class `HarmonicProfile` which is a spectrum generator for any kind of periodic wave.
You invoke this with successive indices (DFT bin), this returns the amplitude and phase as complex number. It starts at index 1 for fundamental `f0`, then `2*f0`, `3*f0`, up to any size.
The spectrums of conventional waves extend to infinity, that we are able to truncate at whichever point we want.

- it can `generate` into an array of any size, by filling a spectrum of the matching size and doing IFFT.
When parameter `cutoff` is set at 0.5, the whole harmonic range is generated up to Nyquist, or <0.5 to cut it sooner.

- there exist multisamples, which wrap this to generate sets of wavetables for different frequency ranges (currently 1 per octave). For each table, this adjusts `cutoff` such that, when the table is repitched to the range's highest frequency, the scaled harmonics do not exceed Nyquist frequency.

- one can plot a multisamples with `sfizz_test_wavetables` and option `-m`. Pictured below.
When all is well, the final range of 10-20kHz reduces the signal to a single sine wave.
![plot](https://user-images.githubusercontent.com/17614485/74530670-eb1d2d00-4f2a-11ea-8b28-16ea4be351b0.png)

- the demo program permits to listen to an oscillator generated in realtime with a frequency sweep.
When frequency modulation causes a jump from a wavetable to another, this creates a discontinuity, but I don't find it very perceptible.
A thing of note: in Cakewalk's oscillators, there exists a quality setting called `Dual-High`, which permits to interpolate from 2 adjacent wavetables of a multisample, and avoids discontinuity created by such jumps.

- regarding custom oscillators from sound files, it's not too hard to modify the system to add it.

Example: `sample=period.wav oscillator=on`

The process is like this:
    - receive a sound file as a float span, compute its FFT
       (this FFT will likely needs scaling ; divide by the signal size)
    - create an instance of a subclass of `HarmonicProfile`, that will return each component for indices in bounds of the FFT array just computed, otherwise 0
    - invoke the method `createForHarmonicProfile`, like for any other profile of the predefined waves

**Comment by paulfd** [comment]
Merged in #61
