### ISSUE TITLE
Problem browsing in Qtractor after sfz file(s)

### ISSUE THREAD

**Issue by TobbeT** [sfztools/sfizz#558]
Hi,

I cant browse after sfz files in qtractor. I tried both versions vst3 and lv2. Nothing is happen when I click to load a sfz file. 

Tried it on Carla Rack...nope, didnt work.

Tested in LMMS also. Same problem. I must miss something.

OS: Manjaro KDE with everything updated
Latest kernel available for Manjaro.

**Comment by redtide** [comment]
Hello, probably you need to install the `zenity` package, which is used in sfizz for file requesters.

**Comment by TobbeT** [comment]
> Hello, probably you need to install the `zenity` package, which is used in sfizz for file requesters.

Yes! That did it. Thanks alot. Cased closed!
