### ISSUE TITLE
Bug: nothing happens when clicking "No file"

### ISSUE THREAD

**Issue by cshao06** [sfztools/sfizz#568]
I'm using the sfizz in REAPER on KDE Arch Linux. Both the LV2 and VST3 plugins won't let me select an SFZ file to load. Nothing happens when clicking "No file" in the plugin GUI.

I also tried dragging a file onto the VST plugin GUI in REAPER and had no luck. However, dragging a file onto the LV2 plugin in Carla does work.

My file manager is the default KDE Dolphin. I doubt it's any specific issue of the file manager.

**Comment by jpcima** [comment]
Hi, do you have either the `kdialog` or `zenity` package installed?
It needs this helper installed in order to present the file dialog.

As of the file drag&drop, it's available only on these hosts which implement the support of it.
In particular, Reaper does not permit this feature currently.

**Comment by cshao06** [comment]
That made it work. Thanks a lot!

Why did I never have this issue with other programs? Are there many different file dialogs? Do other programs happen to use file dialogs other than kdialog and zenity?

**Comment by jpcima** [comment]
The linux audio plugins have problems when they call directly into GTK for opening the file dialog.
eg. if a host is using Qt and the plugin calls GTK, this creates a fatal incompatibility.

It's the typical fix to this problem to invoke an external program, that will not be subject to this problem.
The approach is identical in Surge synthesizer.
