### ISSUE TITLE
Optimize clamp

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#57]
As ridiculous as this may sound, you can optimize clamp by rewriting it as a 2-line function.

It's a craziness I was aware of for a bit of time, you can easily reproduce it.
https://godbolt.org/z/NuNaq9

As you will be able to observe, gcc will generate a branch in the slow case, and just an instruction pair in others.

**Comment by paulfd** [comment]
Wow, OK. Seems the 3rd one is the most general; clang seems to match gcc's code, and msvc just adds a move instruction for some reason. A similar effect can be seen on ARM too. 

So the clearest code is also the fastest one here :joy:
