### ISSUE TITLE
[Question] Need anything special to build the VST plugin?

### ISSUE THREAD

**Issue by grammoboy2** [sfztools/sfizz#589]
Do I need anything special, like SDKs or something, to build the VST plugin?

**Comment by jpcima** [comment]
These are pulled as submodules. Just `-DSFIZZ_VST=ON` to cmake should do.

This has the list of systems dependencies and build procedure, you can refer to our github script.
https://github.com/sfztools/sfizz/blob/cbcc875aef05ca161a962e0e529c38ae149ffc45/.github/workflows/build.yml#L43-L57

**Comment by redtide** [comment]
The build instructions are placed at <https://sfz.tools/sfizz/development/build/>, from the `Build` link in the menu, please let us know if something is missing or not clear.

**Comment by squinkylabs** [comment]
This is pretty dumb, but I've never used CMake. What do you type at the command line to build sfizz? And what folder should you be in when you do it?

I know usually with "old make" there is a Makefile in the root of most projects, so you cd to the root and type `make`. but clearly CMake isn't like that.

**Comment by redtide** [comment]
You can either use the main project folder or any other of your choice, usually a `build` directory is used, as described on one of the OS target pages from the link above:
```
cd sfizz
mkdir build && cd build
cmake ..
cmake --build . --config Release
```

**Comment by jpcima** [comment]
This question has been answered, closing.
Future discussion is in the newly opened "Discussions" section
