### ISSUE TITLE
Ability to enter manual tuning frequency

### ISSUE THREAD

**Issue by ghost** [sfztools/sfizz#590]
The presets are nice but I would find it very useful to enter manual values such as A=399 etc

**Comment by ghost** [comment]
I note that this is possible via the generic UI on LV2 but on VST this is currently not possible.

**Comment by ghost** [comment]
Also add to this ability to enter manual volume amount in top right corner.

**Comment by jpcima** [comment]
#599
it was made possible to edit tuning frequency using the mouse wheel.

**Comment by paulfd** [comment]
Is this solved?

**Comment by jpcima** [comment]
It depends, are we interested in some way to edit the value textually?
There are multiple possibilities
- popup dialog with input box
- a vstgui hackery to integrate a text edit in there somehow

**Comment by AlexMitchellMus** [comment]
Maybe put it in another dialog spin box, with a button that says: "use custom tuning"?

If the button is false, then use one of the preset tunings listed.
