### ISSUE TITLE
Sfizz LV2 and VST crash Ardour 6.5.x and Reaper 6.19 on Linux

### ISSUE THREAD

**Issue by bachstudies2020** [sfztools/sfizz#591]
Sfizz build (inclusive of commit cbcc875) allows for loading of scala file and tuning preset but after several seconds of playing (maybe sometimes just shy of a minute), Sfizz crashes Ardour and Reaper (native)

**Comment by bachstudies2020** [comment]
I _think_ I might have pinned this down to using opcode `sample_quality=2` in my SFZ. I can't operate without it (until Hermite or similar is made the default) given my instrument is using whole step sampling and default quality is too noticeable on the half-step notes.

**Comment by bachstudies2020** [comment]
On a couple of occasions I've been able to crash it by changing polyphony from 64 to 128 and on another, quickly moving between key switches. Tested without any other plugins present and with both default resampling and `sample_quality=2` opcode present.

**Comment by bachstudies2020** [comment]
Through process of elimination, I believe the root cause of the crash is when the polyphony setting (under engine) is moved away from the value of 64.

**Comment by jpcima** [comment]
It's most likely fixed in the latest, please confirm

**Comment by bachstudies2020** [comment]
After a brief play, I do believe the polyphony issue is fixed. Thanks!
