### ISSUE TITLE
licence issue

### ISSUE THREAD

**Issue by trebmuh** [sfztools/sfizz#592]
Lintian (debian cheking utility) reports that https://github.com/sfztools/vstgui/blob/055cbcc9ae858f0b07d5d86c205a1111e2fba7a4/vstgui/uidescription/rapidjson/license.txt isn't free, see: https://wiki.debian.org/qa.debian.org/jsonevil .
@jpcima told me on IRC that all the uidescription/ folder can be removed since it's not use at all.
To ease packaging and redistribution, it could be great to remove those files in the tarball when releasing.

HTH

**Comment by jpcima** [comment]
This will be fixed automatically when the next release is made.
