### ISSUE TITLE
sample_quality=2 opcode takes away high frequency content

### ISSUE THREAD

**Issue by ghost** [sfztools/sfizz#594]
Sfizz with sample_quality=2 vs default Sforzando lops off some high frequency content. Checked against original samples using a spectrum analyzer...
![Screenshot_2021-01-16_14-11-29](https://user-images.githubusercontent.com/65790582/104824304-6c4d0600-5805-11eb-8242-dff502c77525.png)
![Screenshot_2021-01-16_14-12-07](https://user-images.githubusercontent.com/65790582/104824308-6f47f680-5805-11eb-8f83-5cd934154fa6.png)

**Comment by jpcima** [comment]
Is the difference perceptible?
it's expected that linear interpolation produces at least some high frequency artifacts as result of aliasing.
As of sforzando, I don't know about what algorithm it uses.

**Comment by ghost** [comment]
Apparently Sforzando uses Hermite. I should be clear that I heard an obvious damping of high frequency content but then double-checked with an analyzer. So, yes, definitely perceptible.

**Comment by jpcima** [comment]
Your observation is right, that B-spline has a few dBs of loss in the high frequencies.
Hermite is not worse that linear in this criteria, so I changed it as the algorithm for sample_quallity=2.
Let me know if that makes it better.

**Comment by ghost** [comment]
Thanks so much. I will build later and let you know!

**Comment by ghost** [comment]
After a brief test, all seems well! High frequency content is restored...

**Comment by jpcima** [comment]
As expected :+1:  thanks for confirmation
