### ISSUE TITLE
sfizz currently saving basenames only for sfz and scl files

### ISSUE THREAD

**Issue by jamshark70** [sfztools/sfizz#595]
I have just been trying to use sfizz with Ardour and Carla.

When saving projects in both hosts, I get:

Ardour 'state.ttl` file:
```
	state:state [
		<http://sfztools.github.io/sfizz:sfzfile> <flute-SEC-KS-C2.sfz> ;
		<http://sfztools.github.io/sfizz:tuningfile> <DefaultScale.scl> ;
		... etc.
	] .
```

Carla `.carxp` file:
```
  <CustomData>
    <Type>http://lv2plug.in/ns/ext/atom#Path</Type>
    <Key>http://sfztools.github.io/sfizz:sfzfile</Key>
    <Value>flute-SOLO-KS-C2.sfz</Value>
   </CustomData>
 
  <CustomData>
    <Type>http://lv2plug.in/ns/ext/atom#Path</Type>
    <Key>http://sfztools.github.io/sfizz:tuningfile</Key>
    <Value>DefaultScale.scl</Value>
   </CustomData>
```

As these are not complete paths, if I close either host and reopen, then the plug-in instance exists but it has no sample data to play. So there is no sound. (I also tried hacking the Ardour state file to put in the full path manually, but the lack of a tuning file also suppressed audio. Hacking the Carla state file doesn't help at all -- it still reports 0 groups, 0 samples.)

Because this is happening identically in two different hosts, I have to assume that the host is asking sfizz to describe its state and sfizz is not supplying enough information to recover the state next time.

At the moment, I can find no workaround. I would have to open each plug-in instance manually when loading the Ardour project, every time, and find the instrument in the folder structure. For 20 instruments in a small orchestra, this will be... how to say... inefficient. (So for now I have no choice but to use Carla's SFZero plug-in, which appears not to support keyswitches, but I really want the keyswitches.)

**Comment by falkTX** [comment]
This is working exactly as intended. The host puts a symlink to the file in question in the session dir, and the session file only contains the abstract path. This allows to move the session within the disk and also export/archive.

maybe you are saving the project in a mount point or file system that does not support symlinks?

**Comment by jamshark70** [comment]
Ohhh ok... I wanted to keep the files off of the system partition, but it's a FAT partition, which indeed doesn't support symlinks.

Ok, I'll save the files on the system partition. Thanks.

I'll close this, but... is this documented btw?

**Comment by falkTX** [comment]
I guess it is not documented, as it is quite unexpected.
