### ISSUE TITLE
Ability to return to default tuning scale by removing scala file

### ISSUE THREAD

**Issue by ghost** [sfztools/sfizz#598]
It seems impossible to remove a scale file once loaded. Shouldn't loading a new instrument reset the scala and tuning options by default? If not, it would be great to have a reset to default tuning scale without having to delete and re-add the plugin.

**Comment by jpcima** [comment]
The remedy right now is to load the equal temperament file which ships in the plugin bundle.
It's shipped so the plugin uses it by default. So it can be done, just not atm in user-friendly manner.
A thing of LV2 file controls, they can't be easily reset to empty, hosts don't usually provide such feature in generic UIs.

**Comment by ghost** [comment]
Thanks, it's a useful workaround for now.

**Comment by falkTX** [comment]
this is something the host can do, if it cares enough.
on MOD, the "default" file is listed first on the possible list of files to use.
this assumes the plugin ships with an actual file (and not just "empty" or none) and has it referenced on the "default state"
