### ISSUE TITLE
how to force sfizz to build with mingw, rather than Visual Studio

### ISSUE THREAD

**Issue by squinkylabs** [sfztools/sfizz#602]
See log fragment, below. CMake is correctly seeing that Msoft Visual Studio is installed on my dev computer. It there a way to force it to see mingw? I'm running from inside the msys2 shell, which provides cmake, gcc, and all the other goodies usually used to build open source code.

```
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 1/30/2021 1:38:59 PM.
Project "C:\hacking\dep\sfizz\build\CMakeFiles\3.19.2\CompilerIdCXX\CompilerIdCXX.vcxproj" on node 1 (default targets).
PrepareForBuild:
```

**Comment by redtide** [comment]
IIRC from the MSYS2 shell you need to use the related CMake generator option:
```
cmake -G"MSYS Makefiles"
```

**Comment by squinkylabs** [comment]
tx!
