### ISSUE TITLE
How to make Visual Studio happy when source files have same name

### ISSUE THREAD

**Issue by squinkylabs** [sfztools/sfizz#603]
I'm doing something I probably shouldn't, but just hacking around.
I tried to make a visual studio project using the sfizz source code.
Once I added two files called ADSREnvelope.cpp it gets mad.
I can see that these two files have different classes inside them, but I still get this error:

```1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(1069,5):
 warning MSB8027: Two or more files with the name of ADSREnvelope.cpp will produce outputs to the same location.
This can lead to an incorrect build result.  The files involved are 
..\..\dep\sfizz\src\sfizz\ADSREnvelope.cpp, 
..\..\dep\sfizz\src\sfizz\modulations\sources\ADSREnvelope.cpp.
1>Debug\ADSREnvelope.obj : warning LNK4042: object specified more than once; extras ignored
```
I've never run into this before. Is there a way to make this work? And, not to be ungrateful for all this nice code, but why not have the class name and the file name be the same? Less confusion and less errors.

**Comment by jpcima** [comment]
It's known to build in Vs 2019 with cmake configuration.
Do you have a particular setup that makes this problem happen?

**Comment by squinkylabs** [comment]
I couldn't figure out the how to make cmake run, so I just built my own project. Sounds like I should go back to wrestling with cmake. never had to wrestle all day to get an project from github to build, but there's always a first time ;-)

**Comment by jpcima** [comment]
You can use sfizz as a directory of another project made with cmake.

A basic way of doing should be something like this.
```
cmake_minimum_required(VERSION 3.7)

add_subdirectory(external/sfizz EXCLUDE_FROM_ALL)

add_executable(myprogram PRIVATE sources/myprogram.cpp)
target_link_libraries(myprogram PRIVATE sfizz::sfizz)
```

**Comment by squinkylabs** [comment]
oh, interesting. thank you!
