### ISSUE TITLE
who instantiates the templates in ADSREnvelope.cpp?

### ISSUE THREAD

**Issue by squinkylabs** [sfztools/sfizz#604]
It's a templated class, but the definitions are all in ADSREnvelope.cpp.
I've seen templates the normal way, where they are defined in the .h 
I've also seen explicit instantiation used to make this kind of cpp file thing work, like:

template class ADSREnvelope<float>;
template class ADSREnvelope<double>;

But I've never seen a template instantiated the way it is in sfizz. How does this work?

**Comment by jpcima** [comment]
It's called explicit template instantiation, and it's a trick for saving compilation time in some cases.
https://docs.microsoft.com/en-us/cpp/cpp/explicit-instantiation

In our case though, it's not really useful, probably more an artifact from older versions.
We really need float only, so it can be changed into a normal class. I will do probably at some point later.

**Comment by squinkylabs** [comment]
yes, you can see I mentioned explicit template instantiation in my original question. I was unable to find the point at which that was done. Doing directly in the defining c++ file would make it clearer, and less easy to make linker errors like I did.

thanks.
