### ISSUE TITLE
looking for advice on what targets are easy to build

### ISSUE THREAD

**Issue by squinkylabs** [sfztools/sfizz#606]
thanks in advance!

Looking for advice. I want to build some form of sfizz so that I can run it in a debugger and learn more about the architecture. My near term goal is to make a command-line windows app that I can “goof around with”.

I’m hoping/assuming that I can get cmake to make something for me, although I have also tried making my own Visual Studio project for it.

I am guessing that turning off various targets will increate my chance of success. So here is my current invocation of CMake. It seems like I’m close, but if you have any suggestions it would be appreciated.
```
cmake -DCMAKE_BUILD_TYPE=Debug -DSFIZZ_JACK=OFF -DSFIZZ_SHARED=OFF -DSFIZZ_RENDER=OFF ..
```

**Comment by jpcima** [comment]
You're welcome @squinkylabs.
Having this talk in the issues section is not amazing I think, so I've just opened the discussions feature.
You can repost questions there if you don't mind too much.
→ https://github.com/sfztools/sfizz/discussions

**Comment by squinkylabs** [comment]
will do! thanks for all the prompt replies, really appreciate it. update: done!
