### ISSUE TITLE
Support note names for opcodes, hikey, key, lokey and pitch_keycenter

### ISSUE THREAD

**Issue by SpotlightKid** [sfztools/sfizz#620]
Some software, for example [Polyphone](https://www.polyphone-soundfonts.com/), produces SFZ files, where note names instead of MIDI note numbers are used for the values of the `hikey`, `key`, `lokey` and `pitch_keycenter` opcodes.

According to sfzformat.com: *"values can be specified in MIDI note numbers (0-127) or note names (IPN Standard)"*. But the latter are currently not interpreted correctly by sfizz. It seems to just just play all the regions using these values on every key.

As a workaround, I currently use [this script](https://github.com/SpotlightKid/sfzparser/blob/master/fix-polyphone-sfz.py) to fix the SFZ files exported by Polyphone (note that Polyphone also incorrectly uses partly localized note names, e.g. "H3" when the interface is not English, but that's a bug in Polyphone).

**Comment by jpcima** [comment]
Can you possibly share a sample?
Polyphone does not export me IPN notes, my output has numbers.

**Comment by kinwie** [comment]
@jpcima there is an option to choose note names instead of numbers. It's like in the Setting or Option menu

**Comment by jpcima** [comment]
Ok so this amounts to support the unicode symbols ♯ and ♭.
Sure I'll add it.
