### ISSUE TITLE
Change VST parameter names dynamically

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#627]
How to change VST parameter names according to CC labels.
```
Steinberg::String newTitle = "...";
newTitle.copyTo(parameter->getInfo().title, 0, 128);
componentHandler->restartComponent(kParamTitlesChanged);
```

**Comment by paulfd** [comment]
Ho that's cool actually! Could we also hide them if unused maybe?

**Comment by jpcima** [comment]
Possibly, depending on the host support.
It seems `kParamTitlesChanged`, despite its name, also affects parameter flags.
A flag `kIsHidden` exists.

From documentation
> kParamTitlesChanged | Parameter titles, default values or flags (ParameterFlags) have changed The host invalidates all caches of parameter infos and asks the edit controller for the current infos.[SDK 3.0.0]

> kIsHidden | parameter should be NOT displayed and cannot be changed from outside the plug-in (implies that kCanAutomate is NOT set and kIsReadOnly is set) [SDK 3.7.0]
