### ISSUE TITLE
One-shot voices stick and fill up the polyphony

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#63]
reported by @alcomposer : when you play 64 notes of a one-shot generator, the polyphony is filled and you can't play anymore unless resetting the plugin.

Should the voices be cleared once the envelope has reached the end?
also can we permit new notes to steal a slot more aggressively, in case the polyphony is filled?

```
<group>
lovel=0
hivel=127

<region>
trigger=release
sample=*noise
loop_mode=one_shot
ampeg_attack=1
ampeg_decay=1
ampeg_release=0
ampeg_sustain=0
```

**Comment by AlexMitchellMus** [comment]
`trigger=release` is what stops the voice from being deactivated. Otherwise the example works fine without that line.

**Comment by paulfd** [comment]
OK, so we can assume that in this case (`trigger=release`) the envelope should basically run its course without sustaining at all, would this be right?

If so, the envelope needs a `freeRunning` parameter in the envelope and get into release state as soon as it hits the sustain state. As a note for me (I may have time to do this in the WE) or if someone wants to try, this should be as simple as having a boolean check to switch the status to `Release` [here](https://github.com/sfztools/sfizz/blob/cf940980b45cd8b0f80c7b03daf6eb845e3ee2ab/src/sfizz/ADSREnvelope.cpp#L154) and [here](https://github.com/sfztools/sfizz/blob/cf940980b45cd8b0f80c7b03daf6eb845e3ee2ab/src/sfizz/ADSREnvelope.cpp#L83), along with proper setup depending on the `Region` trigger value and setting the `freeRunning` value [there](https://github.com/sfztools/sfizz/blob/cf940980b45cd8b0f80c7b03daf6eb845e3ee2ab/src/sfizz/Voice.cpp#L112).

However, this is a good opportunity to refactor [that](https://github.com/sfztools/sfizz/blob/cf940980b45cd8b0f80c7b03daf6eb845e3ee2ab/src/sfizz/ADSREnvelope.cpp#L15) and the `prepareEGEnvelope` function above which are ugly and will not scale to flex EGs easily. The solution would be to have it more like [this function](https://github.com/sfztools/sfizz/blob/cf940980b45cd8b0f80c7b03daf6eb845e3ee2ab/src/sfizz/FilterPool.cpp#L20) in the filter pool: give the EG a reference to the `Region`, the `MidiState`, as well as the initial delay and velocity, and let it compute its parameters itself.

Short term EGs should be distributed like filters anyway and have a stable reference to MidiState, but for now the parameter is needed in the call.

**Comment by paulfd** [comment]
Note that as soon as the envelope gets into release properly, [this line](https://github.com/sfztools/sfizz/blob/cf940980b45cd8b0f80c7b03daf6eb845e3ee2ab/src/sfizz/Voice.cpp#L280) should reset the voice.

All of this may break tests or require some additional tests :slightly_smiling_face:

**Comment by paulfd** [comment]
It seems to work now. If you confirm I'll merge the PR and close this issue. Thanks!

**Comment by jpcima** [comment]
Yes the problem is gone. However, I have a link error on one of the benchmarks.

```
/usr/bin/ld : CMakeFiles/bm_envelopes.dir/BM_envelopes.cpp.o : dans la fonction « sfz::ADSREnvelope<float>::reset(sfz::Region const&, sfz::MidiState const&, int, unsigned char, float) » :
/home/jpc/documents/projects/sfizz/benchmarks/../src/sfizz/ADSREnvelope.cpp:21 : référence indéfinie vers « sfz::MidiState::getCCArray() const »
```

**Comment by paulfd** [comment]
Corrected! Thanks.
