### ISSUE TITLE
Native REAPER on Linux can't scan VST3 version on releases page, but will scan Debian package provided by https://download.tuxfamily.org/librazik/pasapas/pool/main/s/sfizz/

### ISSUE THREAD

**Issue by TheVengefulPrince** [sfztools/sfizz#639]
After merging all of the files into /usr/local and pointing REAPER to them, it fails to scan properly and appears in the failed plugins menu. I should also clarify that there is no crash when scanning the plugin as mentioned in other issues.

The experimental REAPER builds that support LV2 accept the LV2 plugin provided, but VST3 still doesn't work.

**Comment by paulfd** [comment]
Hi ! So to make it clear, the librazik version works but not the release version? Did you try the release page version after having the other installed? I am not sure the one in the release page has e.g. libsndfile built-in, so you might need some dependencies for it to work.

**Comment by jpcima** [comment]
Hi @TheVengefulPrince 
This is for LibraZiK 3? Try Debian 10.0 packages from this location.
https://software.opensuse.org//download.html?project=home%3Asfztools%3Asfizz%3Adevelop&package=sfizz

**Comment by paulfd** [comment]
By the way we also have a .deb file for both stable and develop branches over at https://build.opensuse.org/package/show/home:sfztools:sfizz/sfizz and https://build.opensuse.org/package/show/home:sfztools:sfizz:develop/sfizz

**Comment by TheVengefulPrince** [comment]
I installed the binary at the link I found above in a test machine because that was the first link I found in a search.

All .deb packages provided reference Debian package libxcb-cursor0, but when I install libxcb-cursor0 and merge the 0.5.1 release files on a test machine, the problem persists.

I have came to a solution of extracting and manually merging the files provided by the 0.5.1 .deb package on https://opensuse.org and installing libxcb-xcursor0, this allows REAPER to scan the plugin. I don't know what discrepancies there are between the two versions, so if you need more information to debug this, I'd need pointed in a direction.

**Comment by jpcima** [comment]
> merge the 0.5.1 release files on a test machine

You can't force a version which is built with a different xcb to run on your system.
It's a known inconvenience. From one version to Ubuntu/Debian to the next, the binary compatibility became broken.
You just have to pick a build which matches your system, or otherwise build yourself.

Anyway it's not a bad to pick the `develop` version for time being, it contains a big pile of bug fixes , and all this is due for a release which I hope can happen soon.

**Comment by TheVengefulPrince** [comment]
OK, I'm closing this issue now.
