### ISSUE TITLE
Optimize random generator

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#67]
Below is a number generator, fast and branchless, in few instructions.
It has a comparison with standard library generators.
https://godbolt.org/z/r_TccA

As a note, the std generator is particularly bad when using clang as the compiler, for some reason.

**Comment by paulfd** [comment]
MSVC is pretty bad too...

I'm good with this, I'd like to bench it against the std::normal after the box-muller transform or do you have a faster method for this? 

On a side note, visually, the white noise I generate now looks quite different from sforzando's. I need to plot some histograms to understand what's going on.

**Comment by jpcima** [comment]
I think the question to ask as: does it sound the same? if so, fine enough.

Visually, I have run a plot as I implemented and the result was like this.
![random](https://user-images.githubusercontent.com/17614485/74747058-a06f1e00-5266-11ea-9163-13139fec8568.png)

**Comment by paulfd** [comment]
I'm moving this up to the next milestone for the SIMD version and the Gaussian one.

**Comment by jpcima** [comment]
It's funny that you comment this now, I was researching gauss and I have a decent one at hand.
I'm going to attach the plots.

**Comment by jpcima** [comment]
There is a distribution which matches c++ `normal_distribution` with various values of variance.
It's nothing original, it's `no.gnoise` of faust, I just make a plot from it.
It accepts a quality settings that ranges from 2 (looks triangle-ish) to any integer values.

![gauss_0 25](https://user-images.githubusercontent.com/17614485/85234774-1f8c8280-b410-11ea-9433-19c671ac949e.png)
![gauss_0 5](https://user-images.githubusercontent.com/17614485/85234783-287d5400-b410-11ea-84ee-54214fc524cd.png)
![gauss_0_75](https://user-images.githubusercontent.com/17614485/85234795-36cb7000-b410-11ea-9d7a-8eeca51808c0.png)
