### ISSUE TITLE
No sound and CPU maxed with CC 64 sustain

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#676]
- Send CC 64 value 127 to turn on sustain
- Play some notes
- Instrument goes silent
- Voice count never decreases

Problem reproducible with NoBudgetBand guitar, eg. `Guitar/LesPaul/lp_full.sfz`
http://www.bandshed.net/sounds/sfz/nbb_guitars.zip

**Comment by kinwie** [comment]
@jpcima 
I look at the file. There is an inappropriate placement of sw_lokey sw_hikey opcodes in the N1 file.
The `sw_lokey=c2 sw_hikey=127` are placed at `<group>`
That might be causing the issue?

**Comment by kinwie** [comment]
Ooh wait. `Guitar\LesPaul\lp_full.sfz` played fine here
