### ISSUE TITLE
Moving CC4 of Hihats from UI doesn't change the sound

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#684]
I found an issue when testing some drums instruments that use CC4 for Hihats articulation switching (closed to open) :
_Moving CC4 from UI doesn't change the sound_

While moving from savihost CC, it works fine.

Example kit here, in case needed for checking :
https://github.com/sfzinstruments/WilkinsonAudio.NakedDrums

![ND_sfizz](https://user-images.githubusercontent.com/65444898/110510494-d1521780-8135-11eb-90d4-3cefe87e1c73.png)

**Comment by paulfd** [comment]
Solved in #786
