### ISSUE TITLE
MacOS Logic Pro Auto-Reload Bug

### ISSUE THREAD

**Issue by AlexMitchellMus** [sfztools/sfizz#689]
Using latest sfizz with MacOS Logic Pro, the auto-reload feature of sfizz works sporadically.

Sometime it will reload when I save the `file.sfz`- and other times I will need to close/open sfizz plugin. It also works sometimes when I load another SFZ script- and come back to the one in question.

**Comment by paulfd** [comment]
Close/open the GUI, or reload the plugin?

If you can run in debug build, there's a console message when the file reloads.

**Comment by jpcima** [comment]
Automatic reloading is dependent on the `process` function to send a message every period of a fixed number of frames.

There are some cases where the `process` function is not working in a periodic way, or not called at all.
One is the processor being suspended of course, or performing offline rendering, or in these save/load situations (where the processor performs a special `process` call whose purpose is parameter flush. see https://steinbergmedia.github.io/vst3_doc/vstsdk/faq.html#faqCommunication6).

No doubt, a more appropriate way would be that the work thread does this ticking by itself on the basis of some independent timer.

**Comment by AlexMitchellMus** [comment]
> Close/open the GUI, or reload the plugin?

Closing/opening the GUI tends to work. I am not reloading the plugin.
It is very sporadic, no knowing when it will reload- and what will trigger it. (sfizz AU - Logic Pro MacOS)
