### ISSUE TITLE
Effect routing

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#69]
Some initial analysis of effect routing is added in the wiki.

https://github.com/sfztools/sfizz/wiki/Effect-routing

This is a quick-made and terrible dot graph of what routing can be supposed to be. (not checked 100%)

![effect-routing](https://user-images.githubusercontent.com/17614485/75176384-60131280-5734-11ea-8c06-709070aca407.png)
[effect-routing.dot.gz](https://github.com/sfztools/sfizz/files/4245910/effect-routing.dot.gz)

**Comment by jpcima** [comment]
Updated the graph to indicate effect chaining.

Also I don't know fully what `auxN` buses are for, perhaps they participate in the Mix endpoint; there is also an effect `mixer` from the book that can supposedly use them in the opcode `source_2`, not present in the software.

**Comment by paulfd** [comment]
I guess this is closed by #84 ?

**Comment by jpcima** [comment]
Yes, except for the aux buses possibly, but as far as I'm aware there are book-only, as well as buffer/mixer pseudo-effects.
