### ISSUE TITLE
smoothcc is not in milliseconds and should allow > 100

### ISSUE THREAD

**Issue by AlexMitchellMus** [sfztools/sfizz#697]
Smoothcc should smooth the controller with a setting in milliseconds.
This is great for adding character to instrument control, it is not uncommon to see values of smoothcc > 1000.

Currently it is limited of 100, any greater and it resets to 0 (@jpcima edit), and it is not clear if the value is in milliseconds. Testing a value of 100 does not look like it is in milliseconds from measuring the resultant smoothing.

**Comment by jpcima** [comment]
In the exponential model (cakewalk, old sfizz), it's an asymptotic time constant expressed in ms.
In linear, it's an exact time constant, but gets a full reset each CC that arrives, which is Aria behavior.

The deeper problem is duplicated with another issue, see also
https://github.com/sfztools/sfizz/issues/704#issuecomment-802729086
