### ISSUE TITLE
min and max value issue on lobend/hibend

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#704]
https://sfzformat.com/opcodes/lobend
https://sfzformat.com/opcodes/hibend

It's said in the specs, the range for lobend and hibend is -8192 to 8192 atm, which is not correct.
The range should be -8192 to 8191, and the center value is 0

sfizz has these minor issue :
- When the pitch bend data at max (8191) and lobend/hibend at 8192, the region still play, which it shouldn't.
- When the pitch bend data at min (-8192) and lobend/hibend at -8191, the region still play, which it shouldn't.

Example :
```
<region>
sample=snare.wav
loop_mode=one_shot
key=60
lobend=-8191
hibend=-8191
```

**Comment by jpcima** [comment]
This is about limited value ranges, and is the same deeper issue as #697 #696
It needs to modify opcode specifications such that values out-of-range don't reset to default.

**Comment by paulfd** [comment]
Not sure it's only this, I'm pretty sure I have some flaky rounding going on for bending in particular..
