### ISSUE TITLE
Another clicking issue on whole-looped sample

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#705]
Not sure what cause this issue.
The wav sample has loop start and end, the same as sample start and end (looped whole sample).
Attached example file:
[sine60_test.zip](https://github.com/sfztools/sfizz/files/6142470/sine60_test.zip)

This sample is played fine in sforzando, DropZone and BassMidi

**Comment by paulfd** [comment]
Maybe I messed something up in the last patch, I'll check it.

**Comment by paulfd** [comment]
Did this work at any point?
