### ISSUE TITLE
VST2 version of sfizz

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#707]
The "official" version is VST3.
I want a VST2 32-bit version of sfizz.
Just in case, anybody read this issue are willing to help build the VST2 version, that will be great!
And better, if anybody can build an RTAS version or AAX-32 of sfizz.

**Comment by redtide** [comment]
The title of this issue probably had to be "Pro Tools DAW support", where [this] could be a better solution, though an iLok PACE signing is required to make it work in normal, non development releases of the DAW.

[this]: https://developer.steinberg.help/display/VST/VST+3+-+AAX+Wrapper

**Comment by paulfd** [comment]
How does JUCE does it btw? It can export AAX plugins right? You need a key too?

**Comment by redtide** [comment]
IDK about JUCE, it seems to support it but I haven't checked yet there, I've seen [this post] that explains how the process works, basically an unsigned plugin can be tested/used only on development builds, which are available for download after creating an account on https://developer.avid.com/.

[this post]: https://forum.juce.com/t/building-aax-code-signing/14055

**Comment by kinwie** [comment]
@redtide Yes, my aim is for that

**Comment by kinwie** [comment]
Anyway, JPCima has solved this issue I believe

**Comment by redtide** [comment]
I guess this can be closed and possibly if needed open one for AAX if desired?

**Comment by jpcima** [comment]
We need to document how to make this build, otherwise that's it

**Comment by jpcima** [comment]
Notes on building VST2 on Windows (format this later as a proper page)

- Install Visual Studio 2019 Community
  Select "Desktop development with C++", make sure to enable "C++ CMake tools for Windows"

- Open Visual Studio
  Click "Clone a repository"

![2021-04-17 17_47_12-Microsoft Visual Studio](https://user-images.githubusercontent.com/17614485/115118742-03606000-9fa5-11eb-8f50-057e930fd851.png)

- Fill "Repository location" with `https://github.com/sfztools/sfizz.git`
  Click "Clone"

![2021-04-17 17_49_07-Microsoft Visual Studio](https://user-images.githubusercontent.com/17614485/115118783-3c98d000-9fa5-11eb-9cb3-a6d4420f893e.png)
![2021-04-17 17_50_42-Microsoft Visual Studio](https://user-images.githubusercontent.com/17614485/115118826-7538a980-9fa5-11eb-9039-dd7970554790.png)

- Enter "sfizz" by a double-click on the folder view
![2021-04-17 18_00_26-sfizz - Microsoft Visual Studio](https://user-images.githubusercontent.com/17614485/115119071-eaf14500-9fa6-11eb-9a2d-a05dee0ec61c.png)

- A Steinberg VST2 license is needed to use the SDK
  Get the file `vst_sdk2_4_rev2.zip` (found at archive.org in "VST2 SDK")
  Extract contents in `sfizz/plugins/vst/external`

![2021-04-17 18_11_47-external](https://user-images.githubusercontent.com/17614485/115119390-6ef7fc80-9fa8-11eb-8f28-f260d14c7117.png)

- Open"Manage configurations" in the drop-down list
![2021-04-17 18_02_29-sfizz - Microsoft Visual Studio](https://user-images.githubusercontent.com/17614485/115119120-1c6a1080-9fa7-11eb-98f6-1f38b093c2d2.png)

- Delete the default "Debug" configuration
  Add either "x86-Release" or "x64-Release", depending whether a 32-bit or 64-bit build is wanted
![2021-04-17 18_04_03-sfizz - Microsoft Visual Studio](https://user-images.githubusercontent.com/17614485/115119178-55a28080-9fa7-11eb-91ae-33aeb5ce9127.png)

- Do "File > Save CMakeSettings.json"
  Wait during configuration. The section "CMake variables and cache" will be filled.

![2021-04-17 18_14_27-sfizz - Microsoft Visual Studio](https://user-images.githubusercontent.com/17614485/115119476-ca29ef00-9fa8-11eb-97eb-287a4139fd82.png)


- Change `CMAKE_BUILD_TYPE` to `Release` (written with this exact case)
  Check `SFIZZ_VST2`
  Uncheck `SFIZZ_LV2`
  Uncheck `SFIZZ_RENDER`
  Uncheck `SFIZZ_SHARED`

![2021-04-17 18_17_47-sfizz - Microsoft Visual Studio](https://user-images.githubusercontent.com/17614485/115119556-3efd2900-9fa9-11eb-8bf3-85616338d019.png)
![2021-04-17 18_17_10-sfizz - Microsoft Visual Studio](https://user-images.githubusercontent.com/17614485/115119541-28ef6880-9fa9-11eb-966e-f67db181e652.png)

- Do "File > Save CMakeSettings.json" again
  Wait.

- There is now "Build > Build All" in the menu. Click it.

![2021-04-17 18_17_47-sfizz - Microsoft Visual Studio](https://user-images.githubusercontent.com/17614485/115119583-74a21200-9fa9-11eb-99bb-51a5662443bd.png)

- After a successful build, from the "sfizz" folder, navigate in the "out" folder and a bit down from there.
  The VST2 bundle will be found in the folder `sfizz.vst2`.

**Comment by kinwie** [comment]
This is solved, thanks!
