### ISSUE TITLE
Region activations are not sample-accurate

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#735]
Preferably the region activations should allow to be evaluated at precise frames.
This issue concerns / will concern at least
- cc
- bend
- velocity
- channel aftertouch
- poly aftertouch

**Comment by paulfd** [comment]
One way to ensure this without introducing too much complexity is just to buffer all "messages" before the `renderBlock` function is called, sort them appropriately, and perform their associated actions afterwards.

To be clear just in case, it's not that the current version is not "sample accurate", but it assumes that CC and note events are sent sorted for the purpose of region activation (or note stealing for that matter). If the events are sent sorted by their delay within the block everything works as expected.

**Comment by jpcima** [comment]
Let me try to explain it differently:
- if sfizz is requested a cycle 1 second
- an activation message on->off arrives at 0.5 second within the cycle

then we have the following expectations, which will not be met in current sfizz
- the note-on arrived at time 0.25 must not activate the region;
- the note-on arrived at 0.75 does.

**Comment by paulfd** [comment]
Yes unless the received sequence is ordered, i.e.
* Note on at 0.25
* Activation message at 0.5
* Note on at 0.75

**Comment by paulfd** [comment]
API updated in #771
