### ISSUE TITLE
Notes playing first time silent?

### ISSUE THREAD

**Issue by tavasti** [sfztools/sfizz#74]
When loading project, and starting to play, some notes aren't playing. Something like sounds are loaded in request, and hitting first time, they aren't loaded yet? 

Are sounds played from memory or disk?

Using version 0.2.0, downloaded linux-amd64, and using lv2

**Comment by paulfd** [comment]
Hi! The samples are preloaded but it may take some time, and the synth will not start sounds during this time. In Ardour you can check that the sfz finished loading in the log window (a button on the top right with a yellow or red dot in it): it will tell you the number of regions when it's done.

If after that there's still no sound on the first notes then yeah there's a problem 😄 To answer your other question, only the first part of the sample is preloaded and the rest is streamed on demand.

**Comment by paulfd** [comment]
To answer your other question, only the first part of the sample is preloaded and the rest is streamed on demand.

**Comment by paulfd** [comment]
Did you have time to try again?

**Comment by tavasti** [comment]
I tried it few times, maybe one time got it, but not sure. This was when plugin was freshly added to track, and sfz loaded. 

On other tries on closing Mixbus, starting again, everything played ok. 

Maybe this is not happening often enough if any, and this issue is not worth spending your time.

**Comment by paulfd** [comment]
Ok, I'm closing this for now, if it appears conclusively again, reopen it and we can try to find out what is happening.
