### ISSUE TITLE
How can I load samples into sfizz?

### ISSUE THREAD

**Issue by Satlinker** [sfztools/sfizz#740]
Hi, beginners question: is there a GUI or how can I load samples into sfizz? I try to use it in ardour.

**Comment by jpcima** [comment]
Hello, the file dialog is not appearing, most likely, because the package `zenity` is not installed.
The next version will warn when this package is absent on linux OS.

**Comment by Satlinker** [comment]
Just found it, (hours later). Doesn't work anyway, I guess because of the conversion of sf2 to sfz. I try again a little bit
thanks

**Comment by redtide** [comment]
There is no such conversion, ATM sfizz doesn't imports sf2 soundfonts.

**Comment by paulfd** [comment]
Single file import is in though. For sf2 you will need a converter like Polyphone.
