### ISSUE TITLE
Some sfz instrument shows key switches at wrong places on the keyboard

### ISSUE THREAD

**Issue by atsushieno** [sfztools/sfizz#742]
I'm not sure if this is a problem in sfz or sfizz UI, but anyways, some instrument seems to show key switches at wrong range areas. I'm experiencing it with UI Standard Guitar KSOP: https://unreal-instruments.wixsite.com/unreal-instruments/standard-guitar (caution: the instrument is huge, 700MB-ish)

I'm on Linux now and cannot really test how it loads on Sforzando (which the instrument is confirmed by the sfz creator), but I see the key switch ranges on my desktop are different from the screenshot on the instrument website. Here is an sfizz sshot from my desktop:

![image](https://user-images.githubusercontent.com/53929/112290104-3f6c1200-8cd2-11eb-8e43-5448d752d62f.png)

UI METAL GTX, a similar sfz instrument on the same website shows the keyswitches as expected, so it is not a simple range mismatch. I have no further idea on what are different (no right idea on how key ranges are specified in the sfz files) so I'd leave further investigation to you.

Confirmed build: 858028f. Loaded sfizz vst3 from JUCE AudioPluginHost on Linux.

**Comment by jpcima** [comment]
They were not shown in the case where key ranges and switch ranges overlapped.
For now a solution is implemented which shows these keys in a distinct color.

![Capture d’écran_2021-03-24_12-48-25](https://user-images.githubusercontent.com/17614485/112305913-868cdf80-8c9f-11eb-806b-cc83dab693c8.png)

**Comment by atsushieno** [comment]
Hey thanks for the fix, it works fine and looks good enough to me. Is this left open because it is not an actual fix, or design confirmation needed, or for whatever else? (I guess the second one)

**Comment by alcomposer** [comment]
Given the use of colour here (which would be better reserved) I can't help think keyswitches should always display, regardless of competing range.

**Comment by paulfd** [comment]
I guess we can close this and iterate later as needed. Thanks/どうも @atsushieno !
