### ISSUE TITLE
Assigning client name via command line

### ISSUE THREAD

**Issue by lminiero** [sfztools/sfizz#75]
Hi all,

first of all, thanks a lot for working on this! I've recently discovered sfizz thanks to Michael Wellis' excellent Ardour template for VPO, and I started using it for all my SFZ needs, especially considering LinuxSampler was crashing a bit too often on my old laptop.

I was wondering if you could add a command line option to `sfizz_jack` to provide a custom name to use for the Jack client: at the moment it defaults to an hardcoded `sfizz`

    auto defaultName = "sfizz";
    jack_status_t status;
    client = jack_client_open(defaultName, JackNullOption, &status);

which can be problematic when you open multiple clients at the same time, or want to be able to quickly create connections with other applications. This looks like a simple task so I can take care of that as well and prepare a pull request, if you let me know which branch you'd like me to target.

Thanks!

**Comment by lminiero** [comment]
Just prepared this very short diff on the (slightly older) commit of the `develop` branch I'm on, and it seems to be working as expected:

```
diff --git a/clients/jack_client.cpp b/clients/jack_client.cpp
index 12344e2..00387bf 100644
--- a/clients/jack_client.cpp
+++ b/clients/jack_client.cpp
@@ -163,6 +163,7 @@ static void done(int sig [[maybe_unused]])
     // exit(0);
 }
 
+ABSL_FLAG(std::string, client_name, "sfizz", "Jack client name");
 ABSL_FLAG(std::string, oversampling, "1x", "Internal oversampling factor (value values are x1, x2, x4, x8)");
 ABSL_FLAG(uint32_t, preload_size, 8192, "Preloaded value");
 
@@ -171,10 +172,12 @@ int main(int argc, char** argv)
     // std::ios::sync_with_stdio(false);
     auto arguments = absl::ParseCommandLine(argc, argv);
     auto filesToParse = absl::MakeConstSpan(arguments).subspan(1);
+    const std::string clientName = absl::GetFlag(FLAGS_client_name);
     const std::string oversampling = absl::GetFlag(FLAGS_oversampling);
     const uint32_t preload_size = absl::GetFlag(FLAGS_preload_size);
 
     std::cout << "Flags" << '\n';
+    std::cout << "- Client name: " << clientName << '\n';
     std::cout << "- Oversampling: " << oversampling << '\n';
     std::cout << "- Preloaded Size: " << preload_size << '\n';
     const auto factor = [&]() {
@@ -216,9 +219,8 @@ int main(int argc, char** argv)
     std::cout << '\n';
     // std::cout << std::flush;
 
-    auto defaultName = "sfizz";
     jack_status_t status;
-    client = jack_client_open(defaultName, JackNullOption, &status);
+    client = jack_client_open(clientName.c_str(), JackNullOption, &status);
     if (client == nullptr) {
         std::cerr << "Could not open JACK client" << '\n';
         // if (status & JackFailure)
```

**Comment by paulfd** [comment]
Hi! 

Thanks alot! You can target the develop branch no problem. We will merge it soon since there are alot of changes queued in develop already :)

If you can open a PR that would be great! There should be no issue rebasing the jack client has not been touched in a while.

**Comment by lminiero** [comment]
@paulfd thanks for the quick feedback! I just created the PR :+1:

**Comment by paulfd** [comment]
Merged. Thanks alot!
