### ISSUE TITLE
Change function arguments for MIDI channel  to zero-based

### ISSUE THREAD

**Issue by SpotlightKid** [sfztools/sfizz#8]
Currently the `channel` argument for the `sfizz_send_*` functions uses 1-based counting of MIDI channels.

I suggest changing this to zero-based counting, i.e. 0-15, since this is how the channel is represented in the MIDI status byte and how most software stores and passes it internally.

IMO, 1-based counting should only be used when presenting a MIDI channel number to the user.

**Comment by paulfd** [comment]
Agreed!

**Comment by paulfd** [comment]
Should be ok on develop as of c6a9ba88da6b8a64b3a4e0f98a215e6baf62379a
