### ISSUE TITLE
crash on note play with mf-taiko-drum-ogg

### ISSUE THREAD

**Issue by falkTX** [sfztools/sfizz#804]
I have this tiny sfz file (not sure the origins now) which when loaded in sfizz it instantly crashes when playing a note.
```
python3: /Shared/Personal/FOSS/Repo/Debian-Plugins/sfizz/external/abseil-cpp/absl/types/span.h:278: absl::lts_20210324::Span<T>::operator[](absl::lts_20210324::Span<T>::size_type) const [with T = const float; absl::lts_20210324::Span<T>::reference = const float&; absl::lts_20210324::Span<T>::size_type = long unsigned int]::<lambda()>: Assertion `false && "i < size()"' failed.
Aborted
```

sfizz build fresh from today.

since the sfz kit is so small, I will just upload it in here

[mf-taiko-drum-ogg.tar.gz](https://github.com/sfztools/sfizz/files/6287426/mf-taiko-drum-ogg.tar.gz)

**Comment by redtide** [comment]
For reference the samples lib is a CC-BY-3.0 coming from [Fiedler Audio](https://www.fiedler-audio.de/creative-commons-library/).

**Comment by jpcima** [comment]
The problem is with `sampleEnd`, it fills the value -2 in the indices array
`fill<int>(indices->subspan(i), sampleEnd);`

**Comment by jpcima** [comment]
There are 2 aspects to this problem
- [X] sfizz is not robust against a failure to load a file, it will produce a crash as reported
- [X] stb_vorbis produces an "outofmem" error, this requires us to allocate a larger temporary memory for OGG decoding

**Comment by jpcima** [comment]
The sound files load now, but there's another issue.
This instrument has a very long release time.
When opening the default sfizz at polyphony 64, playing lots of notes up to the hard limit, the voice thief fails to do its job on new notes, and the instrument becomes pretty much silent. @paulfd

**Comment by paulfd** [comment]
I'll have a look at it !

**Comment by paulfd** [comment]
I think what the original author wanted is to have `loop_mode=one_shot` rather than `ampeg_release=100`. Nevertheless such a long release time had impacts which are now hopefully resolved.
