### ISSUE TITLE
Absolute path in sfizz.pc

### ISSUE THREAD

**Issue by tank-trax** [sfztools/sfizz#83]
I built and installed on Debian 10 and the file
`/usr/local/lib/pkgconfig/sfizz.pc` was correct (verified)

However the `sfizz.pc` in the release `sfizz-v0.2.0-linux-amd64.tar.gz` has the following lines

```
prefix=/home/travis/build/sfztools/sfizz/build/sfizz-v0.2.0-linux-amd64
exec_prefix=/home/travis/build/sfztools/sfizz/build/sfizz-v0.2.0-linux-amd64
```
which should be 
```
prefix=/usr/local
exec_prefix=/usr/local
```

**Comment by redtide** [comment]
Thank you for reporting, I've just fixed the packages and the Travis CI scripts with the above commit of yesterday, hope is OK now!

**Comment by tank-trax** [comment]
I build sfizz locally it via git clone, was just checking out file paths and noticed that, thought I'd mention it. Looks good now.
