### ISSUE TITLE
To do before release 1.0.0 / suggestions

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#830]
- [x] Bump LV2 minor version
- [x] Bump libsfizz.so shared library version
- [x] Review the API doc comments ; there are cases of mismatched `@since` tags between h/hpp, check which is correct and edit accordingly
- [x] Suggestion to change 7bit `char` arguments (velocity, aftertouch ...) to `int`.
- [x] Suggestion to have a tempo API based on BPM, the unit that SFZ uses, rather than "samples per beat". (+deprecate the latter?)
- [x] ~~Have LV2 restore parameter to defaults, when not present in the save blob, for compliance to the spec~~
- [x] Credit faust-libraries and authors in the README
- [x] Missing `exportMidnam()` in C++ API
- [x] https://github.com/sfztools/sfizz/wiki/To-deprecate-on-next-API-ABI-break

**Comment by paulfd** [comment]
>     * [ ]  Suggestion to change 7bit `char` arguments (velocity, aftertouch ...) to `int`.

In the API?

>     * [ ]  Suggestion to have a tempo API based on BPM, the unit that SFZ uses, rather than "samples per beat". (+deprecate the latter?)

Sure, go for it. If we go for 1.0 now's the time to deprecate stuff.

**Comment by redtide** [comment]
There was the JSON documentation API files Python script generator (#164), though I think is not a priority now, the files can still be tweaked manually.

**Comment by paulfd** [comment]
https://github.com/sfztools/sfizz/wiki/To-deprecate-on-next-API-ABI-break also !
