### ISSUE TITLE
Extended CCs are not properly set for "non-modulation" opcode

### ISSUE THREAD

**Issue by paulfd** [sfztools/sfizz#853]
Opcodes like `offset_cc`, and any of them that do not go through the modulation matrix, are not currently properly affected by extended CCs. The internal reason is as follows: since most of these CCs are "per-voice", the modulation matrix builds them on the fly when requested by a voice, but the CCs that are not modulated on the other hand fetch the CC state from the `MidiState` which is not updated.

I have tested that Sforzando does not react to say
```
<region> start_locc133=100 start_hicc133=127 sample=...
```
Given this, I am tempted to provide as a fix that we indeed fill the MidiState with the proper value for the extended CCs.
Also related, Sforzando does not show extended CCs in the UI.

**Comment by kinwie** [comment]
Sforzando shown only cc 128 and 129 on its UI. Others are hidden
