### ISSUE TITLE
VST3 X11 runloop issues with timers

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#861]
There seems to remain issues in the X11RunLoop component.
Reaper crashes occasionally, with different backtraces, but timers seem often involved somewhat.

This is the deal with `X11RunLoop`: it's a utility class which serves to implement Timer and FD event handling, which VST3 Linux requires to do at plugin-side.

The one which comes in VST3 SDK is flawed, it's unable to handle unusual edge cases and crashes.
For example, the case when you want to unregister a timer inside a timer callback.

I've made a custom implementation to cover some of these weird cases but it's not yet bulletproof I think.
It used a strategy which puts event handlers in a "zombie" state before clearing them from the vector.

As a wild guess, I think this might have to do with a handler getting re-registered after being unregistered into a zombie, all during the same iteration of event handling.

**Comment by paulfd** [comment]
I had one bug yes.

**Comment by jpcima** [comment]
Let's consider it fixed, reopen in case of new problems.
