### ISSUE TITLE
Linux binaries are dynamically linked

### ISSUE THREAD

**Issue by x42** [sfztools/sfizz#867]
Please statically link Linux binaries just like you do with the  windows binaries, and only depend on mandatory system libs (here: libX11, libc).

Otherwise this can cause conflicts with hosts or other plugins in the same memory-space and also only works on a limited set of target systems.

**Comment by paulfd** [comment]
Which library is causing the issue?

**Comment by x42** [comment]
from #ardour IRC earlier tonight
```
22:56 < avlinux> Its not happy about libxcb utis
```

but generally libpango and libglib are likely to cause issues, too.

**Comment by paulfd** [comment]
Ok. Note that we also have packages/repositories at https://software.opensuse.org//download.html?project=home%3Asfztools%3Asfizz&package=sfizz

Seems the issue is mostly in the linux binaries on github.

**Comment by x42** [comment]
Well, yeah, I just thought the distro agnostic binaries should not depend on any 3rd party (distro provided) libraries.

**Comment by paulfd** [comment]
I removed the binaries from the Release page and made the OBS builds more prominent there.
