### ISSUE TITLE
Release opcode rt_decay is broken

### ISSUE THREAD

**Issue by ghost** [sfztools/sfizz#881]
Release sounds no longer decrease in volume based on the time since attack: https://sfzformat.com/opcodes/rt_decay. Worked in v1 but latest git doesn't not.

**Comment by jpcima** [comment]
This test works. (although, the volume compared to aria is a little mismatched)
~~https://github.com/sfz/tests/blob/master/sfz2%20basic%20tests/03%20-%20release%20triggers/08%20-%20release%20trigger%20and%20key%20switches.sfz~~

Do you have a file that we can try?

**Comment by ghost** [comment]
It's specifically with rt_decay opcode which I don't see in your test file.

**Comment by jpcima** [comment]
I linked the wrong one, sorry about that.
https://github.com/sfz/tests/blob/master/sfz2%20basic%20tests/03%20-%20release%20triggers/00%20-%20release%20trigger%20decay.sfz

**Comment by ghost** [comment]
You could use the small harpsichord subset I provided a while ago if you still have it?

**Comment by jpcima** [comment]
Note:
- [ ] the rt_decay does not activate under polyphony set to 1, in sforzando it does (@paulfd)

(However the context of this issue is max voices set to 64, I'm not yet able to reproduce it.)

**Comment by paulfd** [comment]
This was fixed by 87f3a2b2 right? (not the polyphony thing though)

**Comment by ghost** [comment]
Yes!

C

-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


May 21, 2021, 23:47 by ***@***.***:

**Comment by paulfd** [comment]
The commit also fixed the polyphony issue I think.
