### ISSUE TITLE
No sound from VST3 sfizz 1.0.0 plugin instances when loading Ardour project

### ISSUE THREAD

**Issue by xard-dev** [sfztools/sfizz#886]
When restoring saved project using Ardour 6.6 and self compiled sfizz vst3 version 1.0.0 midi state is not restored properly. This results all sfizz plugin instances being completely silent.

Investigating further it looks like that undefined basic midi cc attributes like expression, volume, panning etc are set to 0 during initialization.

This didn't happen with sfizz 0.5.0 lv2 plugin instances.

**Comment by jpcima** [comment]
This was found recently and a fix was posted. #872
Can you check latest?

**Comment by xard-dev** [comment]
@jpcima yes those two commits fixed the issue: I created local branch of the 1.0.0 tag and then cherry picked those two commits 13dfddae645464e89f7a383042e416365948f124 and 13dfddae645464e89f7a383042e416365948f124.

After compilation the midi cc values are not unexpectedly set to 0 when loading the project anymore.
