### ISSUE TITLE
Linux build fails with clang on ARM

### ISSUE THREAD

**Issue by cmdrf** [sfztools/sfizz#890]
When building with clang on an armhf system, I get:
```
[ 61%] Building CXX object src/CMakeFiles/sfizz_internal.dir/sfizz/Synth.cpp.o
In file included from /home/redacted/sfizz/src/sfizz/Synth.cpp:30:
In file included from /home/redacted/sfizz/src/sfizz/Interpolators.h:68:
In file included from /home/redacted/sfizz/src/sfizz/Interpolators.hpp:8:
In file included from /home/redacted/sfizz/src/sfizz/WindowedSinc.h:121:
In file included from /home/redacted/sfizz/src/sfizz/WindowedSinc.hpp:11:
/home/redacted/sfizz/external/simde/simde/x86/sse2.h:2633:21: error: use of undeclared identifier 'vcvtnq_s32_f32'; did you mean
      'vcvtq_s32_f32'?
      r_.neon_i32 = vcvtnq_s32_f32(a_.neon_f32);
                    ^~~~~~~~~~~~~~
                    vcvtq_s32_f32
/usr/include/clang/7.0.1/include/arm_neon.h:4571:16: note: 'vcvtq_s32_f32' declared here
__ai int32x4_t vcvtq_s32_f32(float32x4_t __p0) {
               ^
1 error generated.
```

I'm using a Debian 10 variant called Armbian and a backported clang-11:
```
$ clang-11 -v
Debian clang version 11.0.1-2~bpo10+1
Target: armv7l-unknown-linux-gnueabihf
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/arm-linux-gnueabihf/8
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/8
Selected GCC installation: /usr/bin/../lib/gcc/arm-linux-gnueabihf/8
Candidate multilib: .;@m32
Selected multilib: .;@m32
```

Interestingly it works on an arm64 system (otherwise same Linux distribution).

Could this be a simde issue? I already tried the current master, but it doesn't fix the issue. Or maybe clang is at fault?

**Comment by jpcima** [comment]
Hi, I just notice you have indeed a clang-11 backport, but your trace refers to the header `arm_neon.h` from clang 7.0.1. This seems like an anomaly.

Can you recheck your installation, or that your build uses the actually proper compiler.
(This might help: `cmake -DCMAKE_C_COMPILER=clang-11 -DCMAKE_CXX_COMPILER=clang++-11`)

Although, if this produces errors with clang7, this likely would be a simde bug.

**Comment by cmdrf** [comment]
Sorry, I just mixed up the outputs. clang-7 and clang-11 produce the exact same result. I upgraded to clang-11 after clang-7 failed to see if this is a clang-7 issue. Here is the output of clang-11:
```
[ 59%] Building CXX object src/CMakeFiles/sfizz_internal.dir/sfizz/Synth.cpp.o
In file included from /home/redacted/sfizz/src/sfizz/Synth.cpp:30:
In file included from /home/redacted/sfizz/src/sfizz/Interpolators.h:68:
In file included from /home/redacted/sfizz/src/sfizz/Interpolators.hpp:8:
In file included from /home/redacted/sfizz/src/sfizz/WindowedSinc.h:121:
In file included from /home/redacted/sfizz/src/sfizz/WindowedSinc.hpp:11:
/home/redacted/sfizz/external/simde/simde/x86/sse2.h:2633:21: error: use of undeclared identifier 'vcvtnq_s32_f32'; did you mean 'vcvtq_s32_f32'?
      r_.neon_i32 = vcvtnq_s32_f32(a_.neon_f32);
                    ^~~~~~~~~~~~~~
                    vcvtq_s32_f32
/usr/lib/llvm-11/lib/clang/11.0.1/include/arm_neon.h:5698:16: note: 'vcvtq_s32_f32' declared here
__ai int32x4_t vcvtq_s32_f32(float32x4_t __p0) {
               ^
1 error generated.
```

**Comment by jpcima** [comment]
Does the intrinsic `vcvtnq_s32_f32` appear in your file `arm_neon.h`?
I've got clang `11.1.0` here, and it does.

That file which according to your log is located at: `/usr/lib/llvm-11/lib/clang/11.0.1/include/arm_neon.h`

If it's not, this problem has to be reported at simde.

**Comment by jpcima** [comment]
It's expected to be fixed in the latest, following the simde update.

**Comment by cmdrf** [comment]
Cool, thanks! I was about to compile the simde test suite, but 256 MByte of RAM was just not enough...
