### ISSUE TITLE
Frequency Hz parameter not working in VST3 under Ardour

### ISSUE THREAD

**Issue by AlexMitchellMus** [sfztools/sfizz#892]
In Ardour & VST3, the parameter of `Frequency` doesn't change sfizz tuning.

The value of 352.9 Hz is played as 440 Hz:
![sine_352 9hz](https://user-images.githubusercontent.com/12004932/118122583-337b1180-b432-11eb-8ef5-e4ece680ad0e.png)
![piano_352 9hz](https://user-images.githubusercontent.com/12004932/118122589-34ac3e80-b432-11eb-8ba0-0c5a4f5167ad.png)

LV2 Ardour does not exhibit this issue:
![Screenshot from 2021-05-13 20-35-31](https://user-images.githubusercontent.com/12004932/118122846-9371b800-b432-11eb-9cf7-bf3d7045d258.png)

**Comment by jpcima** [comment]
This affects all parameters without `kCanAutomate`.
Ardour, as of 6.6, rejects these parameters as being editable.
