### ISSUE TITLE
Extended CC revision

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#901]
Some issues still in the extended CC. Some examples :

This is working,
```
<region>
sample=snare.wav
loop_mode=one_shot
pitch_keytrack=0
amp_veltrack=0
amplitude_oncc133=100
```

This is not working,
```
<region>
sample=*sine
pitch_keytrack=0
amp_veltrack=0
ampeg_release_oncc133=5
```

In 2nd example, lower keys will have shorter release and higher keys will have longer release, in the range of,
key 0 - release 0
key 127 - release 5
Right now with sfizz, it's not modulate over the keyboard range. It still the same as common cc, changes are made with the CC knob (all keys have the same release time)

I'll check other CC numbers also

**Comment by paulfd** [comment]
I'm closing this because I think it got fixed by an earlier patch ! The second example works right now. If needed you can reopen @kinwie.
