### ISSUE TITLE
Edit File opens the SFZ up in the wrong app on Mac

### ISSUE THREAD

**Issue by MTornPDX** [sfztools/sfizz#904]
This might be Mac specific, I think I saw a similar issue for some other OS a while ago.
Selecting Edit File will open the active SFZ up in TextEdit, even if you have set all .sfz files to open up in a different text editor by default in the finder. In my case I use Visual Studio Code, and double clicking an SFZ will automatically open it in VSC.
Sforzando will also edit it in VSC, but Sfizz will still use TextEdit.

In the UI, a small button that does the same thing (Edit File) when clicked would be very handy!

**Comment by jpcima** [comment]
It identifies which software is associated with plain-text files for editing, and it uses this one.
The reasoning was that, if asking the system just open the SFZ file (as in a double click), perhaps it would open it in a program which is not an editor. (eg. a player)

Now in Apple specifically, it looks up the association by the `kUTTypePlainText` [UTI] and the `editor` role.
Perhaps there would be an applicable UTI for SFZ files.

[UTI]: https://en.wikipedia.org/wiki/Uniform_Type_Identifier

**Comment by MTornPDX** [comment]
Ah, I see, Sfizz looks for the default setting for PLAIN-TEXT files... That doesn't work well for me - for plain text I wouldn't want to use Visual Studio Code as my default. I have my computer set up to default to VSC only for .sfz files.
I can't think of any free standing SFZ player I'd want to double click to open. It'll pretty much alway be opened in VSC.

Ideally Sfizz would ask which helper text editor we want to use, but if it doesn't, it's not a huge deal, I can just open up the .sfz files manually from the finder.

**Comment by jpcima** [comment]
A solution is implemented which queries CoreServices, to get the adequates editor for SFZ files.

**Comment by MTornPDX** [comment]
This works perfectly now, thanks!
