### ISSUE TITLE
note_polyphony and note_selfmask doesn't seem to work

### ISSUE THREAD

**Issue by MTornPDX** [sfztools/sfizz#914]
When setting note_polyphony to 1, Sfizz still doesn't limit polyphony for repeated instances of the same note.

note_selfmask=on should allow multiple repeated notes to play if the new notes are lower in velocity than the previous notes, but should cut off previous notes if the new ones are higher in velocity.

note_selfmask=off should cut off ALL previous notes on repeated note hits (if note_polyphony=1).

Sfizz plays repeated notes with full polyphony regardless of these settings.

**Comment by paulfd** [comment]
Relevant tests are here and below: https://github.com/sfztools/sfizz/blob/acd866fd3d247d2fc659593cac96e88e801c29e2/tests/PolyphonyT.cpp#L218

I'll check this behavior to see if there are things that are not covered.

**Comment by paulfd** [comment]
> When setting note_polyphony to 1, Sfizz still doesn't limit polyphony for repeated instances of the same note.
> 
> note_selfmask=on should allow multiple repeated notes to play if the new notes are lower in velocity than the previous notes, but should cut off previous notes if the new ones are higher in velocity.
> 
> note_selfmask=off should cut off ALL previous notes on repeated note hits (if note_polyphony=1).
> 
> Sfizz plays repeated notes with full polyphony regardless of these settings.

Do you have an example? After some quick testing it looks like the behavior is similar between ARIA and sfizz for what I tried:
```
<region> sample=crash.wav note_polyphony=1 note_selfmask=on loop_mode=one_shot
```

If `note_selfmask=off` repeated notes will off the previous ones. If `note_selfmask=on` you can stack notes with decreasing velocity. A higher velocity note will steal the polyphony of a lower velocity one.

**Comment by MTornPDX** [comment]
Let's see if this works as an example. In this test, repeated notes does NOT off the previous ones on Sfizz, but does in Sforzando. The only circumstance where Sforzando lets previous notes ring out is when note_selfmask is changed to "on", and the repeated notes are of lower velocity than the first. That's the proper behavior, right?

Perhaps this is related to that Sfizz lets the release phase of previous notes be polyphonic even when polyphony=1?
It sounds like at your end Sfizz DOES off previous notes? That's weird.

The disco tom pitch sweep in the example is so you can hear both the old notes and the repeated new ones:

```
<region>
sample=*triangle
ampeg_release=10
pitcheg_release=10
pitcheg_depth=1200
note_polyphony=1
note_selfmask=off
```
