### ISSUE TITLE
polyphony opcode inactive after key release

### ISSUE THREAD

**Issue by MTornPDX** [sfztools/sfizz#915]
When setting polyphony=1, Sfizz limits the polyphony only on keys currently held.
If you have a long ampeg release and let go of the key (the sound keeps ringing), new notes do not cut off the previous ringing notes.

**Comment by paulfd** [comment]
Yes most polyphony checks ignore released voices in their counting right now, which allows for clickless "killing" of notes. I have to check the behavior of other implementations.

**Comment by paulfd** [comment]
When using
```
<region> sample=*saw ampeg_attack=0.1 ampeg_release=10 polyphony=1
```
in sforzando it does indeed cut the release phase short.
I think we'll need to consider an `offed` state on top of the released state for the voices.

**Comment by paulfd** [comment]
Should be ok now you can reopen if it's not !

**Comment by MTornPDX** [comment]
I could only test it briefly today, but it looks like both this and note_selfmask is working perfectly now. Thanks!
