### ISSUE TITLE
Version information in GUI (major.minor, LV2/VST3)

### ISSUE THREAD

**Issue by mikelupe** [sfztools/sfizz#918]
First of all thanks for sfizz, this very compact sampler plugin.

Is there a way of getting the version information of the binary? It would help having this in the gui, I missed it while updating, but it's also handy when trying to clean up the plugin mess that sometimes happens through the freedom of different plugin folders and different installation methods.  

"objdump -T sfizz.so | grep text" delivered some information for VST3, but it seemed a bit contradictory (or maybe it's not intended for a version check at all).

Thanks

**Comment by alcomposer** [comment]
Click on the SFIZZ logo for `about sfizz`
![Screenshot from 2021-06-21 20-27-54](https://user-images.githubusercontent.com/12004932/122751702-40abdb80-d2cf-11eb-883e-fe488fd78968.png)

**Comment by mikelupe** [comment]
Wow - this is the first thing I usually try, thanks. Could it be this was missing in the 0.5.x version? It almost cant be I double-clicked that fast, that I didnt realize there was a info screen ;)

**Comment by mikelupe** [comment]
It indeed seems this was only added in V1.0.0, that's why it really wasn't helpful for me, coming from 0.5.x

From the release notes of V1.0.0: 
"Added an info panel in the plugin UI (#793 #792 #791 #789 #788 #787 #782 #779 #773)"
--> https://github.com/sfztools/sfizz/pull/779

**Comment by alcomposer** [comment]
Ah! Yes I didn't know which version you were on sorry.

Get into the V1 good stuff.

**Comment by mikelupe** [comment]
And apparently 1.x solved a problem I had, where I was forced to reload a sample after some not reproduceable actions in Ardour (looping? whatever).

Indeed good stuff! :)
