### ISSUE TITLE
Support for Polyphonic Aftertouch

### ISSUE THREAD

**Issue by redtide** [sfztools/sfizz#92]
I would be interested in seeing Polyphonic Aftertouch as well. Devices such as the Roli Seaboard support it, as do any devices that support MPE. (The list is growing every day).

I understand that this would be a long term goal.

_Originally posted by @alcomposer in https://github.com/sfztools/sfizz/issues/7#issuecomment-561137996_

**Comment by AlexMitchellMus** [comment]
Polyphonic Aftertouch would be a non-MPE thing.
In MPE, each MIDI event is it's own channel, and mono-aftertouch is used. Which means all polyphony is created in MPE from layering MIDI channels. Channel 1 is used for control, so we end up with 2-16. However also remember that can be changed in the device settings, so it's best to keep it flexible to how any plugin is driven.

Polyphonic Aftertouch is reserved- and not used currently in MPE.

This isn't to say it isn't a good idea, as IIRC an MPE device can be run in non-MPE mode, and send Polyphonic Aftertouch. 

MPE also allows Slide (moving the finger up/down on the keywave) to be either relative - or absolute. Which means that its either -64<0<64 relative (from MIDI event on) or absolute 0<127 (bottom of keywave being 0, top being 127). https://support.roli.com/support/solutions/articles/36000025050-slide-absolute-vs-relative

**Comment by redtide** [comment]
> I would be interested in seeing Polyphonic Aftertouch as well. Devices such as the Roli Seaboard support it, as do any devices that support MPE. (The list is growing every day).

Some Roland electronic drum modules (not sure if others) use it for cymbal choking, so it might be useful also for that (even if maybe with a minimal use of it)

From [#7 (comment)](https://github.com/sfztools/sfizz/issues/7#issuecomment-568221388)

**Comment by redtide** [comment]
It's not the scope of this issue, but as the hardware question came up: a relatively inexpensive and recent device that emits Poly Aftertouch messages is the Arturia Microfreak.

_Originally posted by @sagamusix in [#7 (comment)](https://github.com/sfztools/sfizz/issues/7#issuecomment-592946629)_

**Comment by redtide** [comment]
As a side note on v1 specification (see <https://sfzformat.com/opcodes/lopolyaft> and <https://sfzformat.com/legacy/>) the incoming note of the message is ignored, which makes useless the use of this opcode on Roland VDrums modules, where as tested by @kinwie and myself with a test file he made for cymbals choking, it works using Sforzando with the [SFZ extended CC](https://sfzformat.com/extensions/midi_ccs)130, so in this case it could be nice to have either the extended CC implemented or using v1 opcodes implemented without following the ignored note rule.

**Comment by kinwie** [comment]
A test file and description about Polyphonic Aftertouch usage for cymbal choke in edrums kit, which has been successfully tested by @redtide, in here :
https://github.com/kinwie/sfztest/wiki/Cymbal-choke-test-for-edrums-and-keyboard-mapping-mode

**Comment by paulfd** [comment]
@redtide @kinwie Do you have the test file at hand?

**Comment by paulfd** [comment]
Along with a midi capture it would be perfect :D

**Comment by paulfd** [comment]
Also, the fact that `on_cc130` is even a thing means that all the polyaftertouch messages for all notes are "merged" into a single CC. I wish I had keyboards and equipment that send these messages to check what they do...

**Comment by paulfd** [comment]
I've been trying sforzando, and there are alot of things that don't seem to respond as I thought. E.g. a simple thing like this
```
<region> sample=*sine pan_cc130=200 pan=-100
```

**Comment by kinwie** [comment]
> 
> 
> I've been trying sforzando, and there are alot of things that don't seem to respond as I thought. E.g. a simple thing like this
> 
> ```
> <region> sample=*sine pan_cc130=200 pan=-100
> ```

Hi Paul,
Yes, here with your above example
[Poly_aft_check_DropZone.zip](https://github.com/sfztools/sfizz/files/6249190/Poly_aft_check_DropZone.zip)
