### ISSUE TITLE
macOS pkg installer and dmg image

### ISSUE THREAD

**Issue by redtide** [sfztools/sfizz#93]
Currently we are providing `tar.gz` archives for both sfizz library and LV2 plugin.
On Windows we have an InnoSetup script to build an installer setup, via Travis-CI, for the LV2 plugin; it would be good to have one also on macOS.

On macOS does exists a procedure to create `.pkg` installer package files using [pkgbuild], [productbuild] and [pkgutil] tools; there are also some frontend utilities to simplify the process. I started using [macos-installer-builder] (here an [article] from the author) but it seems there is also another interesting one called [Packages].
The purpose is to create a final bash script to use in Travis-CI, so no GUI based builders.

As a side note, similar on InnoSetup on Windows, macOS packages can be publicly signed and an Apple Developer account is required to do it. On latest macOS versions signing is mandatory (see "[notarization]").

Another additional option could be to distribute the resulting package using a `dmg` image, usually built using [hdiutil]. This could be also achieved by using [create-dmg], "a shell script to build fancy DMGs", so it can be executed inside the CI build.

[pkgbuild]: https://www.unix.com/man-page/osx/1/pkgbuild/
[productbuild]: https://www.unix.com/man-page/osx/1/productbuild/
[pkgutil]: https://www.unix.com/man-page/osx/1/pkgutil/
[macos-installer-builder]: https://github.com/KosalaHerath/macos-installer-builder
[article]: https://medium.com/swlh/the-easiest-way-to-build-macos-installer-for-your-application-34a11dd08744
[Packages]: http://s.sudre.free.fr/Software/Packages/about.html
[hdiutil]: https://redtide.github.io/dev-docs/en/deploy/macos-dmg
[notarization]: https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution
[create-dmg]: https://github.com/andreyvit/create-dmg

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/master/installer_mac/make_installer.sh

there's a bash script we use to make an (unnotarized) installer for surge if that helps. Once we have that built with a stable web address, it was just a few hops to get it into home-brew too.

**Comment by redtide** [comment]
Thank you @baconpaul!

**Comment by redtide** [comment]
I guess I can close this now, after a lot of work done by different people to manage Apple's "monetarization" madness.
