### ISSUE TITLE
EQ types lshelf and hshelf has really weird eq_bw response

### ISSUE THREAD

**Issue by MTornPDX** [sfztools/sfizz#937]
I've been playing with the EQ opcodes today. They are hugely useful.
The regular default parametric response works pretty well as it is. It's a bit strange to define the bandwidth by octaves, rather than the more commonly used Q value. You have to think backwards, in that a larger eqx_bw value produces a wider boost/cut, while on a studio EQ a high Q value produces a sharper, more resonant peak.
Nonetheless, using an octave value for bandwidth is fairly intuitive, so no real problem there.

It's when using eqx_type=lshelf and hshelf where things get weird. In those two cases a higher eqx_bw value DOES produce a narrower bandwidth! But weirder than that, using the default bw value (1), gives you a super sharp, howling, resonant shelving EQ! Not exactly useful. You can tame it by defining a low bandwidth number. It seems that a value of about .2 gives you a good shelf, roughly equivalent to what a 12db q=1 studio shelf EQ would be.

If nothing else, the bw numbers for the shelving eq should be re-mapped to produce a basic standard shelf at the default (1) number, since often one might want to use it without defining the bandwidth at all.

**Comment by paulfd** [comment]
![shelves](https://user-images.githubusercontent.com/15227713/141613944-8f169f85-2363-4495-849f-71a0ca0f2307.png)

This is with
```sfz
<region> sample=*noise eq1_gain=10 eq1_freq=5000 eq1_bw=1 eq1_type=hshelf 
```
I'd say even sforzando has it wrong, no? But definitely something isn't right with our filter :D

**Comment by paulfd** [comment]
@jpcima What's the source for this?

```
// a common function that computes the EQ shelf parameter
sfzGetQFromSlope(slope) = 1.0/sqrt((A+1.0/A)*(1.0/S-1.0)+2.0) with {
  // note(jpc) slope is a 0-1 control that is reduced into a domain of validity,
  //   and clamped to avoid the extremes at both sides.
  S = (slope*root) : max(1e-2) : min(root-1e-2);
  A = 10^(pkShGain/40);
  root = (A*A+1)/((A-1)*(A-1)); // the root of the expression under sqrt()
};
```

**Comment by paulfd** [comment]
Actually sfizz is really shelving, it's mostly the Q parameter that seems tuned wrong by the bandwidth. Sforzando seems to ignore the `hshelf` type and just put a regular EQ point there... Their filter type `hsh` does work as expected though.

**Comment by paulfd** [comment]
@MTornPDX can you try the above pull request builds? (#1027)

**Comment by MTornPDX** [comment]
I'd be happy to, but I'm not sure how. Is there a Mac version (AU or VST is fine) that I can download and test?

**Comment by paulfd** [comment]
https://ci.appveyor.com/project/SFZTools/sfizz/builds/41526380/artifacts

In general you can go to https://ci.appveyor.com/project/SFZTools/sfizz/history, and find the build of interest (or directly from the pull request). There's a small "Artifacts" tab that should contain a working installer for the branch.

**Comment by jpcima** [comment]
> @jpcima What's the source for this?
> 
> ```
> // a common function that computes the EQ shelf parameter
> sfzGetQFromSlope(slope) = 1.0/sqrt((A+1.0/A)*(1.0/S-1.0)+2.0) with {
>   // note(jpc) slope is a 0-1 control that is reduced into a domain of validity,
>   //   and clamped to avoid the extremes at both sides.
>   S = (slope*root) : max(1e-2) : min(root-1e-2);
>   A = 10^(pkShGain/40);
>   root = (A*A+1)/((A-1)*(A-1)); // the root of the expression under sqrt()
> };
> ```

This was from the `S` parameter which is specific for shelves, as seen in the RBJ document.
https://webaudio.github.io/Audio-EQ-Cookbook/audio-eq-cookbook.html

Regarding lsh/hsh vs lshelf/hshelf, it's possible there was a Cakewalk vs Aria difference there. I don't recall, this would have to be verified.

**Comment by paulfd** [comment]
Yeah I saw in the cookbook in the end. However what I did is remap the parameter to the `BW` one, since it's the common one in SFZ for the EQs---even though it may not be the most natural/sensible one for a shelving filter.

**Comment by paulfd** [comment]
I've tried both `hsh` and `hshelf` in ARIA for `eqN_type`, neither seemed to work.

**Comment by jpcima** [comment]
Yes because that must be cakewalk spec.
These are as filters only not EQ.

**Comment by paulfd** [comment]
sfzformat.com is a bit ambiguous then, I'll see to revise it.
