### ISSUE TITLE
set articulation not being recalled in SFZ patches using keyswitches

### ISSUE THREAD

**Issue by IsaakCode** [sfztools/sfizz#939]
I tried it using the Vibraphone - Keyswitch SFZ patch from the VCSL (v 1.2.2) library by Versilian. I played a MIDI sequence switching the articulation to "Hard Mallets". When I reload the project in my DAW, the set articulation will not be recalled. The keyswitch setting is not remembered and I get the initial setting of the patch.

Is this intended behaviour? Sure, I could add an extra note to my MIDI sequence telling Sfizz which keyswitch articulation to use, but find it preferable if the articulation that was last being used could be also recalled.

**Comment by paulfd** [comment]
It is expected to behave this way right now yes. Do you know how other keyswitchable samplers handle this?

**Comment by AlexMitchellMus** [comment]
This is the behaviour I would expect, and is what Sforzando exhibits.

Last keyswitch chosen (from midi / VKBD / drop-down menu) that is the set keyswitch if no keyswitches are chosen in the beginning of the track.

**Comment by paulfd** [comment]
> This is the behaviour I would expect.

Which one?

**Comment by AlexMitchellMus** [comment]
The last keyswitch set by the user would be default when reloaded, or playing back.

This would also override default keyswitch, as a user changing the plugin should be given greater priority.

**Comment by AlexMitchellMus** [comment]
If we take the Sforzando behaviour here, then on project load the last keyswitch set (any which way) will be remembered. 

This isn't without its issues, as a user would have to make sure to set a start keyswitch if it changes in a midi track. However I think as Sforzando has been around for quite a while, I haven't heard of users complaining about this behaviour.

Think of the last keyswitch set as a setting in sfizz. Any setting that is chanced by the user is remembered. So to should this be.

**Comment by IsaakCode** [comment]
Indeed, I'm used to and prefer the Sforzando behaviour, where the last used keyswitch is remembered, if no other keyswitch information is given within the MIDI data.

If a MIDI sequence switches the articulation, the composer would have to write the necessary MIDI data into his sequence anyway. From my personal experience the more common case: I just use one of the articulations and would like that used keyswitch to be properly recalled when opening the DAW project the next time.

**Comment by AlexMitchellMus** [comment]
Yes, setting one keyswitch in GUI, and not entering in midi keyswitches feels like a use case that can only be addressed with this solution.
