### ISSUE TITLE
build/sfizz.lv2/LICENSE.md says it is LGPLv2/v3 but it seems wrong

### ISSUE THREAD

**Issue by atsushieno** [sfztools/sfizz#940]
`build/sfizz.lv2/LICENSE.md` is generated from `plugins/lv2/LICENSE.md.in` which says:

> The `sfizz` LV2 plugin is able to be built statically against all its components,
> which is a desirable property for audio plugin hosts. These components include
> `libsndfile` from Erik de Castro Lopo (http://www.mega-nerd.com/libsndfile).
> `libsndfile` is distributed under the terms of the LGPL v2 or v3. As such,
> statically-linked LV2 version of `sfizz` are to be distributed under the terms
> of the LGPL-v3.0 license. You should be able to rebuild from source the sfizz LV2
> plugin using any `libsndfile` version you wish to use.

But now that libsndfile is optional and I actually disable it in my local build as it is by default, I assume it is not necessarily LGPL anymore. At least it does not seem to be due to libsndfile anymore.

It's likely complicated because we can still enable libsndfile, so I'm not sure how you'd improve this. Probably updating the description conditional would suffice?

confirmed with 6b01bde.

**Comment by paulfd** [comment]
Hi @atsushieno !

Yes you're right, we have to correct this.

**Comment by paulfd** [comment]
@atsushieno is #943 clearer?

**Comment by atsushieno** [comment]
Yes, it is clear enough! Thank you.
