### ISSUE TITLE
Use a standard license

### ISSUE THREAD

**Issue by kmturley** [sfztools/sfizz#951]
License file is here:
https://github.com/sfztools/sfizz/blob/develop/LICENSE.md

But GitHub detect as custom other license:
https://api.github.com/repos/sfztools/sfizz/license

This is problematic when using the GitHub API to categorize plugins by license type. Compare to a standard license API request:
https://api.github.com/repos/asb2m10/dexed/license

Could you use a standard license from either:
https://choosealicense.com/

OR the list here:
https://api.github.com/licenses

Would be much appreciated!

**Comment by paulfd** [comment]
It is a standard license: [BSD 2-Clause](https://spdx.org/licenses/BSD-2-Clause.html). There is additional wording that's interesting for anyone without a clear understanding of licensing, which are still the majority of humans. I'll put it in the README and see if it makes Github API smarter. (edited)

**Comment by falkTX** [comment]
GitHub seems to hash the text and compared it to some own DB.
I had exactly the same thing myself, the "fix" was to remove the project name from the LICENSE file.
Which is pretty silly, yes. :shrug:

**Comment by paulfd** [comment]
The API appears to work now !

**Comment by kmturley** [comment]
Thank-you for making the change!
