### ISSUE TITLE
Sustain pedal issues in the LV2 plugin, and more general MIDI bindings questions

### ISSUE THREAD

**Issue by paulfd** [sfztools/sfizz#955]
The problem is as follows, please tell me if I miss anything:
- VST3 does not send midi _control_ data directly. You have to register a parameter as "bound" to a midi CC and the host will send changes to this parameter whenever a CC is received. If there are any collisions between a UI control, a MIDI control, and whatever the user is doing on a single parameter, it is the responsibility of the host to solve the collision.
- LV2 does not have this, but there is a `midi:binding` [property for ports](https://lv2plug.in/doc/html/group__midi.html) which supposedly should do the same (i.e. provide a default binding which removes the CC from the midi stream and let the host resolve collisions out of the plugin). Problem is no host seem to implement it, or implement it this way, yet sfizz-lv2 assumes they do unless you pass in a compile-time switch.

One immediate impact which is very apparent for users is that by default, sfizz-lv2 does not respond to the sustain pedal, which I think is not a good user experience. We can probably wait for the host to implement the midi bindings eventually, if ever, and just require users to manually map any other sfizz's "CCs" to actual controllers if they would want to, but sustain and sostenuto should probably be treated differently. I propose the following:
- When loading an SFZ file, track which CCs are used over all regions as sustain or sostenuto, and store them somewhere.
- In the LV2 UI and the VST UI, do not advertise the CC and sostenuto switches in the CC control list, although they could be mentioned somewhere else (or some other GUI element, as sforzando does).
- In the LV2 logic, if a CC is received on the midi stream _and_ it is a sustain or sostenuto, then it is passed as is to the engine. If it is not a sustain or sostenuto, it is ignored.

cc @jpcima @alcomposer

**Comment by paulfd** [comment]
Another thing I came across testing things out: Reaper cannot bind `lv2:Parameter`s as of version 6.32. They do not appear in the parameter list. Also, Ardour doesn't update the CC parameters touched from the plugin UI in the generic UI.

**Comment by jpcima** [comment]
Let's just do the PSA perhaps?
back when we requested the general opinion, PSA was adviced against and MIDI bindings suggested instead.
Following the moddevices discussions, I recall we went full circle on this topic, only to go back to the old way being "map it yourself at plugin-side". (unless I'm mistaken, then correct me)

**Comment by paulfd** [comment]
If we do the PSA, do we have a way in LV2 to properly update the UI ?

**Comment by jpcima** [comment]
> If we do the PSA, do we have a way in LV2 to properly update the UI ?

MIDI and PSA updates the controls here, in editor and generic UI.
Is there an issue on your side?

**Comment by paulfd** [comment]
Hm no no problem for me. If you're OK with this then we can do that (at least enable by default). I wonder still if it's not a good thing to "hide" the sustain CC from the control page. Or at least make it consistent: for now it will not appear by default, even though regions may be sustained, unless there are some `locc/hicc` or `start_locc/start_hicc` switches that e.g. piano libraries do.
