### ISSUE TITLE
Numpad input in VSTGUI

### ISSUE THREAD

**Issue by paulfd** [sfztools/sfizz#962]
Numpad input doesn't work for me, VSTGUI does not forward the keycodes.

**Comment by jpcima** [comment]
I've made a fix to that. But also it needs to rebase it to vstgui's latest.
[vstgui-numpad.diff.gz](https://github.com/sfztools/sfizz/files/7199459/vstgui-numpad.diff.gz)

**Comment by jpcima** [comment]
Patch to fix the vstgui latest, currently broken. Also it forces the upgrade to c++ 17.
https://github.com/steinbergmedia/vstgui/pull/229

**Comment by jpcima** [comment]
Fixed following the update #987

**Comment by paulfd** [comment]
I'm reopening to remember to patch the 4.10.2 VSTGUI fork until the corruption issue is handled with 4.11.
