### ISSUE TITLE
Implement CC140 - Key Delta

### ISSUE THREAD

**Issue by MTornPDX** [sfztools/sfizz#969]
Since SFZ doesn't have native portamento, I have been trying out some workarounds. I had good success using a pitch envelope that's scaled by cc140 - Key Delta.
Key Delta produces a number which is proportional to the difference between the previous key number and the current one. It can also go negative (there is a more upbeat cousin of this, cc141, which always stays positive).

Cc140 doesn't seem to be implemented yet (it works in Sforzando), but is quite useful, so that's my request.

**Comment by paulfd** [comment]
Do you happen to have a working example that I could test? As simple as possible :)

**Comment by MTornPDX** [comment]
Here's one, pared down as much as possible.
This one is polyphonic portamento, which is quite nice. You can do a polyphony=1, but to get the whole mono experience you should of course ideally pair portamento with a mono legato mode (envelopes not retriggering with legato notes).

<region> sample=*saw
eg1_level0=-1
eg1_time1=.1
eg1_level1=0
eg1_sustain=1
eg1_pitch_oncc140=100
