### ISSUE TITLE
GUI for the Standalone (and plugin)

### ISSUE THREAD

**Issue by tank-trax** [sfztools/sfizz#97]
really like this SFZ player. I use sforzando in Linux using WINE with much success and have followed the development of SFIZZ for a bit, I use Debian Buster at v10.3 and build it locally, both the standalone and LV2 work perfectly

my question is, are there plans to implement a GUI for the standalone and possibly the LV2?

**Comment by falkTX** [comment]
Is that really needed?

The generic GUI only needs options to load a file and a few controls.
As-is already works in Ardour, Qtractor, Carla and likely a few others.

**Comment by alcomposer** [comment]
Right, but I'm not sure if the published CC's can be displayed via LV2. It opens up a can of worms. LV2 does not have dynamic manifest in Ardour (and is depreciated AFAIK). And there would also be issues with CC values.

I think a simple host-like interface that was able to publish CC's along with loaded parameters would make sense longer term. Obviously if a GUI like Sforzando was needed then that would be a completely different conversation. I'm only discussing usability.

**Comment by paulfd** [comment]
@alcomposer for this we might use and develop things along midnam. The issue with GUI CC controls is that you'll make an arbitrary decision when collision occurs between GUI and host CC values, whereas if the host handles everything you are golden...

Couple this with bank names and we might just have a nice package for the host to create a GUI and handle all the required controls from its part.

@jpcima added midnam CC names but Ardour wasn't showing them in the interface last I tried.

**Comment by alcomposer** [comment]
Yes but MIDNAM will only display in the automation assignment menu of Ardour currently. As Ardour polls the plugin constantly for MIDNAM, it currently lacks a way of being able to regenerate only when the plugin changes.

**Comment by jpcima** [comment]
@alcomposer the plugin sends a reloading signal to Ardour when the data changes

From my point of view, the UI has true added value only in case of:
- plugin format like VST
- non MIDNAM host

@paulfd the UI can communicate CC sliders to DSP as MIDI messages

@falkTX one question, I note that Carla and other hosts permit selecting the file, but not reset it to empty after choosing. Should this be a possibility?
I think of the case where I want to set a file that's optional. (eg. a scala tuning file)

**Comment by falkTX** [comment]
That is not possible in Carla, not yet.

Carla's file selector for lv2 atom:Path is pretty minimal.
It is only available if there is no custom GUI, and only 1 path per plugin.

**Comment by tank-trax** [comment]
The LV2 does not appear to be possible to use sfizz in Carla as there is no way to find or load the SFZ file. Works in Qtractor and Ardour

**Comment by redtide** [comment]
The gear icon on Rack tab of the plugin.

**Comment by rghvdberg** [comment]
the gear is for UI, the wrench is for generic UI

**Comment by falkTX** [comment]
> the gear is for UI, the wrench is for generic UI

Exactly. you can tell I am a master of best user experience design ;)

**Comment by tank-trax** [comment]
am I missing something? load and save state are not active

![Screenshot_20200304_105100](https://user-images.githubusercontent.com/41337033/75897182-26ae6700-5e06-11ea-9678-3743fff8680c.png)

![Screenshot_20200304_105115](https://user-images.githubusercontent.com/41337033/75897187-28782a80-5e06-11ea-8040-2efff18f86dc.png)

also not possible using jalv.select

**Comment by redtide** [comment]
You asked to load a sfz file, that can be done from Rack by clicking on the gear icon...

**Comment by tank-trax** [comment]
The Gear is to display the GUI which as you can see is not active as there is no GUI. The Wrench brings up the properties and as stated there is no means to navigate to and select  the SFZ File

![Screenshot_20200304_105929](https://user-images.githubusercontent.com/41337033/75897973-6b86cd80-5e07-11ea-98db-3fc737c32719.png)

**Comment by falkTX** [comment]
What carla version is this? You need latest git or release candidate, the 2.1 series.

**Comment by tank-trax** [comment]
Version 2.0.0

**Comment by tank-trax** [comment]
I upgraded to the latest version of Carla via apt and yes the gear now loads the SFZ file. Thanks for the replies.

Just an FYI, sfizz loads well in Carla, jalv.select, Ardour, Mixbus and can be used in NSM

GUI not needed. Thanks.
