### ISSUE TITLE
Pan seems unresponsive to curvecc and extended MIDI CCs

### ISSUE THREAD

**Issue by MTornPDX** [sfztools/sfizz#976]
I'm trying to set up a scenario where the pan position is modulated in such a way that it tracks the keyboard position, but in the sense that for each octave it goes through the full left-right pan (and back again for the next octave).
I'm using this a lot for some moderate stereo spread in Reason's NN19 and NNXT - although in those it goes back and forth every octave, not every other.

It seems that assigning a curve and cc133 is the right method for this, however pan doesn't respond to the curve when using cc133. If I use cc1 instead, moving the mod wheel makes the pan move back and forth as expected. Here's a sample code:

```
<region> sample=*saw
pan=-100
pan_oncc133=200
pan_curvecc133=10

<curve>
curve_index=10
v000=0 v012=1 v024=0 v036=1 v048=0 v060=1 v072=0 v084=1 v096=0 v108=1 v120=0
```

**Comment by MTornPDX** [comment]
A few more tests show that it doesn't just affect pan, it has the same issue with others, like cutoff.
Also, I get the same results with cc131 (velocity) as with cc133 (keyboard tracking).

**Comment by paulfd** [comment]
Thanks for the report ! As a matter of fact I have `// Ignore the eventual curve for the extended CCs` as a comment around this part of the code. I can't remember why though. You can check #993?
