### ISSUE TITLE
Remember cc positions when reloading an instrument

### ISSUE THREAD

**Issue by MTornPDX** [sfztools/sfizz#977]
When designing a patch, I frequently will be tweaking settings for when a controller (usually mode wheel) is turned up.
But whenever making some adjustment to the code, the instrument of course will reload. It would be nice if this didn't reset the current cc positions.
As it is now, I have to bring up the mod wheel every time I make an adjustment and save, which is of course a bit annoying when fine tuning modulation assignments.

**Comment by paulfd** [comment]
Good point, I'll try to check this out.

**Comment by AlexMitchellMus** [comment]
This may be a bit tricky. But I think it's very much worth it to get it right.

I suppose the safest way would be to check the filename of the SFZ script? If it's the same then don't reset the controller state?

**Comment by paulfd** [comment]
Should be fine since the engine itself checks if the file changed (there's a `shouldReloadFile` API).

Edit: should add a `reloadCurrentFile()` API call that does not reset the midi state, but check what sforzando does with e.g. CC-triggered/depressed notes in this case.
