### ISSUE TITLE
Audio output and stem rendering does not reproduce sound correctly compared with sforzando

### ISSUE THREAD

**Issue by vbgfhfngfdtyreyt** [sfztools/sfizz#979]
Trying in both Windows and Linux, DAW is Reaper 6, VST3 version of plugin.

Download the Fluid R3 GM soundfont from either link:

https://member.keymusician.com/Member/FluidR3_GM/index.html
https://github.com/urish/cinto/blob/master/media/FluidR3%20GM.sf2

Files are slightly different, but same problem with either one.

Sound in question is "Castanets", but I have the issue with other sounds, including other soundfont files. (Downloaded from musical artifacts)  

I loaded up juicysf to play back the sf2 and rendered to a stem. Playback and stem both sound normal. 

I then use polyphone to convert the sf2 (just the one preset) to sfz, then used sforzando to play back the sfz, rendered to stem, sounds identical to the first stem. 

So far so good.

Finally, I loaded up sfizz and did the same thing, playing back the sfz, and it sounds very warped / distorted / ring modulated. It makes me worried that the sfizz playback code has some subtle bug somewhere that is compromising the quality of the audio playback. Same problem with stem rendering.

This also happens with other random soundfonts from musical artifacts. The sf2 sounds fine, the sfz converted sounds fine in sforzando, but the sfz sounds warped / distorted / ring modulated in sfizz.

As sforzando is not linux native, as an additional test I tried just sfizz in Linux and I get identical results to sfizz in Windows.

(As an additional control case, audio playback sound correct in polyphone for any of the soundfonts also)

**Comment by vbgfhfngfdtyreyt** [comment]
This seems to be fixed after uninstalling the tarball version of 1.0.0 and instead install the deb version. I will do some more testing to confirm.

**Comment by paulfd** [comment]
Is this OK in the end?

**Comment by paulfd** [comment]
Feel free to reopen if there's still issues !
