### ISSUE TITLE
note_offset and octave_offset "sticks" when changing patches

### ISSUE THREAD

**Issue by MTornPDX** [sfztools/sfizz#982]
When playing a patch that has, for example, octave_offset=1 to drop the sound one octave, and then switching to any other patch that does NOT have an octave_offset (which is most patches), the one octave drop keeps being active.

It's only when playing a patch that has octave_offset=0 (or restart the plugin) that things go back to normal.

The same goes for note_offset.

**Comment by pferrand** [comment]
Maybe check but I remember sforzando had some weird behavior with this.

**Comment by MTornPDX** [comment]
No idea, but I just checked the same files with Sforzando, and it doesn't have the sticking problem now.

**Comment by AlexMitchellMus** [comment]
Even if Sforzando did exhibit this behaviour, (which apparently it doesn't) it feels more like a bug to me.

**Comment by paulfd** [comment]
Should be OK with #994
