### ISSUE TITLE
Crashes in Reaper

### ISSUE THREAD

**Issue by SoliDeoGloria2** [sfztools/sfizz#983]
Hi!

I'd like to report that I encounter a lot of crashes in Reaper, just while doing simple things. For example, a crash has just occurred when I tried to set the plugin offline. Others happen when I close the project in which Sfizz is loaded. It happens quite frequently, and it doesn´t have to be a busy project; just one track with Sfizz can trigger the issue.

If you need a specific log or something, you can give me the instructions to get it and I will provide it for sure. The OS is Manjaro.

Greets!

**Comment by SoliDeoGloria2** [comment]
I forgot to mention that the crashes occur mostly with the VST3i version...

**Comment by jpcima** [comment]
Hi. Is the editor window open when the crash happens?

**Comment by jpcima** [comment]
Note: the fix #984 is just merged, which can fix a crash when the plugin is toggled active or inactive
That might help.
I know there's also a timer-related issue (#980).

**Comment by SoliDeoGloria2** [comment]
> Hi. Is the editor window open when the crash happens?

No, it has happened even with the UI disabled...

Excuse my ignorance, please, but : is it possible to try out the merge, or do I have to wait until a new pre-release it's out?

**Comment by jpcima** [comment]
When the head commit on github is marked with a green check mark, a development build is deployed.
You can get this at the download page (designated as "Current" / yellow)
https://sfz.tools/sfizz/downloads

**Comment by jpcima** [comment]
There are additional timer fixes as part of #986

**Comment by SoliDeoGloria2** [comment]
Well, a couple of hours after your first message I tried out the yellow latest release from the page, but the crash still occurred with VST3. If you need additional data, just tell me...

**Comment by jpcima** [comment]
The obs build was stuck because of a file renamed, sorry, this is fixed.
There is a fresh package stamped 20-Sep-2021 16:35.
https://download.opensuse.org/repositories/home:/sfztools:/sfizz:/develop/Arch/x86_64/

**Comment by SoliDeoGloria2** [comment]
Nice! Thanks so much! It works great now, as it seems. I'll be using it extensively in real life scenarios during these weeks, so I'll report if I see anything strange.
